### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  id: Binding.DestinationType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.EXCHANGE
  - Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.QUEUE
  langs:
  - csharp
  - vb
  name: Binding.DestinationType
  nameWithType: Binding.DestinationType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  type: Enum
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/Binding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: DestinationType
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/Binding.cs
    startLine: 21
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public enum DestinationType
    content.vb: Public Enum DestinationType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.QUEUE
  commentId: F:Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.QUEUE
  id: QUEUE
  parent: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  langs:
  - csharp
  - vb
  name: QUEUE
  nameWithType: Binding.DestinationType.QUEUE
  fullName: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.QUEUE
  type: Field
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/Binding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: QUEUE
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/Binding.cs
    startLine: 23
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: QUEUE = 0
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.EXCHANGE
  commentId: F:Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.EXCHANGE
  id: EXCHANGE
  parent: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  langs:
  - csharp
  - vb
  name: EXCHANGE
  nameWithType: Binding.DestinationType.EXCHANGE
  fullName: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType.EXCHANGE
  type: Field
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/Binding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: EXCHANGE
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/Binding.cs
    startLine: 24
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: EXCHANGE = 1
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: Binding.DestinationType
  nameWithType: Binding.DestinationType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
