### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.IBinderOptions
  commentId: T:Steeltoe.Stream.Config.IBinderOptions
  id: IBinderOptions
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
  - Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
  - Steeltoe.Stream.Config.IBinderOptions.Environment
  - Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
  langs:
  - csharp
  - vb
  name: IBinderOptions
  nameWithType: IBinderOptions
  fullName: Steeltoe.Stream.Config.IBinderOptions
  type: Interface
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBinderOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IBinderOptions
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBinderOptions.cs
    startLine: 11
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nContains the configuration options for a binder\n"
  example: []
  syntax:
    content: public interface IBinderOptions
    content.vb: Public Interface IBinderOptions
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
  commentId: P:Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
  id: ConfigureClass
  parent: Steeltoe.Stream.Config.IBinderOptions
  langs:
  - csharp
  - vb
  name: ConfigureClass
  nameWithType: IBinderOptions.ConfigureClass
  fullName: Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBinderOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigureClass
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBinderOptions.cs
    startLine: 13
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: string ConfigureClass { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ConfigureClass As String
  overload: Steeltoe.Stream.Config.IBinderOptions.ConfigureClass*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IBinderOptions.Environment
  commentId: P:Steeltoe.Stream.Config.IBinderOptions.Environment
  id: Environment
  parent: Steeltoe.Stream.Config.IBinderOptions
  langs:
  - csharp
  - vb
  name: Environment
  nameWithType: IBinderOptions.Environment
  fullName: Steeltoe.Stream.Config.IBinderOptions.Environment
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBinderOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Environment
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBinderOptions.cs
    startLine: 15
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: Dictionary<string, object> Environment { get; }
    parameters: []
    return:
      type: System.Collections.Generic.Dictionary{System.String,System.Object}
    content.vb: ReadOnly Property Environment As Dictionary(Of String, Object)
  overload: Steeltoe.Stream.Config.IBinderOptions.Environment*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
  commentId: P:Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
  id: InheritEnvironment
  parent: Steeltoe.Stream.Config.IBinderOptions
  langs:
  - csharp
  - vb
  name: InheritEnvironment
  nameWithType: IBinderOptions.InheritEnvironment
  fullName: Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBinderOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InheritEnvironment
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBinderOptions.cs
    startLine: 17
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: bool InheritEnvironment { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property InheritEnvironment As Boolean
  overload: Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
  commentId: P:Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
  id: DefaultCandidate
  parent: Steeltoe.Stream.Config.IBinderOptions
  langs:
  - csharp
  - vb
  name: DefaultCandidate
  nameWithType: IBinderOptions.DefaultCandidate
  fullName: Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBinderOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: DefaultCandidate
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBinderOptions.cs
    startLine: 19
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: bool DefaultCandidate { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property DefaultCandidate As Boolean
  overload: Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: Steeltoe.Stream.Config.IBinderOptions.ConfigureClass*
  commentId: Overload:Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
  name: ConfigureClass
  nameWithType: IBinderOptions.ConfigureClass
  fullName: Steeltoe.Stream.Config.IBinderOptions.ConfigureClass
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Stream.Config.IBinderOptions.Environment*
  commentId: Overload:Steeltoe.Stream.Config.IBinderOptions.Environment
  name: Environment
  nameWithType: IBinderOptions.Environment
  fullName: Steeltoe.Stream.Config.IBinderOptions.Environment
- uid: System.Collections.Generic.Dictionary{System.String,System.Object}
  commentId: T:System.Collections.Generic.Dictionary{System.String,System.Object}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.Dictionary`2
  name: Dictionary<String, Object>
  nameWithType: Dictionary<String, Object>
  fullName: System.Collections.Generic.Dictionary<System.String, System.Object>
  nameWithType.vb: Dictionary(Of String, Object)
  fullName.vb: System.Collections.Generic.Dictionary(Of System.String, System.Object)
  name.vb: Dictionary(Of String, Object)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.Dictionary`2
  commentId: T:System.Collections.Generic.Dictionary`2
  isExternal: true
  name: Dictionary<TKey, TValue>
  nameWithType: Dictionary<TKey, TValue>
  fullName: System.Collections.Generic.Dictionary<TKey, TValue>
  nameWithType.vb: Dictionary(Of TKey, TValue)
  fullName.vb: System.Collections.Generic.Dictionary(Of TKey, TValue)
  name.vb: Dictionary(Of TKey, TValue)
  spec.csharp:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.Dictionary`2
    name: Dictionary
    nameWithType: Dictionary
    fullName: System.Collections.Generic.Dictionary
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TKey
    nameWithType: TKey
    fullName: TKey
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - name: TValue
    nameWithType: TValue
    fullName: TValue
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment*
  commentId: Overload:Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
  name: InheritEnvironment
  nameWithType: IBinderOptions.InheritEnvironment
  fullName: Steeltoe.Stream.Config.IBinderOptions.InheritEnvironment
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate*
  commentId: Overload:Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
  name: DefaultCandidate
  nameWithType: IBinderOptions.DefaultCandidate
  fullName: Steeltoe.Stream.Config.IBinderOptions.DefaultCandidate
