### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  id: RandomValueSource
  parent: Steeltoe.Extensions.Configuration.RandomValue
  children:
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(ILoggerFactory)
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(System.String,ILoggerFactory)
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build(IConfigurationBuilder)
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.PREFIX
  langs:
  - csharp
  - vb
  name: RandomValueSource
  nameWithType: RandomValueSource
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  type: Class
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RandomValueSource
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueSource.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nConfiguration source used in creating a <xref href=\"Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider\" data-throw-if-not-resolved=\"false\"></xref> that generates random numbers\n"
  example: []
  syntax:
    content: 'public class RandomValueSource : IConfigurationSource'
    content.vb: >-
      Public Class RandomValueSource

          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.PREFIX
  commentId: F:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.PREFIX
  id: PREFIX
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  langs:
  - csharp
  - vb
  name: PREFIX
  nameWithType: RandomValueSource.PREFIX
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.PREFIX
  type: Field
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: PREFIX
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueSource.cs
    startLine: 14
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  syntax:
    content: public const string PREFIX = "random:"
    return:
      type: System.String
    content.vb: Public Const PREFIX As String = "random:"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(ILoggerFactory)
  commentId: M:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(ILoggerFactory)
  id: '#ctor(ILoggerFactory)'
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  langs:
  - csharp
  - vb
  name: RandomValueSource(ILoggerFactory)
  nameWithType: RandomValueSource.RandomValueSource(ILoggerFactory)
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.RandomValueSource(ILoggerFactory)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueSource.cs
    startLine: 22
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nInitializes a new instance of the <xref href=\"Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public RandomValueSource(ILoggerFactory logFactory = null)
    parameters:
    - id: logFactory
      type: ILoggerFactory
      description: the logger factory to use
    content.vb: Public Sub New(logFactory As ILoggerFactory = Nothing)
  overload: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(System.String,ILoggerFactory)
  commentId: M:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor(System.String,ILoggerFactory)
  id: '#ctor(System.String,ILoggerFactory)'
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  langs:
  - csharp
  - vb
  name: RandomValueSource(String, ILoggerFactory)
  nameWithType: RandomValueSource.RandomValueSource(String, ILoggerFactory)
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.RandomValueSource(System.String, ILoggerFactory)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueSource.cs
    startLine: 32
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nInitializes a new instance of the <xref href=\"Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource\" data-throw-if-not-resolved=\"false\"></xref> class.\n"
  example: []
  syntax:
    content: public RandomValueSource(string prefix, ILoggerFactory logFactory = null)
    parameters:
    - id: prefix
      type: System.String
      description: key prefix to use to match random number keys. Should end with the configuration seperator
    - id: logFactory
      type: ILoggerFactory
      description: the logger factory to use
    content.vb: Public Sub New(prefix As String, logFactory As ILoggerFactory = Nothing)
  overload: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build(IConfigurationBuilder)
  commentId: M:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: RandomValueSource.Build(IConfigurationBuilder)
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Build
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueSource.cs
    startLine: 43
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nBuilds a <xref href=\"Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider\" data-throw-if-not-resolved=\"false\"></xref> from the sources.\n"
  example: []
  syntax:
    content: public IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: the provided builder
    return:
      type: IConfigurationProvider
      description: the random number provider
    content.vb: Public Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
  name: RandomValueProvider
  nameWithType: RandomValueProvider
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
- uid: Steeltoe.Extensions.Configuration.RandomValue
  commentId: N:Steeltoe.Extensions.Configuration.RandomValue
  name: Steeltoe.Extensions.Configuration.RandomValue
  nameWithType: Steeltoe.Extensions.Configuration.RandomValue
  fullName: Steeltoe.Extensions.Configuration.RandomValue
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  name: RandomValueSource
  nameWithType: RandomValueSource
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor*
  commentId: Overload:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.#ctor
  name: RandomValueSource
  nameWithType: RandomValueSource.RandomValueSource
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.RandomValueSource
- uid: ILoggerFactory
  isExternal: true
  name: ILoggerFactory
  nameWithType: ILoggerFactory
  fullName: ILoggerFactory
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build*
  commentId: Overload:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build
  name: Build
  nameWithType: RandomValueSource.Build
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
