### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer
  commentId: T:Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer
  id: IMessageChannelAndSourceConfigurer
  parent: Steeltoe.Stream.Binding
  children:
  - Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource(Steeltoe.Stream.Binder.IPollableMessageSource,System.String)
  langs:
  - csharp
  - vb
  name: IMessageChannelAndSourceConfigurer
  nameWithType: IMessageChannelAndSourceConfigurer
  fullName: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer
  type: Interface
  source:
    remote:
      path: src/Stream/src/StreamBase/Binding/IMessageChannelAndSourceConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IMessageChannelAndSourceConfigurer
    path: ../Steeltoe/src/Stream/src/StreamBase/Binding/IMessageChannelAndSourceConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Binding
  syntax:
    content: 'public interface IMessageChannelAndSourceConfigurer : IMessageChannelConfigurer'
    content.vb: >-
      Public Interface IMessageChannelAndSourceConfigurer

          Inherits IMessageChannelConfigurer
  inheritedMembers:
  - Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  - Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource(Steeltoe.Stream.Binder.IPollableMessageSource,System.String)
  commentId: M:Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource(Steeltoe.Stream.Binder.IPollableMessageSource,System.String)
  id: ConfigurePolledMessageSource(Steeltoe.Stream.Binder.IPollableMessageSource,System.String)
  parent: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer
  langs:
  - csharp
  - vb
  name: ConfigurePolledMessageSource(IPollableMessageSource, String)
  nameWithType: IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource(IPollableMessageSource, String)
  fullName: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource(Steeltoe.Stream.Binder.IPollableMessageSource, System.String)
  type: Method
  source:
    remote:
      path: src/Stream/src/StreamBase/Binding/IMessageChannelAndSourceConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigurePolledMessageSource
    path: ../Steeltoe/src/Stream/src/StreamBase/Binding/IMessageChannelAndSourceConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Binding
  syntax:
    content: void ConfigurePolledMessageSource(IPollableMessageSource binding, string name)
    parameters:
    - id: binding
      type: Steeltoe.Stream.Binder.IPollableMessageSource
    - id: name
      type: System.String
    content.vb: Sub ConfigurePolledMessageSource(binding As IPollableMessageSource, name As String)
  overload: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource*
references:
- uid: Steeltoe.Stream.Binding
  commentId: N:Steeltoe.Stream.Binding
  name: Steeltoe.Stream.Binding
  nameWithType: Steeltoe.Stream.Binding
  fullName: Steeltoe.Stream.Binding
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  commentId: M:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  parent: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  isExternal: true
  name: ConfigureInputChannel(IMessageChannel, String)
  nameWithType: IMessageChannelConfigurer.ConfigureInputChannel(IMessageChannel, String)
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel, System.String)
  spec.csharp:
  - uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
    name: ConfigureInputChannel
    nameWithType: IMessageChannelConfigurer.ConfigureInputChannel
    fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel
  - name: (
    nameWithType: (
    fullName: (
  - uid: Steeltoe.Messaging.IMessageChannel
    name: IMessageChannel
    nameWithType: IMessageChannel
    fullName: Steeltoe.Messaging.IMessageChannel
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
    name: ConfigureInputChannel
    nameWithType: IMessageChannelConfigurer.ConfigureInputChannel
    fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel
  - name: (
    nameWithType: (
    fullName: (
  - uid: Steeltoe.Messaging.IMessageChannel
    name: IMessageChannel
    nameWithType: IMessageChannel
    fullName: Steeltoe.Messaging.IMessageChannel
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  commentId: M:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  parent: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  isExternal: true
  name: ConfigureOutputChannel(IMessageChannel, String)
  nameWithType: IMessageChannelConfigurer.ConfigureOutputChannel(IMessageChannel, String)
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel, System.String)
  spec.csharp:
  - uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
    name: ConfigureOutputChannel
    nameWithType: IMessageChannelConfigurer.ConfigureOutputChannel
    fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel
  - name: (
    nameWithType: (
    fullName: (
  - uid: Steeltoe.Messaging.IMessageChannel
    name: IMessageChannel
    nameWithType: IMessageChannel
    fullName: Steeltoe.Messaging.IMessageChannel
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
    name: ConfigureOutputChannel
    nameWithType: IMessageChannelConfigurer.ConfigureOutputChannel
    fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel
  - name: (
    nameWithType: (
    fullName: (
  - uid: Steeltoe.Messaging.IMessageChannel
    name: IMessageChannel
    nameWithType: IMessageChannel
    fullName: Steeltoe.Messaging.IMessageChannel
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  commentId: T:Steeltoe.Stream.Binding.IMessageChannelConfigurer
  parent: Steeltoe.Stream.Binding
  name: IMessageChannelConfigurer
  nameWithType: IMessageChannelConfigurer
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer
- uid: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource*
  commentId: Overload:Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource
  name: ConfigurePolledMessageSource
  nameWithType: IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource
  fullName: Steeltoe.Stream.Binding.IMessageChannelAndSourceConfigurer.ConfigurePolledMessageSource
- uid: Steeltoe.Stream.Binder.IPollableMessageSource
  commentId: T:Steeltoe.Stream.Binder.IPollableMessageSource
  parent: Steeltoe.Stream.Binder
  name: IPollableMessageSource
  nameWithType: IPollableMessageSource
  fullName: Steeltoe.Stream.Binder.IPollableMessageSource
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Stream.Binder
  commentId: N:Steeltoe.Stream.Binder
  name: Steeltoe.Stream.Binder
  nameWithType: Steeltoe.Stream.Binder
  fullName: Steeltoe.Stream.Binder
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
