### YamlMime:ManagedReference
items:
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions
  commentId: T:Steeltoe.Common.Security.PemConfigureCertificateOptions
  id: PemConfigureCertificateOptions
  parent: Steeltoe.Common.Security
  children:
  - Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor(IConfiguration)
  - Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(Steeltoe.Common.Options.CertificateOptions)
  - Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(System.String,Steeltoe.Common.Options.CertificateOptions)
  langs:
  - csharp
  - vb
  name: PemConfigureCertificateOptions
  nameWithType: PemConfigureCertificateOptions
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions
  type: Class
  source:
    remote:
      path: src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: PemConfigureCertificateOptions
    path: ../Steeltoe/src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
    startLine: 16
  assemblies:
  - Steeltoe.Common.Security
  namespace: Steeltoe.Common.Security
  syntax:
    content: 'public class PemConfigureCertificateOptions : IConfigureNamedOptions<CertificateOptions>'
    content.vb: >-
      Public Class PemConfigureCertificateOptions

          Inherits IConfigureNamedOptions(Of CertificateOptions)
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor(IConfiguration)
  commentId: M:Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor(IConfiguration)
  id: '#ctor(IConfiguration)'
  parent: Steeltoe.Common.Security.PemConfigureCertificateOptions
  langs:
  - csharp
  - vb
  name: PemConfigureCertificateOptions(IConfiguration)
  nameWithType: PemConfigureCertificateOptions.PemConfigureCertificateOptions(IConfiguration)
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions.PemConfigureCertificateOptions(IConfiguration)
  type: Constructor
  source:
    remote:
      path: src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
    startLine: 20
  assemblies:
  - Steeltoe.Common.Security
  namespace: Steeltoe.Common.Security
  syntax:
    content: public PemConfigureCertificateOptions(IConfiguration config)
    parameters:
    - id: config
      type: IConfiguration
    content.vb: Public Sub New(config As IConfiguration)
  overload: Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(System.String,Steeltoe.Common.Options.CertificateOptions)
  commentId: M:Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(System.String,Steeltoe.Common.Options.CertificateOptions)
  id: Configure(System.String,Steeltoe.Common.Options.CertificateOptions)
  parent: Steeltoe.Common.Security.PemConfigureCertificateOptions
  langs:
  - csharp
  - vb
  name: Configure(String, CertificateOptions)
  nameWithType: PemConfigureCertificateOptions.Configure(String, CertificateOptions)
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(System.String, Steeltoe.Common.Options.CertificateOptions)
  type: Method
  source:
    remote:
      path: src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
    startLine: 30
  assemblies:
  - Steeltoe.Common.Security
  namespace: Steeltoe.Common.Security
  syntax:
    content: public void Configure(string name, CertificateOptions options)
    parameters:
    - id: name
      type: System.String
    - id: options
      type: Steeltoe.Common.Options.CertificateOptions
    content.vb: Public Sub Configure(name As String, options As CertificateOptions)
  overload: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(Steeltoe.Common.Options.CertificateOptions)
  commentId: M:Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(Steeltoe.Common.Options.CertificateOptions)
  id: Configure(Steeltoe.Common.Options.CertificateOptions)
  parent: Steeltoe.Common.Security.PemConfigureCertificateOptions
  langs:
  - csharp
  - vb
  name: Configure(CertificateOptions)
  nameWithType: PemConfigureCertificateOptions.Configure(CertificateOptions)
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure(Steeltoe.Common.Options.CertificateOptions)
  type: Method
  source:
    remote:
      path: src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Common/src/Common.Security/PemConfigureCertificateOptions.cs
    startLine: 60
  assemblies:
  - Steeltoe.Common.Security
  namespace: Steeltoe.Common.Security
  syntax:
    content: public void Configure(CertificateOptions options)
    parameters:
    - id: options
      type: Steeltoe.Common.Options.CertificateOptions
    content.vb: Public Sub Configure(options As CertificateOptions)
  overload: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Common.Security
  commentId: N:Steeltoe.Common.Security
  name: Steeltoe.Common.Security
  nameWithType: Steeltoe.Common.Security
  fullName: Steeltoe.Common.Security
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor*
  commentId: Overload:Steeltoe.Common.Security.PemConfigureCertificateOptions.#ctor
  name: PemConfigureCertificateOptions
  nameWithType: PemConfigureCertificateOptions.PemConfigureCertificateOptions
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions.PemConfigureCertificateOptions
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure*
  commentId: Overload:Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure
  name: Configure
  nameWithType: PemConfigureCertificateOptions.Configure
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions.Configure
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Common.Options.CertificateOptions
  commentId: T:Steeltoe.Common.Options.CertificateOptions
  parent: Steeltoe.Common.Options
  name: CertificateOptions
  nameWithType: CertificateOptions
  fullName: Steeltoe.Common.Options.CertificateOptions
- uid: Steeltoe.Common.Options
  commentId: N:Steeltoe.Common.Options
  name: Steeltoe.Common.Options
  nameWithType: Steeltoe.Common.Options
  fullName: Steeltoe.Common.Options
