### YamlMime:ManagedReference
items:
- uid: Steeltoe.Integration.Config
  commentId: N:Steeltoe.Integration.Config
  id: Steeltoe.Integration.Config
  children:
  - Steeltoe.Integration.Config.ServiceActivatorAttributeProcessor
  langs:
  - csharp
  - vb
  name: Steeltoe.Integration.Config
  nameWithType: Steeltoe.Integration.Config
  fullName: Steeltoe.Integration.Config
  type: Namespace
  assemblies:
  - Steeltoe.Integration.IntegrationBase
references:
- uid: Steeltoe.Integration.Config.ServiceActivatorAttributeProcessor
  commentId: T:Steeltoe.Integration.Config.ServiceActivatorAttributeProcessor
  name: ServiceActivatorAttributeProcessor
  nameWithType: ServiceActivatorAttributeProcessor
  fullName: Steeltoe.Integration.Config.ServiceActivatorAttributeProcessor
