### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  id: CloudFoundryServicesOptions
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  children:
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfiguration)
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfigurationRoot)
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
  langs:
  - csharp
  - vb
  name: CloudFoundryServicesOptions
  nameWithType: CloudFoundryServicesOptions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  type: Class
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CloudFoundryServicesOptions
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 8
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: 'public class CloudFoundryServicesOptions : ServicesOptions, IServicesInfo'
    content.vb: >-
      Public Class CloudFoundryServicesOptions

          Inherits ServicesOptions

          Implements IServicesInfo
  inheritance:
  - System.Object
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions
  - Steeltoe.Extensions.Configuration.ServicesOptions
  implements:
  - Steeltoe.Extensions.Configuration.IServicesInfo
  inheritedMembers:
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Name
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Label
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Tags
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Plan
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Services
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration,System.String)
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
  id: ServicesConfigRoot
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  langs:
  - csharp
  - vb
  name: ServicesConfigRoot
  nameWithType: CloudFoundryServicesOptions.ServicesConfigRoot
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ServicesConfigRoot
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 10
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public static string ServicesConfigRoot { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Shared ReadOnly Property ServicesConfigRoot As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  id: CONFIGURATION_PREFIX
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  langs:
  - csharp
  - vb
  name: CONFIGURATION_PREFIX
  nameWithType: CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CONFIGURATION_PREFIX
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public override string CONFIGURATION_PREFIX { get; protected set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Overrides Property CONFIGURATION_PREFIX As String
  overridden: Steeltoe.Extensions.Configuration.AbstractServiceOptions.CONFIGURATION_PREFIX
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX*
  modifiers.csharp:
  - public
  - override
  - get
  - protected set
  modifiers.vb:
  - Public
  - Overrides
  - Get
  - Protected Set
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor
  id: '#ctor'
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  langs:
  - csharp
  - vb
  name: CloudFoundryServicesOptions()
  nameWithType: CloudFoundryServicesOptions.CloudFoundryServicesOptions()
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CloudFoundryServicesOptions()
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 15
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public CloudFoundryServicesOptions()
    content.vb: Public Sub New
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfigurationRoot)
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfigurationRoot)
  id: '#ctor(IConfigurationRoot)'
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  langs:
  - csharp
  - vb
  name: CloudFoundryServicesOptions(IConfigurationRoot)
  nameWithType: CloudFoundryServicesOptions.CloudFoundryServicesOptions(IConfigurationRoot)
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CloudFoundryServicesOptions(IConfigurationRoot)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 19
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public CloudFoundryServicesOptions(IConfigurationRoot root)
    parameters:
    - id: root
      type: IConfigurationRoot
    content.vb: Public Sub New(root As IConfigurationRoot)
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfiguration)
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor(IConfiguration)
  id: '#ctor(IConfiguration)'
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  langs:
  - csharp
  - vb
  name: CloudFoundryServicesOptions(IConfiguration)
  nameWithType: CloudFoundryServicesOptions.CloudFoundryServicesOptions(IConfiguration)
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CloudFoundryServicesOptions(IConfiguration)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryServicesOptions.cs
    startLine: 24
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public CloudFoundryServicesOptions(IConfiguration config)
    parameters:
    - id: config
      type: IConfiguration
    content.vb: Public Sub New(config As IConfiguration)
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  commentId: T:Steeltoe.Extensions.Configuration.AbstractServiceOptions
  parent: Steeltoe.Extensions.Configuration
  name: AbstractServiceOptions
  nameWithType: AbstractServiceOptions
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions
- uid: Steeltoe.Extensions.Configuration.ServicesOptions
  commentId: T:Steeltoe.Extensions.Configuration.ServicesOptions
  parent: Steeltoe.Extensions.Configuration
  name: ServicesOptions
  nameWithType: ServicesOptions
  fullName: Steeltoe.Extensions.Configuration.ServicesOptions
- uid: Steeltoe.Extensions.Configuration.IServicesInfo
  commentId: T:Steeltoe.Extensions.Configuration.IServicesInfo
  parent: Steeltoe.Extensions.Configuration
  name: IServicesInfo
  nameWithType: IServicesInfo
  fullName: Steeltoe.Extensions.Configuration.IServicesInfo
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Name
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Name
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: Name
  nameWithType: AbstractServiceOptions.Name
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Name
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Label
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Label
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: Label
  nameWithType: AbstractServiceOptions.Label
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Label
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Tags
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Tags
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: Tags
  nameWithType: AbstractServiceOptions.Tags
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Tags
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Plan
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Plan
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: Plan
  nameWithType: AbstractServiceOptions.Plan
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Plan
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Services
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Services
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: Services
  nameWithType: AbstractServiceOptions.Services
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Services
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
  commentId: M:Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: GetServicesList()
  nameWithType: AbstractServiceOptions.GetServicesList()
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList()
  spec.csharp:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
    name: GetServicesList
    nameWithType: AbstractServiceOptions.GetServicesList
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
    name: GetServicesList
    nameWithType: AbstractServiceOptions.GetServicesList
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetServicesList
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
  commentId: M:Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  isExternal: true
  name: GetInstancesOfType(String)
  nameWithType: AbstractServiceOptions.GetInstancesOfType(String)
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
  spec.csharp:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
    name: GetInstancesOfType
    nameWithType: AbstractServiceOptions.GetInstancesOfType
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType(System.String)
    name: GetInstancesOfType
    nameWithType: AbstractServiceOptions.GetInstancesOfType
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.GetInstancesOfType
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration,System.String)
  commentId: M:Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration,System.String)
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  isExternal: true
  name: Bind(IConfiguration, String)
  nameWithType: AbstractServiceOptions.Bind(IConfiguration, String)
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration, System.String)
  spec.csharp:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration,System.String)
    name: Bind
    nameWithType: AbstractServiceOptions.Bind
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind
  - name: (
    nameWithType: (
    fullName: (
  - uid: IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: IConfiguration
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind(IConfiguration,System.String)
    name: Bind
    nameWithType: AbstractServiceOptions.Bind
    fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.Bind
  - name: (
    nameWithType: (
    fullName: (
  - uid: IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: IConfiguration
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration
  commentId: N:Steeltoe.Extensions.Configuration
  name: Steeltoe.Extensions.Configuration
  nameWithType: Steeltoe.Extensions.Configuration
  fullName: Steeltoe.Extensions.Configuration
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
  name: ServicesConfigRoot
  nameWithType: CloudFoundryServicesOptions.ServicesConfigRoot
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.ServicesConfigRoot
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions.CONFIGURATION_PREFIX
  commentId: P:Steeltoe.Extensions.Configuration.AbstractServiceOptions.CONFIGURATION_PREFIX
  parent: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  name: CONFIGURATION_PREFIX
  nameWithType: AbstractServiceOptions.CONFIGURATION_PREFIX
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions.CONFIGURATION_PREFIX
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  name: CONFIGURATION_PREFIX
  nameWithType: CloudFoundryServicesOptions.CONFIGURATION_PREFIX
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CONFIGURATION_PREFIX
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.#ctor
  name: CloudFoundryServicesOptions
  nameWithType: CloudFoundryServicesOptions.CloudFoundryServicesOptions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions.CloudFoundryServicesOptions
- uid: IConfigurationRoot
  isExternal: true
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: IConfigurationRoot
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
