### YamlMime:ManagedReference
items:
- uid: Steeltoe.Common.Security
  commentId: N:Steeltoe.Common.Security
  id: Steeltoe.Common.Security
  children:
  - Steeltoe.Common.Security.CertificateProvider
  - Steeltoe.Common.Security.CertificateRotationService
  - Steeltoe.Common.Security.CertificateSource
  - Steeltoe.Common.Security.ConfigurationExtensions
  - Steeltoe.Common.Security.ConfigureCertificateOptions
  - Steeltoe.Common.Security.ICertificateRotationService
  - Steeltoe.Common.Security.LocalCertificateWriter
  - Steeltoe.Common.Security.PemCertificateProvider
  - Steeltoe.Common.Security.PemCertificateSource
  - Steeltoe.Common.Security.PemConfigureCertificateOptions
  langs:
  - csharp
  - vb
  name: Steeltoe.Common.Security
  nameWithType: Steeltoe.Common.Security
  fullName: Steeltoe.Common.Security
  type: Namespace
  assemblies:
  - Steeltoe.Common.Security
references:
- uid: Steeltoe.Common.Security.CertificateProvider
  commentId: T:Steeltoe.Common.Security.CertificateProvider
  name: CertificateProvider
  nameWithType: CertificateProvider
  fullName: Steeltoe.Common.Security.CertificateProvider
- uid: Steeltoe.Common.Security.CertificateRotationService
  commentId: T:Steeltoe.Common.Security.CertificateRotationService
  name: CertificateRotationService
  nameWithType: CertificateRotationService
  fullName: Steeltoe.Common.Security.CertificateRotationService
- uid: Steeltoe.Common.Security.CertificateSource
  commentId: T:Steeltoe.Common.Security.CertificateSource
  name: CertificateSource
  nameWithType: CertificateSource
  fullName: Steeltoe.Common.Security.CertificateSource
- uid: Steeltoe.Common.Security.ConfigurationExtensions
  commentId: T:Steeltoe.Common.Security.ConfigurationExtensions
  name: ConfigurationExtensions
  nameWithType: ConfigurationExtensions
  fullName: Steeltoe.Common.Security.ConfigurationExtensions
- uid: Steeltoe.Common.Security.ConfigureCertificateOptions
  commentId: T:Steeltoe.Common.Security.ConfigureCertificateOptions
  name: ConfigureCertificateOptions
  nameWithType: ConfigureCertificateOptions
  fullName: Steeltoe.Common.Security.ConfigureCertificateOptions
- uid: Steeltoe.Common.Security.ICertificateRotationService
  commentId: T:Steeltoe.Common.Security.ICertificateRotationService
  parent: Steeltoe.Common.Security
  name: ICertificateRotationService
  nameWithType: ICertificateRotationService
  fullName: Steeltoe.Common.Security.ICertificateRotationService
- uid: Steeltoe.Common.Security.LocalCertificateWriter
  commentId: T:Steeltoe.Common.Security.LocalCertificateWriter
  name: LocalCertificateWriter
  nameWithType: LocalCertificateWriter
  fullName: Steeltoe.Common.Security.LocalCertificateWriter
- uid: Steeltoe.Common.Security.PemCertificateProvider
  commentId: T:Steeltoe.Common.Security.PemCertificateProvider
  name: PemCertificateProvider
  nameWithType: PemCertificateProvider
  fullName: Steeltoe.Common.Security.PemCertificateProvider
- uid: Steeltoe.Common.Security.PemCertificateSource
  commentId: T:Steeltoe.Common.Security.PemCertificateSource
  name: PemCertificateSource
  nameWithType: PemCertificateSource
  fullName: Steeltoe.Common.Security.PemCertificateSource
- uid: Steeltoe.Common.Security.PemConfigureCertificateOptions
  commentId: T:Steeltoe.Common.Security.PemConfigureCertificateOptions
  name: PemConfigureCertificateOptions
  nameWithType: PemConfigureCertificateOptions
  fullName: Steeltoe.Common.Security.PemConfigureCertificateOptions
- uid: Steeltoe.Common.Security
  commentId: N:Steeltoe.Common.Security
  name: Steeltoe.Common.Security
  nameWithType: Steeltoe.Common.Security
  fullName: Steeltoe.Common.Security
