### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  id: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer,System.String[],System.Boolean)
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
  langs:
  - csharp
  - vb
  name: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: HeadersExchangeKeysBindingCreator
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 152
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class HeadersExchangeKeysBindingCreator
    content.vb: Public Class HeadersExchangeKeysBindingCreator
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer,System.String[],System.Boolean)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer,System.String[],System.Boolean)
  id: '#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer,System.String[],System.Boolean)'
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  langs:
  - csharp
  - vb
  name: HeadersExchangeKeysBindingCreator(BindingBuilder.HeadersExchangeMapConfigurer, String[], Boolean)
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator(BindingBuilder.HeadersExchangeMapConfigurer, String[], Boolean)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer, System.String[], System.Boolean)
  type: Constructor
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 157
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public HeadersExchangeKeysBindingCreator(BindingBuilder.HeadersExchangeMapConfigurer configurer, string[] headerKeys, bool matchAll)
    parameters:
    - id: configurer
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer
    - id: headerKeys
      type: System.String[]
    - id: matchAll
      type: System.Boolean
    content.vb: Public Sub New(configurer As BindingBuilder.HeadersExchangeMapConfigurer, headerKeys As String(), matchAll As Boolean)
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor*
  nameWithType.vb: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator(BindingBuilder.HeadersExchangeMapConfigurer, String(), Boolean)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer, System.String(), System.Boolean)
  name.vb: HeadersExchangeKeysBindingCreator(BindingBuilder.HeadersExchangeMapConfigurer, String(), Boolean)
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
  id: Exist
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator
  langs:
  - csharp
  - vb
  name: Exist()
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist()
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist()
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Exist
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 169
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public IBinding Exist()
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.IBinding
    content.vb: Public Function Exist As IBinding
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.#ctor
  name: HeadersExchangeKeysBindingCreator
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.HeadersExchangeKeysBindingCreator
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: BindingBuilder.HeadersExchangeMapConfigurer
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer
- uid: System.String[]
  isExternal: true
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullName.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ()
    nameWithType: ()
    fullName: ()
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
  name: Exist
  nameWithType: BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.HeadersExchangeMapConfigurer.HeadersExchangeKeysBindingCreator.Exist
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IBinding
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IBinding
  nameWithType: IBinding
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding
