### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  id: BindingBuilder.AbstractRoutingKeyConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,System.String)
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  langs:
  - csharp
  - vb
  name: BindingBuilder.AbstractRoutingKeyConfigurer
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: AbstractRoutingKeyConfigurer
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 213
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public abstract class AbstractRoutingKeyConfigurer
    content.vb: Public MustInherit Class AbstractRoutingKeyConfigurer
  inheritance:
  - System.Object
  derivedClasses:
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DirectExchangeRoutingKeyConfigurer
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.TopicExchangeRoutingKeyConfigurer
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - abstract
  - class
  modifiers.vb:
  - Public
  - MustInherit
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  id: Destination
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: Destination
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Destination
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 215
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public BindingBuilder.DestinationConfigurer Destination { get; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
    content.vb: Public ReadOnly Property Destination As BindingBuilder.DestinationConfigurer
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  id: ExchangeName
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: ExchangeName
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ExchangeName
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 217
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public string ExchangeName { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property ExchangeName As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,System.String)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,System.String)
  id: '#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,System.String)'
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: AbstractRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer, String)
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.AbstractRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer, String)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.AbstractRoutingKeyConfigurer(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer, System.String)
  type: Constructor
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 219
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: protected AbstractRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer destination, string exchange)
    parameters:
    - id: destination
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
    - id: exchange
      type: System.String
    content.vb: Protected Sub New(destination As BindingBuilder.DestinationConfigurer, exchange As String)
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor*
  modifiers.csharp:
  - protected
  modifiers.vb:
  - Protected
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  name: Destination
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: BindingBuilder.DestinationConfigurer
  nameWithType: BindingBuilder.DestinationConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  name: ExchangeName
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.#ctor
  name: AbstractRoutingKeyConfigurer
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.AbstractRoutingKeyConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.AbstractRoutingKeyConfigurer
