### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  commentId: T:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  id: EurekaApplicationsHealthContributor
  parent: Steeltoe.Discovery.Eureka
  children:
  - Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient,ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor})
  - Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health
  - Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
  langs:
  - csharp
  - vb
  name: EurekaApplicationsHealthContributor
  nameWithType: EurekaApplicationsHealthContributor
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  type: Class
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: EurekaApplicationsHealthContributor
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
    startLine: 13
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: 'public class EurekaApplicationsHealthContributor : IHealthContributor'
    content.vb: >-
      Public Class EurekaApplicationsHealthContributor

          Inherits IHealthContributor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient,ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor})
  commentId: M:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient,ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor})
  id: '#ctor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient,ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor})'
  parent: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  langs:
  - csharp
  - vb
  name: EurekaApplicationsHealthContributor(EurekaDiscoveryClient, ILogger<EurekaApplicationsHealthContributor>)
  nameWithType: EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor(EurekaDiscoveryClient, ILogger<EurekaApplicationsHealthContributor>)
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient, ILogger<Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor>)
  type: Constructor
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
    startLine: 18
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public EurekaApplicationsHealthContributor(EurekaDiscoveryClient discoveryClient, ILogger<EurekaApplicationsHealthContributor> logger = null)
    parameters:
    - id: discoveryClient
      type: Steeltoe.Discovery.Eureka.EurekaDiscoveryClient
    - id: logger
      type: ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor}
    content.vb: Public Sub New(discoveryClient As EurekaDiscoveryClient, logger As ILogger(Of EurekaApplicationsHealthContributor) = Nothing)
  overload: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor*
  nameWithType.vb: EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor(EurekaDiscoveryClient, ILogger(Of EurekaApplicationsHealthContributor))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor(Steeltoe.Discovery.Eureka.EurekaDiscoveryClient, ILogger(Of Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor))
  name.vb: EurekaApplicationsHealthContributor(EurekaDiscoveryClient, ILogger(Of EurekaApplicationsHealthContributor))
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health
  commentId: M:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health
  id: Health
  parent: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  langs:
  - csharp
  - vb
  name: Health()
  nameWithType: EurekaApplicationsHealthContributor.Health()
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health()
  type: Method
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Health
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
    startLine: 29
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public HealthCheckResult Health()
    return:
      type: HealthCheckResult
    content.vb: Public Function Health As HealthCheckResult
  overload: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
  commentId: P:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
  id: Id
  parent: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: EurekaApplicationsHealthContributor.Id
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
  type: Property
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Id
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaApplicationsHealthContributor.cs
    startLine: 110
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public string Id { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Id As String
  overload: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Steeltoe.Discovery.Eureka
  commentId: N:Steeltoe.Discovery.Eureka
  name: Steeltoe.Discovery.Eureka
  nameWithType: Steeltoe.Discovery.Eureka
  fullName: Steeltoe.Discovery.Eureka
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.#ctor
  name: EurekaApplicationsHealthContributor
  nameWithType: EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.EurekaApplicationsHealthContributor
- uid: Steeltoe.Discovery.Eureka.EurekaDiscoveryClient
  commentId: T:Steeltoe.Discovery.Eureka.EurekaDiscoveryClient
  parent: Steeltoe.Discovery.Eureka
  name: EurekaDiscoveryClient
  nameWithType: EurekaDiscoveryClient
  fullName: Steeltoe.Discovery.Eureka.EurekaDiscoveryClient
- uid: ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor}
  commentId: '!:ILogger{Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor}'
  definition: ILogger`1
  name: ILogger<EurekaApplicationsHealthContributor>
  nameWithType: ILogger<EurekaApplicationsHealthContributor>
  fullName: ILogger<Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor>
  nameWithType.vb: ILogger(Of EurekaApplicationsHealthContributor)
  fullName.vb: ILogger(Of Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor)
  name.vb: ILogger(Of EurekaApplicationsHealthContributor)
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
    name: EurekaApplicationsHealthContributor
    nameWithType: EurekaApplicationsHealthContributor
    fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
    name: EurekaApplicationsHealthContributor
    nameWithType: EurekaApplicationsHealthContributor
    fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor
  - name: )
    nameWithType: )
    fullName: )
- uid: ILogger`1
  isExternal: true
  name: ILogger<>
  nameWithType: ILogger<>
  fullName: ILogger<>
  nameWithType.vb: ILogger(Of )
  fullName.vb: ILogger(Of )
  name.vb: ILogger(Of )
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health
  name: Health
  nameWithType: EurekaApplicationsHealthContributor.Health
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Health
- uid: HealthCheckResult
  isExternal: true
  name: HealthCheckResult
  nameWithType: HealthCheckResult
  fullName: HealthCheckResult
- uid: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
  name: Id
  nameWithType: EurekaApplicationsHealthContributor.Id
  fullName: Steeltoe.Discovery.Eureka.EurekaApplicationsHealthContributor.Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
