### YamlMime:ManagedReference
items:
- uid: Steeltoe.Connector.MySql.MySqlProviderConfigurer
  commentId: T:Steeltoe.Connector.MySql.MySqlProviderConfigurer
  id: MySqlProviderConfigurer
  parent: Steeltoe.Connector.MySql
  children:
  - Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  - Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  langs:
  - csharp
  - vb
  name: MySqlProviderConfigurer
  nameWithType: MySqlProviderConfigurer
  fullName: Steeltoe.Connector.MySql.MySqlProviderConfigurer
  type: Class
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MySqlProviderConfigurer
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.MySql
  syntax:
    content: public class MySqlProviderConfigurer
    content.vb: Public Class MySqlProviderConfigurer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  commentId: M:Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  id: Configure(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  parent: Steeltoe.Connector.MySql.MySqlProviderConfigurer
  langs:
  - csharp
  - vb
  name: Configure(MySqlServiceInfo, MySqlProviderConnectorOptions)
  nameWithType: MySqlProviderConfigurer.Configure(MySqlServiceInfo, MySqlProviderConnectorOptions)
  fullName: Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure(Steeltoe.Connector.Services.MySqlServiceInfo, Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.MySql
  syntax:
    content: public string Configure(MySqlServiceInfo si, MySqlProviderConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.MySqlServiceInfo
    - id: configuration
      type: Steeltoe.Connector.MySql.MySqlProviderConnectorOptions
    return:
      type: System.String
    content.vb: Public Function Configure(si As MySqlServiceInfo, configuration As MySqlProviderConnectorOptions) As String
  overload: Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  commentId: M:Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  id: UpdateConfiguration(Steeltoe.Connector.Services.MySqlServiceInfo,Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  parent: Steeltoe.Connector.MySql.MySqlProviderConfigurer
  langs:
  - csharp
  - vb
  name: UpdateConfiguration(MySqlServiceInfo, MySqlProviderConnectorOptions)
  nameWithType: MySqlProviderConfigurer.UpdateConfiguration(MySqlServiceInfo, MySqlProviderConnectorOptions)
  fullName: Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.MySqlServiceInfo, Steeltoe.Connector.MySql.MySqlProviderConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: UpdateConfiguration
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/MySql/MySqlProviderConfigurer.cs
    startLine: 16
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.MySql
  syntax:
    content: public void UpdateConfiguration(MySqlServiceInfo si, MySqlProviderConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.MySqlServiceInfo
    - id: configuration
      type: Steeltoe.Connector.MySql.MySqlProviderConnectorOptions
    content.vb: Public Sub UpdateConfiguration(si As MySqlServiceInfo, configuration As MySqlProviderConnectorOptions)
  overload: Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Connector.MySql
  commentId: N:Steeltoe.Connector.MySql
  name: Steeltoe.Connector.MySql
  nameWithType: Steeltoe.Connector.MySql
  fullName: Steeltoe.Connector.MySql
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure*
  commentId: Overload:Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure
  name: Configure
  nameWithType: MySqlProviderConfigurer.Configure
  fullName: Steeltoe.Connector.MySql.MySqlProviderConfigurer.Configure
- uid: Steeltoe.Connector.Services.MySqlServiceInfo
  commentId: T:Steeltoe.Connector.Services.MySqlServiceInfo
  parent: Steeltoe.Connector.Services
  name: MySqlServiceInfo
  nameWithType: MySqlServiceInfo
  fullName: Steeltoe.Connector.Services.MySqlServiceInfo
- uid: Steeltoe.Connector.MySql.MySqlProviderConnectorOptions
  commentId: T:Steeltoe.Connector.MySql.MySqlProviderConnectorOptions
  parent: Steeltoe.Connector.MySql
  name: MySqlProviderConnectorOptions
  nameWithType: MySqlProviderConnectorOptions
  fullName: Steeltoe.Connector.MySql.MySqlProviderConnectorOptions
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Connector.Services
  commentId: N:Steeltoe.Connector.Services
  name: Steeltoe.Connector.Services
  nameWithType: Steeltoe.Connector.Services
  fullName: Steeltoe.Connector.Services
- uid: Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration*
  commentId: Overload:Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration
  name: UpdateConfiguration
  nameWithType: MySqlProviderConfigurer.UpdateConfiguration
  fullName: Steeltoe.Connector.MySql.MySqlProviderConfigurer.UpdateConfiguration
