### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer
  id: IDeclarableCustomizer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply(Steeltoe.Messaging.RabbitMQ.Config.IDeclarable)
  langs:
  - csharp
  - vb
  name: IDeclarableCustomizer
  nameWithType: IDeclarableCustomizer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IDeclarableCustomizer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IDeclarableCustomizer
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IDeclarableCustomizer.cs
    startLine: 6
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public interface IDeclarableCustomizer
    content.vb: Public Interface IDeclarableCustomizer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply(Steeltoe.Messaging.RabbitMQ.Config.IDeclarable)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply(Steeltoe.Messaging.RabbitMQ.Config.IDeclarable)
  id: Apply(Steeltoe.Messaging.RabbitMQ.Config.IDeclarable)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer
  langs:
  - csharp
  - vb
  name: Apply(IDeclarable)
  nameWithType: IDeclarableCustomizer.Apply(IDeclarable)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply(Steeltoe.Messaging.RabbitMQ.Config.IDeclarable)
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IDeclarableCustomizer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Apply
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IDeclarableCustomizer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: IDeclarable Apply(IDeclarable declarable)
    parameters:
    - id: declarable
      type: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
    content.vb: Function Apply(declarable As IDeclarable) As IDeclarable
  overload: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply*
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply
  name: Apply
  nameWithType: IDeclarableCustomizer.Apply
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarableCustomizer.Apply
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IDeclarable
  nameWithType: IDeclarable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
