### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer
  id: IRabbitListenerConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners(Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar)
  langs:
  - csharp
  - vb
  name: IRabbitListenerConfigurer
  nameWithType: IRabbitListenerConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IRabbitListenerConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IRabbitListenerConfigurer
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IRabbitListenerConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public interface IRabbitListenerConfigurer
    content.vb: Public Interface IRabbitListenerConfigurer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners(Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners(Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar)
  id: ConfigureRabbitListeners(Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer
  langs:
  - csharp
  - vb
  name: ConfigureRabbitListeners(IRabbitListenerEndpointRegistrar)
  nameWithType: IRabbitListenerConfigurer.ConfigureRabbitListeners(IRabbitListenerEndpointRegistrar)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners(Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar)
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IRabbitListenerConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigureRabbitListeners
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IRabbitListenerConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: void ConfigureRabbitListeners(IRabbitListenerEndpointRegistrar registrar)
    parameters:
    - id: registrar
      type: Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar
    content.vb: Sub ConfigureRabbitListeners(registrar As IRabbitListenerEndpointRegistrar)
  overload: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners*
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners
  name: ConfigureRabbitListeners
  nameWithType: IRabbitListenerConfigurer.ConfigureRabbitListeners
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerConfigurer.ConfigureRabbitListeners
- uid: Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar
  commentId: T:Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar
  parent: Steeltoe.Messaging.RabbitMQ.Listener
  name: IRabbitListenerEndpointRegistrar
  nameWithType: IRabbitListenerEndpointRegistrar
  fullName: Steeltoe.Messaging.RabbitMQ.Listener.IRabbitListenerEndpointRegistrar
- uid: Steeltoe.Messaging.RabbitMQ.Listener
  commentId: N:Steeltoe.Messaging.RabbitMQ.Listener
  name: Steeltoe.Messaging.RabbitMQ.Listener
  nameWithType: Steeltoe.Messaging.RabbitMQ.Listener
  fullName: Steeltoe.Messaging.RabbitMQ.Listener
