### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.StreamListenerMethod
  commentId: T:Steeltoe.Stream.Config.StreamListenerMethod
  id: StreamListenerMethod
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.StreamListenerMethod.#ctor(System.Reflection.MethodInfo,Steeltoe.Stream.Attributes.StreamListenerAttribute)
  - Steeltoe.Stream.Config.StreamListenerMethod.Attribute
  - Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
  - Steeltoe.Stream.Config.StreamListenerMethod.Method
  langs:
  - csharp
  - vb
  name: StreamListenerMethod
  nameWithType: StreamListenerMethod
  fullName: Steeltoe.Stream.Config.StreamListenerMethod
  type: Class
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: StreamListenerMethod
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
    startLine: 10
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: 'public class StreamListenerMethod : IStreamListenerMethod'
    content.vb: >-
      Public Class StreamListenerMethod

          Implements IStreamListenerMethod
  inheritance:
  - System.Object
  implements:
  - Steeltoe.Stream.Config.IStreamListenerMethod
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Stream.Config.StreamListenerMethod.#ctor(System.Reflection.MethodInfo,Steeltoe.Stream.Attributes.StreamListenerAttribute)
  commentId: M:Steeltoe.Stream.Config.StreamListenerMethod.#ctor(System.Reflection.MethodInfo,Steeltoe.Stream.Attributes.StreamListenerAttribute)
  id: '#ctor(System.Reflection.MethodInfo,Steeltoe.Stream.Attributes.StreamListenerAttribute)'
  parent: Steeltoe.Stream.Config.StreamListenerMethod
  langs:
  - csharp
  - vb
  name: StreamListenerMethod(MethodInfo, StreamListenerAttribute)
  nameWithType: StreamListenerMethod.StreamListenerMethod(MethodInfo, StreamListenerAttribute)
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.StreamListenerMethod(System.Reflection.MethodInfo, Steeltoe.Stream.Attributes.StreamListenerAttribute)
  type: Constructor
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
    startLine: 12
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: public StreamListenerMethod(MethodInfo method, StreamListenerAttribute attribute)
    parameters:
    - id: method
      type: System.Reflection.MethodInfo
    - id: attribute
      type: Steeltoe.Stream.Attributes.StreamListenerAttribute
    content.vb: Public Sub New(method As MethodInfo, attribute As StreamListenerAttribute)
  overload: Steeltoe.Stream.Config.StreamListenerMethod.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Stream.Config.StreamListenerMethod.Method
  commentId: P:Steeltoe.Stream.Config.StreamListenerMethod.Method
  id: Method
  parent: Steeltoe.Stream.Config.StreamListenerMethod
  langs:
  - csharp
  - vb
  name: Method
  nameWithType: StreamListenerMethod.Method
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.Method
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Method
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
    startLine: 18
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: public MethodInfo Method { get; }
    parameters: []
    return:
      type: System.Reflection.MethodInfo
    content.vb: Public ReadOnly Property Method As MethodInfo
  overload: Steeltoe.Stream.Config.StreamListenerMethod.Method*
  implements:
  - Steeltoe.Stream.Config.IStreamListenerMethod.Method
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Stream.Config.StreamListenerMethod.Attribute
  commentId: P:Steeltoe.Stream.Config.StreamListenerMethod.Attribute
  id: Attribute
  parent: Steeltoe.Stream.Config.StreamListenerMethod
  langs:
  - csharp
  - vb
  name: Attribute
  nameWithType: StreamListenerMethod.Attribute
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.Attribute
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Attribute
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
    startLine: 20
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: public StreamListenerAttribute Attribute { get; }
    parameters: []
    return:
      type: Steeltoe.Stream.Attributes.StreamListenerAttribute
    content.vb: Public ReadOnly Property Attribute As StreamListenerAttribute
  overload: Steeltoe.Stream.Config.StreamListenerMethod.Attribute*
  implements:
  - Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
  commentId: P:Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
  id: ImplementationType
  parent: Steeltoe.Stream.Config.StreamListenerMethod
  langs:
  - csharp
  - vb
  name: ImplementationType
  nameWithType: StreamListenerMethod.ImplementationType
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ImplementationType
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/StreamListenerMethod.cs
    startLine: 22
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: public Type ImplementationType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: Public ReadOnly Property ImplementationType As Type
  overload: Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType*
  implements:
  - Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Stream.Config.IStreamListenerMethod
  commentId: T:Steeltoe.Stream.Config.IStreamListenerMethod
  parent: Steeltoe.Stream.Config
  name: IStreamListenerMethod
  nameWithType: IStreamListenerMethod
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Stream.Config.StreamListenerMethod.#ctor*
  commentId: Overload:Steeltoe.Stream.Config.StreamListenerMethod.#ctor
  name: StreamListenerMethod
  nameWithType: StreamListenerMethod.StreamListenerMethod
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.StreamListenerMethod
- uid: System.Reflection.MethodInfo
  commentId: T:System.Reflection.MethodInfo
  parent: System.Reflection
  isExternal: true
  name: MethodInfo
  nameWithType: MethodInfo
  fullName: System.Reflection.MethodInfo
- uid: Steeltoe.Stream.Attributes.StreamListenerAttribute
  commentId: T:Steeltoe.Stream.Attributes.StreamListenerAttribute
  parent: Steeltoe.Stream.Attributes
  name: StreamListenerAttribute
  nameWithType: StreamListenerAttribute
  fullName: Steeltoe.Stream.Attributes.StreamListenerAttribute
- uid: System.Reflection
  commentId: N:System.Reflection
  isExternal: true
  name: System.Reflection
  nameWithType: System.Reflection
  fullName: System.Reflection
- uid: Steeltoe.Stream.Attributes
  commentId: N:Steeltoe.Stream.Attributes
  name: Steeltoe.Stream.Attributes
  nameWithType: Steeltoe.Stream.Attributes
  fullName: Steeltoe.Stream.Attributes
- uid: Steeltoe.Stream.Config.StreamListenerMethod.Method*
  commentId: Overload:Steeltoe.Stream.Config.StreamListenerMethod.Method
  name: Method
  nameWithType: StreamListenerMethod.Method
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.Method
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Method
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.Method
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  name: Method
  nameWithType: IStreamListenerMethod.Method
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Method
- uid: Steeltoe.Stream.Config.StreamListenerMethod.Attribute*
  commentId: Overload:Steeltoe.Stream.Config.StreamListenerMethod.Attribute
  name: Attribute
  nameWithType: StreamListenerMethod.Attribute
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.Attribute
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  name: Attribute
  nameWithType: IStreamListenerMethod.Attribute
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
- uid: Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType*
  commentId: Overload:Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
  name: ImplementationType
  nameWithType: StreamListenerMethod.ImplementationType
  fullName: Steeltoe.Stream.Config.StreamListenerMethod.ImplementationType
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  name: ImplementationType
  nameWithType: IStreamListenerMethod.ImplementationType
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
