### YamlMime:ManagedReference
items:
- uid: Steeltoe.Common.Kubernetes.ReloadSettings
  commentId: T:Steeltoe.Common.Kubernetes.ReloadSettings
  id: ReloadSettings
  parent: Steeltoe.Common.Kubernetes
  children:
  - Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
  - Steeltoe.Common.Kubernetes.ReloadSettings.Mode
  - Steeltoe.Common.Kubernetes.ReloadSettings.Period
  - Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
  langs:
  - csharp
  - vb
  name: ReloadSettings
  nameWithType: ReloadSettings
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings
  type: Class
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/ReloadSettings.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ReloadSettings
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/ReloadSettings.cs
    startLine: 6
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Common.Kubernetes
  syntax:
    content: public class ReloadSettings
    content.vb: Public Class ReloadSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Mode
  commentId: P:Steeltoe.Common.Kubernetes.ReloadSettings.Mode
  id: Mode
  parent: Steeltoe.Common.Kubernetes.ReloadSettings
  langs:
  - csharp
  - vb
  name: Mode
  nameWithType: ReloadSettings.Mode
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Mode
  type: Property
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/ReloadSettings.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Mode
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/ReloadSettings.cs
    startLine: 11
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Common.Kubernetes
  summary: "\nGets or sets the reload method (polling or event)\n"
  example: []
  syntax:
    content: public ReloadMethods Mode { get; set; }
    parameters: []
    return:
      type: Steeltoe.Common.Kubernetes.ReloadMethods
    content.vb: Public Property Mode As ReloadMethods
  overload: Steeltoe.Common.Kubernetes.ReloadSettings.Mode*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Period
  commentId: P:Steeltoe.Common.Kubernetes.ReloadSettings.Period
  id: Period
  parent: Steeltoe.Common.Kubernetes.ReloadSettings
  langs:
  - csharp
  - vb
  name: Period
  nameWithType: ReloadSettings.Period
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Period
  type: Property
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/ReloadSettings.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Period
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/ReloadSettings.cs
    startLine: 16
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Common.Kubernetes
  summary: "\nGets or sets the number of seconds before reloading config data\n"
  example: []
  syntax:
    content: public int Period { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Period As Integer
  overload: Steeltoe.Common.Kubernetes.ReloadSettings.Period*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
  commentId: P:Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
  id: ConfigMaps
  parent: Steeltoe.Common.Kubernetes.ReloadSettings
  langs:
  - csharp
  - vb
  name: ConfigMaps
  nameWithType: ReloadSettings.ConfigMaps
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
  type: Property
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/ReloadSettings.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigMaps
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/ReloadSettings.cs
    startLine: 21
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Common.Kubernetes
  summary: "\nGets or sets a value indicating whether config maps should be reloaded if changed\n"
  example: []
  syntax:
    content: public bool ConfigMaps { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property ConfigMaps As Boolean
  overload: Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
  commentId: P:Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
  id: Secrets
  parent: Steeltoe.Common.Kubernetes.ReloadSettings
  langs:
  - csharp
  - vb
  name: Secrets
  nameWithType: ReloadSettings.Secrets
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
  type: Property
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/ReloadSettings.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Secrets
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/ReloadSettings.cs
    startLine: 26
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Common.Kubernetes
  summary: "\nGets or sets a value indicating whether secrets should be reloaded if changed\n"
  example: []
  syntax:
    content: public bool Secrets { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Secrets As Boolean
  overload: Steeltoe.Common.Kubernetes.ReloadSettings.Secrets*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Common.Kubernetes
  commentId: N:Steeltoe.Common.Kubernetes
  name: Steeltoe.Common.Kubernetes
  nameWithType: Steeltoe.Common.Kubernetes
  fullName: Steeltoe.Common.Kubernetes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Mode*
  commentId: Overload:Steeltoe.Common.Kubernetes.ReloadSettings.Mode
  name: Mode
  nameWithType: ReloadSettings.Mode
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Mode
- uid: Steeltoe.Common.Kubernetes.ReloadMethods
  commentId: T:Steeltoe.Common.Kubernetes.ReloadMethods
  parent: Steeltoe.Common.Kubernetes
  name: ReloadMethods
  nameWithType: ReloadMethods
  fullName: Steeltoe.Common.Kubernetes.ReloadMethods
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Period*
  commentId: Overload:Steeltoe.Common.Kubernetes.ReloadSettings.Period
  name: Period
  nameWithType: ReloadSettings.Period
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Period
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps*
  commentId: Overload:Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
  name: ConfigMaps
  nameWithType: ReloadSettings.ConfigMaps
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.ConfigMaps
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Common.Kubernetes.ReloadSettings.Secrets*
  commentId: Overload:Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
  name: Secrets
  nameWithType: ReloadSettings.Secrets
  fullName: Steeltoe.Common.Kubernetes.ReloadSettings.Secrets
