### YamlMime:ManagedReference
items:
- uid: Steeltoe.Common.Configuration
  commentId: N:Steeltoe.Common.Configuration
  id: Steeltoe.Common.Configuration
  children:
  - Steeltoe.Common.Configuration.ConfigurationValuesHelper
  - Steeltoe.Common.Configuration.PropertyPlaceholderHelper
  langs:
  - csharp
  - vb
  name: Steeltoe.Common.Configuration
  nameWithType: Steeltoe.Common.Configuration
  fullName: Steeltoe.Common.Configuration
  type: Namespace
  assemblies:
  - Steeltoe.Common
references:
- uid: Steeltoe.Common.Configuration.ConfigurationValuesHelper
  commentId: T:Steeltoe.Common.Configuration.ConfigurationValuesHelper
  name: ConfigurationValuesHelper
  nameWithType: ConfigurationValuesHelper
  fullName: Steeltoe.Common.Configuration.ConfigurationValuesHelper
- uid: Steeltoe.Common.Configuration.PropertyPlaceholderHelper
  commentId: T:Steeltoe.Common.Configuration.PropertyPlaceholderHelper
  name: PropertyPlaceholderHelper
  nameWithType: PropertyPlaceholderHelper
  fullName: Steeltoe.Common.Configuration.PropertyPlaceholderHelper
