### YamlMime:ManagedReference
items:
- uid: Steeltoe.Common.IApplicationTask
  commentId: T:Steeltoe.Common.IApplicationTask
  id: IApplicationTask
  parent: Steeltoe.Common
  children:
  - Steeltoe.Common.IApplicationTask.Name
  - Steeltoe.Common.IApplicationTask.Run
  langs:
  - csharp
  - vb
  name: IApplicationTask
  nameWithType: IApplicationTask
  fullName: Steeltoe.Common.IApplicationTask
  type: Interface
  source:
    remote:
      path: src/Common/src/Abstractions/IApplicationTask.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IApplicationTask
    path: ../Steeltoe/src/Common/src/Abstractions/IApplicationTask.cs
    startLine: 9
  assemblies:
  - Steeltoe.Common.Abstractions
  namespace: Steeltoe.Common
  summary: "\nA runnable task bundled with the assembly that can be executed on-demand\n"
  example: []
  syntax:
    content: public interface IApplicationTask
    content.vb: Public Interface IApplicationTask
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Common.IApplicationTask.Name
  commentId: P:Steeltoe.Common.IApplicationTask.Name
  id: Name
  parent: Steeltoe.Common.IApplicationTask
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: IApplicationTask.Name
  fullName: Steeltoe.Common.IApplicationTask.Name
  type: Property
  source:
    remote:
      path: src/Common/src/Abstractions/IApplicationTask.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Name
    path: ../Steeltoe/src/Common/src/Abstractions/IApplicationTask.cs
    startLine: 14
  assemblies:
  - Steeltoe.Common.Abstractions
  namespace: Steeltoe.Common
  summary: "\nGets globally unique name for the task\n"
  example: []
  syntax:
    content: string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property Name As String
  overload: Steeltoe.Common.IApplicationTask.Name*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Common.IApplicationTask.Run
  commentId: M:Steeltoe.Common.IApplicationTask.Run
  id: Run
  parent: Steeltoe.Common.IApplicationTask
  langs:
  - csharp
  - vb
  name: Run()
  nameWithType: IApplicationTask.Run()
  fullName: Steeltoe.Common.IApplicationTask.Run()
  type: Method
  source:
    remote:
      path: src/Common/src/Abstractions/IApplicationTask.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Run
    path: ../Steeltoe/src/Common/src/Abstractions/IApplicationTask.cs
    startLine: 19
  assemblies:
  - Steeltoe.Common.Abstractions
  namespace: Steeltoe.Common
  summary: "\nAction which to run\n"
  example: []
  syntax:
    content: void Run()
    content.vb: Sub Run
  overload: Steeltoe.Common.IApplicationTask.Run*
references:
- uid: Steeltoe.Common
  commentId: N:Steeltoe.Common
  name: Steeltoe.Common
  nameWithType: Steeltoe.Common
  fullName: Steeltoe.Common
- uid: Steeltoe.Common.IApplicationTask.Name*
  commentId: Overload:Steeltoe.Common.IApplicationTask.Name
  name: Name
  nameWithType: IApplicationTask.Name
  fullName: Steeltoe.Common.IApplicationTask.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Common.IApplicationTask.Run*
  commentId: Overload:Steeltoe.Common.IApplicationTask.Run
  name: Run
  nameWithType: IApplicationTask.Run
  fullName: Steeltoe.Common.IApplicationTask.Run
