### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  commentId: T:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  id: ConfigurationDiscoveryClientExtension
  parent: Steeltoe.Discovery.Client.SimpleClients
  children:
  - Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices(IServiceCollection)
  - Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.CONFIG_PREFIX
  - Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  langs:
  - csharp
  - vb
  name: ConfigurationDiscoveryClientExtension
  nameWithType: ConfigurationDiscoveryClientExtension
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  type: Class
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigurationDiscoveryClientExtension
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
    startLine: 14
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  syntax:
    content: 'public class ConfigurationDiscoveryClientExtension : IDiscoveryClientExtension'
    content.vb: >-
      Public Class ConfigurationDiscoveryClientExtension

          Implements IDiscoveryClientExtension
  inheritance:
  - System.Object
  implements:
  - Steeltoe.Discovery.Client.IDiscoveryClientExtension
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.CONFIG_PREFIX
  commentId: F:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.CONFIG_PREFIX
  id: CONFIG_PREFIX
  parent: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  langs:
  - csharp
  - vb
  name: CONFIG_PREFIX
  nameWithType: ConfigurationDiscoveryClientExtension.CONFIG_PREFIX
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.CONFIG_PREFIX
  type: Field
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CONFIG_PREFIX
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
    startLine: 16
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  syntax:
    content: public const string CONFIG_PREFIX = "discovery:services"
    return:
      type: System.String
    content.vb: Public Const CONFIG_PREFIX As String = "discovery:services"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices(IServiceCollection)
  commentId: M:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices(IServiceCollection)
  id: ApplyServices(IServiceCollection)
  parent: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  langs:
  - csharp
  - vb
  name: ApplyServices(IServiceCollection)
  nameWithType: ConfigurationDiscoveryClientExtension.ApplyServices(IServiceCollection)
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices(IServiceCollection)
  type: Method
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ApplyServices
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
    startLine: 19
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  example: []
  syntax:
    content: public void ApplyServices(IServiceCollection services)
    parameters:
    - id: services
      type: IServiceCollection
    content.vb: Public Sub ApplyServices(services As IServiceCollection)
  overload: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices*
  implements:
  - Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  commentId: M:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  id: IsConfigured(IConfiguration,IServiceInfo)
  parent: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension
  langs:
  - csharp
  - vb
  name: IsConfigured(IConfiguration, IServiceInfo)
  nameWithType: ConfigurationDiscoveryClientExtension.IsConfigured(IConfiguration, IServiceInfo)
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured(IConfiguration, IServiceInfo)
  type: Method
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IsConfigured
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientExtension.cs
    startLine: 26
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  syntax:
    content: public bool IsConfigured(IConfiguration configuration, IServiceInfo serviceInfo = null)
    parameters:
    - id: configuration
      type: IConfiguration
    - id: serviceInfo
      type: IServiceInfo
    return:
      type: System.Boolean
    content.vb: Public Function IsConfigured(configuration As IConfiguration, serviceInfo As IServiceInfo = Nothing) As Boolean
  overload: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured*
  implements:
  - Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Discovery.Client.SimpleClients
  commentId: N:Steeltoe.Discovery.Client.SimpleClients
  name: Steeltoe.Discovery.Client.SimpleClients
  nameWithType: Steeltoe.Discovery.Client.SimpleClients
  fullName: Steeltoe.Discovery.Client.SimpleClients
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension
  commentId: T:Steeltoe.Discovery.Client.IDiscoveryClientExtension
  parent: Steeltoe.Discovery.Client
  name: IDiscoveryClientExtension
  nameWithType: IDiscoveryClientExtension
  fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery.Client
  commentId: N:Steeltoe.Discovery.Client
  name: Steeltoe.Discovery.Client
  nameWithType: Steeltoe.Discovery.Client
  fullName: Steeltoe.Discovery.Client
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices*
  commentId: Overload:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices
  name: ApplyServices
  nameWithType: ConfigurationDiscoveryClientExtension.ApplyServices
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.ApplyServices
- uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
  commentId: M:Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
  parent: Steeltoe.Discovery.Client.IDiscoveryClientExtension
  isExternal: true
  name: ApplyServices(IServiceCollection)
  nameWithType: IDiscoveryClientExtension.ApplyServices(IServiceCollection)
  fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
  spec.csharp:
  - uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
    name: ApplyServices
    nameWithType: IDiscoveryClientExtension.ApplyServices
    fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices
  - name: (
    nameWithType: (
    fullName: (
  - uid: IServiceCollection
    name: IServiceCollection
    nameWithType: IServiceCollection
    fullName: IServiceCollection
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices(IServiceCollection)
    name: ApplyServices
    nameWithType: IDiscoveryClientExtension.ApplyServices
    fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.ApplyServices
  - name: (
    nameWithType: (
    fullName: (
  - uid: IServiceCollection
    name: IServiceCollection
    nameWithType: IServiceCollection
    fullName: IServiceCollection
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: IServiceCollection
  isExternal: true
  name: IServiceCollection
  nameWithType: IServiceCollection
  fullName: IServiceCollection
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured*
  commentId: Overload:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured
  name: IsConfigured
  nameWithType: ConfigurationDiscoveryClientExtension.IsConfigured
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientExtension.IsConfigured
- uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  commentId: M:Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
  parent: Steeltoe.Discovery.Client.IDiscoveryClientExtension
  isExternal: true
  name: IsConfigured(IConfiguration, IServiceInfo)
  nameWithType: IDiscoveryClientExtension.IsConfigured(IConfiguration, IServiceInfo)
  fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration, IServiceInfo)
  spec.csharp:
  - uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
    name: IsConfigured
    nameWithType: IDiscoveryClientExtension.IsConfigured
    fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured
  - name: (
    nameWithType: (
    fullName: (
  - uid: IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: IConfiguration
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: IServiceInfo
    name: IServiceInfo
    nameWithType: IServiceInfo
    fullName: IServiceInfo
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured(IConfiguration,IServiceInfo)
    name: IsConfigured
    nameWithType: IDiscoveryClientExtension.IsConfigured
    fullName: Steeltoe.Discovery.Client.IDiscoveryClientExtension.IsConfigured
  - name: (
    nameWithType: (
    fullName: (
  - uid: IConfiguration
    name: IConfiguration
    nameWithType: IConfiguration
    fullName: IConfiguration
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: IServiceInfo
    name: IServiceInfo
    nameWithType: IServiceInfo
    fullName: IServiceInfo
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
- uid: IServiceInfo
  isExternal: true
  name: IServiceInfo
  nameWithType: IServiceInfo
  fullName: IServiceInfo
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
