### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.HeaderMode
  commentId: T:Steeltoe.Stream.Config.HeaderMode
  id: HeaderMode
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.HeaderMode.EmbeddedHeaders
  - Steeltoe.Stream.Config.HeaderMode.Headers
  - Steeltoe.Stream.Config.HeaderMode.None
  langs:
  - csharp
  - vb
  name: HeaderMode
  nameWithType: HeaderMode
  fullName: Steeltoe.Stream.Config.HeaderMode
  type: Enum
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/HeaderMode.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: HeaderMode
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/HeaderMode.cs
    startLine: 9
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nSpecifies how headers are handled during message sending\n"
  example: []
  syntax:
    content: public enum HeaderMode
    content.vb: Public Enum HeaderMode
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Steeltoe.Stream.Config.HeaderMode.None
  commentId: F:Steeltoe.Stream.Config.HeaderMode.None
  id: None
  parent: Steeltoe.Stream.Config.HeaderMode
  langs:
  - csharp
  - vb
  name: None
  nameWithType: HeaderMode.None
  fullName: Steeltoe.Stream.Config.HeaderMode.None
  type: Field
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/HeaderMode.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: None
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/HeaderMode.cs
    startLine: 14
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nNo headers\n"
  example: []
  syntax:
    content: None = 0
    return:
      type: Steeltoe.Stream.Config.HeaderMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Steeltoe.Stream.Config.HeaderMode.Headers
  commentId: F:Steeltoe.Stream.Config.HeaderMode.Headers
  id: Headers
  parent: Steeltoe.Stream.Config.HeaderMode
  langs:
  - csharp
  - vb
  name: Headers
  nameWithType: HeaderMode.Headers
  fullName: Steeltoe.Stream.Config.HeaderMode.Headers
  type: Field
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/HeaderMode.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Headers
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/HeaderMode.cs
    startLine: 19
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nNative headers\n"
  example: []
  syntax:
    content: Headers = 1
    return:
      type: Steeltoe.Stream.Config.HeaderMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: Steeltoe.Stream.Config.HeaderMode.EmbeddedHeaders
  commentId: F:Steeltoe.Stream.Config.HeaderMode.EmbeddedHeaders
  id: EmbeddedHeaders
  parent: Steeltoe.Stream.Config.HeaderMode
  langs:
  - csharp
  - vb
  name: EmbeddedHeaders
  nameWithType: HeaderMode.EmbeddedHeaders
  fullName: Steeltoe.Stream.Config.HeaderMode.EmbeddedHeaders
  type: Field
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/HeaderMode.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: EmbeddedHeaders
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/HeaderMode.cs
    startLine: 24
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nHeaders embedded in payload e.g. kafka less than 0.11\n"
  example: []
  syntax:
    content: EmbeddedHeaders = 2
    return:
      type: Steeltoe.Stream.Config.HeaderMode
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: Steeltoe.Stream.Config.HeaderMode
  commentId: T:Steeltoe.Stream.Config.HeaderMode
  parent: Steeltoe.Stream.Config
  name: HeaderMode
  nameWithType: HeaderMode
  fullName: Steeltoe.Stream.Config.HeaderMode
