### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  id: BindingBuilder.GenericExchangeRoutingKeyConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,Steeltoe.Messaging.RabbitMQ.Config.IExchange)
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.Enum)
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.String)
  langs:
  - csharp
  - vb
  name: BindingBuilder.GenericExchangeRoutingKeyConfigurer
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GenericExchangeRoutingKeyConfigurer
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 246
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: 'public class GenericExchangeRoutingKeyConfigurer : BindingBuilder.AbstractRoutingKeyConfigurer'
    content.vb: >-
      Public Class GenericExchangeRoutingKeyConfigurer

          Inherits BindingBuilder.AbstractRoutingKeyConfigurer
  inheritance:
  - System.Object
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  inheritedMembers:
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  - Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,Steeltoe.Messaging.RabbitMQ.Config.IExchange)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,Steeltoe.Messaging.RabbitMQ.Config.IExchange)
  id: '#ctor(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer,Steeltoe.Messaging.RabbitMQ.Config.IExchange)'
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: GenericExchangeRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer, IExchange)
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer.GenericExchangeRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer, IExchange)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.GenericExchangeRoutingKeyConfigurer(Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer, Steeltoe.Messaging.RabbitMQ.Config.IExchange)
  type: Constructor
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 248
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public GenericExchangeRoutingKeyConfigurer(BindingBuilder.DestinationConfigurer destination, IExchange exchange)
    parameters:
    - id: destination
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
    - id: exchange
      type: Steeltoe.Messaging.RabbitMQ.Config.IExchange
    content.vb: Public Sub New(destination As BindingBuilder.DestinationConfigurer, exchange As IExchange)
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.String)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.String)
  id: With(System.String)
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: With(String)
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(String)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.String)
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: With
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 253
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public BindingBuilder.GenericArgumentsConfigurer With(string routingKey)
    parameters:
    - id: routingKey
      type: System.String
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericArgumentsConfigurer
    content.vb: Public Function With(routingKey As String) As BindingBuilder.GenericArgumentsConfigurer
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.Enum)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.Enum)
  id: With(System.Enum)
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer
  langs:
  - csharp
  - vb
  name: With(Enum)
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(Enum)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With(System.Enum)
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: With
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/BindingBuilder.cs
    startLine: 258
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public BindingBuilder.GenericArgumentsConfigurer With(Enum routingKeyEnum)
    parameters:
    - id: routingKeyEnum
      type: System.Enum
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericArgumentsConfigurer
    content.vb: Public Function With(routingKeyEnum As  Enum) As BindingBuilder.GenericArgumentsConfigurer
  overload: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: BindingBuilder.AbstractRoutingKeyConfigurer
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  name: Destination
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.Destination
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  parent: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer
  name: ExchangeName
  nameWithType: BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.AbstractRoutingKeyConfigurer.ExchangeName
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.#ctor
  name: GenericExchangeRoutingKeyConfigurer
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer.GenericExchangeRoutingKeyConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.GenericExchangeRoutingKeyConfigurer
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: BindingBuilder.DestinationConfigurer
  nameWithType: BindingBuilder.DestinationConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.DestinationConfigurer
- uid: Steeltoe.Messaging.RabbitMQ.Config.IExchange
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IExchange
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IExchange
  nameWithType: IExchange
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IExchange
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With
  name: With
  nameWithType: BindingBuilder.GenericExchangeRoutingKeyConfigurer.With
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericExchangeRoutingKeyConfigurer.With
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericArgumentsConfigurer
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericArgumentsConfigurer
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: BindingBuilder.GenericArgumentsConfigurer
  nameWithType: BindingBuilder.GenericArgumentsConfigurer
  fullName: Steeltoe.Messaging.RabbitMQ.Config.BindingBuilder.GenericArgumentsConfigurer
- uid: System.Enum
  commentId: T:System.Enum
  parent: System
  isExternal: true
  name: Enum
  nameWithType: Enum
  fullName: System.Enum
