### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.Kubernetes
  commentId: N:Steeltoe.Extensions.Configuration.Kubernetes
  id: Steeltoe.Extensions.Configuration.Kubernetes
  children:
  - Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  - Steeltoe.Extensions.Configuration.Kubernetes.KubernetesHostBuilderExtensions
  - Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration.Kubernetes
  nameWithType: Steeltoe.Extensions.Configuration.Kubernetes
  fullName: Steeltoe.Extensions.Configuration.Kubernetes
  type: Namespace
  assemblies:
  - Steeltoe.Common.Kubernetes
references:
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  commentId: T:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  name: StandardPodUtilities
  nameWithType: StandardPodUtilities
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
- uid: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  name: KubernetesConfigurationBuilderExtensions
  nameWithType: KubernetesConfigurationBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
- uid: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesHostBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.Kubernetes.KubernetesHostBuilderExtensions
  name: KubernetesHostBuilderExtensions
  nameWithType: KubernetesHostBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesHostBuilderExtensions
