### YamlMime:ManagedReference
items:
- uid: Steeltoe.CircuitBreaker.Hystrix.Config
  commentId: N:Steeltoe.CircuitBreaker.Hystrix.Config
  id: Steeltoe.CircuitBreaker.Hystrix.Config
  children:
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration.CollapserMetricsConfig
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandExecutionConfig
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandMetricsConfig
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfigurationStream
  - Steeltoe.CircuitBreaker.Hystrix.Config.HystrixThreadPoolConfiguration
  langs:
  - csharp
  - vb
  name: Steeltoe.CircuitBreaker.Hystrix.Config
  nameWithType: Steeltoe.CircuitBreaker.Hystrix.Config
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config
  type: Namespace
  assemblies:
  - Steeltoe.CircuitBreaker.HystrixBase
references:
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCollapserConfiguration
  nameWithType: HystrixCollapserConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration.CollapserMetricsConfig
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration.CollapserMetricsConfig
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCollapserConfiguration.CollapserMetricsConfig
  nameWithType: HystrixCollapserConfiguration.CollapserMetricsConfig
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCollapserConfiguration.CollapserMetricsConfig
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCommandConfiguration
  nameWithType: HystrixCommandConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
  nameWithType: HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandCircuitBreakerConfig
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandExecutionConfig
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandExecutionConfig
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCommandConfiguration.HystrixCommandExecutionConfig
  nameWithType: HystrixCommandConfiguration.HystrixCommandExecutionConfig
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandExecutionConfig
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandMetricsConfig
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandMetricsConfig
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixCommandConfiguration.HystrixCommandMetricsConfig
  nameWithType: HystrixCommandConfiguration.HystrixCommandMetricsConfig
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixCommandConfiguration.HystrixCommandMetricsConfig
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixConfiguration
  nameWithType: HystrixConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfigurationStream
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfigurationStream
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixConfigurationStream
  nameWithType: HystrixConfigurationStream
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfigurationStream
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixThreadPoolConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixThreadPoolConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixThreadPoolConfiguration
  nameWithType: HystrixThreadPoolConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixThreadPoolConfiguration
- uid: Steeltoe.CircuitBreaker.Hystrix.Config
  commentId: N:Steeltoe.CircuitBreaker.Hystrix.Config
  name: Steeltoe.CircuitBreaker.Hystrix.Config
  nameWithType: Steeltoe.CircuitBreaker.Hystrix.Config
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config
