### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  id: Steeltoe.Extensions.Configuration.CloudFoundry
  children:
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryApplicationOptions
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationBuilderExtensions
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryEnvironmentSettingsReader
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryHostBuilderExtensions
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryMemorySettingsReader
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServiceCollectionExtensions
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  - Steeltoe.Extensions.Configuration.CloudFoundry.IServiceCollectionExtensions
  - Steeltoe.Extensions.Configuration.CloudFoundry.Limits
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
  type: Namespace
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
references:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryApplicationOptions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryApplicationOptions
  name: CloudFoundryApplicationOptions
  nameWithType: CloudFoundryApplicationOptions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryApplicationOptions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationBuilderExtensions
  name: CloudFoundryConfigurationBuilderExtensions
  nameWithType: CloudFoundryConfigurationBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationBuilderExtensions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  name: CloudFoundryConfigurationProvider
  nameWithType: CloudFoundryConfigurationProvider
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  name: CloudFoundryConfigurationSource
  nameWithType: CloudFoundryConfigurationSource
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryEnvironmentSettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryEnvironmentSettingsReader
  name: CloudFoundryEnvironmentSettingsReader
  nameWithType: CloudFoundryEnvironmentSettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryEnvironmentSettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryMemorySettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryMemorySettingsReader
  name: CloudFoundryMemorySettingsReader
  nameWithType: CloudFoundryMemorySettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryMemorySettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
  name: CloudFoundryServicesOptions
  nameWithType: CloudFoundryServicesOptions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServicesOptions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  name: ICloudFoundrySettingsReader
  nameWithType: ICloudFoundrySettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.IServiceCollectionExtensions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.IServiceCollectionExtensions
  name: IServiceCollectionExtensions
  nameWithType: IServiceCollectionExtensions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.IServiceCollectionExtensions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.Limits
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.Limits
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  name: Limits
  nameWithType: Limits
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.Limits
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryHostBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryHostBuilderExtensions
  name: CloudFoundryHostBuilderExtensions
  nameWithType: CloudFoundryHostBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryHostBuilderExtensions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServiceCollectionExtensions
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServiceCollectionExtensions
  name: CloudFoundryServiceCollectionExtensions
  nameWithType: CloudFoundryServiceCollectionExtensions
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryServiceCollectionExtensions
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
