### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.RandomValue
  commentId: N:Steeltoe.Extensions.Configuration.RandomValue
  id: Steeltoe.Extensions.Configuration.RandomValue
  children:
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration.RandomValue
  nameWithType: Steeltoe.Extensions.Configuration.RandomValue
  fullName: Steeltoe.Extensions.Configuration.RandomValue
  type: Namespace
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
references:
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  name: RandomValueExtensions
  nameWithType: RandomValueExtensions
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
  name: RandomValueProvider
  nameWithType: RandomValueProvider
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueProvider
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
  name: RandomValueSource
  nameWithType: RandomValueSource
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueSource
