### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.ConfigServer
  commentId: N:Steeltoe.Extensions.Configuration.ConfigServer
  id: Steeltoe.Extensions.Configuration.ConfigServer
  children:
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigEnvironment
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettings
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettingsOptions
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensions
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensionsCore
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationSource
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerException
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHostBuilderExtensions
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerServiceCollectionExtensions
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigurationSettingsHelper
  - Steeltoe.Extensions.Configuration.ConfigServer.PropertySource
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigDiscovery
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigHealth
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration.ConfigServer
  nameWithType: Steeltoe.Extensions.Configuration.ConfigServer
  fullName: Steeltoe.Extensions.Configuration.ConfigServer
  type: Namespace
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
references:
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigEnvironment
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigEnvironment
  name: ConfigEnvironment
  nameWithType: ConfigEnvironment
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigEnvironment
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettings
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettings
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: ConfigServerClientSettings
  nameWithType: ConfigServerClientSettings
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettings
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettingsOptions
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettingsOptions
  name: ConfigServerClientSettingsOptions
  nameWithType: ConfigServerClientSettingsOptions
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerClientSettingsOptions
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensions
  name: ConfigServerConfigurationBuilderExtensions
  nameWithType: ConfigServerConfigurationBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensions
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider
  name: ConfigServerConfigurationProvider
  nameWithType: ConfigServerConfigurationProvider
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationProvider
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationSource
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationSource
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: ConfigServerConfigurationSource
  nameWithType: ConfigServerConfigurationSource
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationSource
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerException
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerException
  name: ConfigServerException
  nameWithType: ConfigServerException
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerException
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  name: ConfigServerHealthContributor
  nameWithType: ConfigServerHealthContributor
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigurationSettingsHelper
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigurationSettingsHelper
  name: ConfigurationSettingsHelper
  nameWithType: ConfigurationSettingsHelper
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigurationSettingsHelper
- uid: Steeltoe.Extensions.Configuration.ConfigServer.PropertySource
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.PropertySource
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: PropertySource
  nameWithType: PropertySource
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.PropertySource
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigDiscovery
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigDiscovery
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: SpringCloudConfigDiscovery
  nameWithType: SpringCloudConfigDiscovery
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigDiscovery
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigHealth
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigHealth
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: SpringCloudConfigHealth
  nameWithType: SpringCloudConfigHealth
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigHealth
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  name: SpringCloudConfigRetry
  nameWithType: SpringCloudConfigRetry
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensionsCore
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensionsCore
  name: ConfigServerConfigurationBuilderExtensionsCore
  nameWithType: ConfigServerConfigurationBuilderExtensionsCore
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerConfigurationBuilderExtensionsCore
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHostBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHostBuilderExtensions
  name: ConfigServerHostBuilderExtensions
  nameWithType: ConfigServerHostBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHostBuilderExtensions
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerServiceCollectionExtensions
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerServiceCollectionExtensions
  name: ConfigServerServiceCollectionExtensions
  nameWithType: ConfigServerServiceCollectionExtensions
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerServiceCollectionExtensions
- uid: Steeltoe.Extensions.Configuration.ConfigServer
  commentId: N:Steeltoe.Extensions.Configuration.ConfigServer
  name: Steeltoe.Extensions.Configuration.ConfigServer
  nameWithType: Steeltoe.Extensions.Configuration.ConfigServer
  fullName: Steeltoe.Extensions.Configuration.ConfigServer
