### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  commentId: T:Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  id: DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  parent: Steeltoe.Discovery.Client
  children:
  - Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor(IHostApplicationLifetime,Steeltoe.Discovery.IDiscoveryClient)
  - Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  langs:
  - csharp
  - vb
  name: DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  nameWithType: DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  fullName: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  type: Class
  source:
    remote:
      path: src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ApplicationLifecycle
    path: ../Steeltoe/src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
    startLine: 192
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client
  syntax:
    content: 'public class ApplicationLifecycle : IDiscoveryLifecycle'
    content.vb: >-
      Public Class ApplicationLifecycle

          Implements IDiscoveryLifecycle
  inheritance:
  - System.Object
  implements:
  - Steeltoe.Discovery.IDiscoveryLifecycle
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor(IHostApplicationLifetime,Steeltoe.Discovery.IDiscoveryClient)
  commentId: M:Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor(IHostApplicationLifetime,Steeltoe.Discovery.IDiscoveryClient)
  id: '#ctor(IHostApplicationLifetime,Steeltoe.Discovery.IDiscoveryClient)'
  parent: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  langs:
  - csharp
  - vb
  name: ApplicationLifecycle(IHostApplicationLifetime, IDiscoveryClient)
  nameWithType: DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationLifecycle(IHostApplicationLifetime, IDiscoveryClient)
  fullName: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationLifecycle(IHostApplicationLifetime, Steeltoe.Discovery.IDiscoveryClient)
  type: Constructor
  source:
    remote:
      path: src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
    startLine: 194
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client
  syntax:
    content: public ApplicationLifecycle(IHostApplicationLifetime lifeCycle, IDiscoveryClient client)
    parameters:
    - id: lifeCycle
      type: IHostApplicationLifetime
    - id: client
      type: Steeltoe.Discovery.IDiscoveryClient
    content.vb: Public Sub New(lifeCycle As IHostApplicationLifetime, client As IDiscoveryClient)
  overload: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  commentId: P:Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  id: ApplicationStopping
  parent: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle
  langs:
  - csharp
  - vb
  name: ApplicationStopping
  nameWithType: DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  fullName: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  type: Property
  source:
    remote:
      path: src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ApplicationStopping
    path: ../Steeltoe/src/Discovery/src/ClientBase/DiscoveryServiceCollectionExtensions.cs
    startLine: 205
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client
  syntax:
    content: public CancellationToken ApplicationStopping { get; set; }
    parameters: []
    return:
      type: System.Threading.CancellationToken
    content.vb: Public Property ApplicationStopping As CancellationToken
  overload: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping*
  implements:
  - Steeltoe.Discovery.IDiscoveryLifecycle.ApplicationStopping
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Discovery.Client
  commentId: N:Steeltoe.Discovery.Client
  name: Steeltoe.Discovery.Client
  nameWithType: Steeltoe.Discovery.Client
  fullName: Steeltoe.Discovery.Client
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Discovery.IDiscoveryLifecycle
  commentId: T:Steeltoe.Discovery.IDiscoveryLifecycle
  parent: Steeltoe.Discovery
  name: IDiscoveryLifecycle
  nameWithType: IDiscoveryLifecycle
  fullName: Steeltoe.Discovery.IDiscoveryLifecycle
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery
  commentId: N:Steeltoe.Discovery
  name: Steeltoe.Discovery
  nameWithType: Steeltoe.Discovery
  fullName: Steeltoe.Discovery
- uid: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor*
  commentId: Overload:Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.#ctor
  name: ApplicationLifecycle
  nameWithType: DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationLifecycle
  fullName: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationLifecycle
- uid: IHostApplicationLifetime
  commentId: '!:IHostApplicationLifetime'
  isExternal: true
  name: IHostApplicationLifetime
  nameWithType: IHostApplicationLifetime
  fullName: IHostApplicationLifetime
- uid: Steeltoe.Discovery.IDiscoveryClient
  commentId: T:Steeltoe.Discovery.IDiscoveryClient
  parent: Steeltoe.Discovery
  name: IDiscoveryClient
  nameWithType: IDiscoveryClient
  fullName: Steeltoe.Discovery.IDiscoveryClient
- uid: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping*
  commentId: Overload:Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  name: ApplicationStopping
  nameWithType: DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
  fullName: Steeltoe.Discovery.Client.DiscoveryServiceCollectionExtensions.ApplicationLifecycle.ApplicationStopping
- uid: Steeltoe.Discovery.IDiscoveryLifecycle.ApplicationStopping
  commentId: P:Steeltoe.Discovery.IDiscoveryLifecycle.ApplicationStopping
  parent: Steeltoe.Discovery.IDiscoveryLifecycle
  name: ApplicationStopping
  nameWithType: IDiscoveryLifecycle.ApplicationStopping
  fullName: Steeltoe.Discovery.IDiscoveryLifecycle.ApplicationStopping
- uid: System.Threading.CancellationToken
  commentId: T:System.Threading.CancellationToken
  parent: System.Threading
  isExternal: true
  name: CancellationToken
  nameWithType: CancellationToken
  fullName: System.Threading.CancellationToken
- uid: System.Threading
  commentId: N:System.Threading
  isExternal: true
  name: System.Threading
  nameWithType: System.Threading
  fullName: System.Threading
