### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.Placeholder
  commentId: N:Steeltoe.Extensions.Configuration.Placeholder
  id: Steeltoe.Extensions.Configuration.Placeholder
  children:
  - Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverConfigurationExtensions
  - Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverExtensions
  - Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverProvider
  - Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverSource
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration.Placeholder
  nameWithType: Steeltoe.Extensions.Configuration.Placeholder
  fullName: Steeltoe.Extensions.Configuration.Placeholder
  type: Namespace
  assemblies:
  - Steeltoe.Extensions.Configuration.PlaceholderBase
references:
- uid: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverConfigurationExtensions
  commentId: T:Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverConfigurationExtensions
  name: PlaceholderResolverConfigurationExtensions
  nameWithType: PlaceholderResolverConfigurationExtensions
  fullName: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverConfigurationExtensions
- uid: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverProvider
  commentId: T:Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverProvider
  name: PlaceholderResolverProvider
  nameWithType: PlaceholderResolverProvider
  fullName: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverProvider
- uid: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverSource
  commentId: T:Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverSource
  name: PlaceholderResolverSource
  nameWithType: PlaceholderResolverSource
  fullName: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverSource
- uid: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverExtensions
  commentId: T:Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverExtensions
  name: PlaceholderResolverExtensions
  nameWithType: PlaceholderResolverExtensions
  fullName: Steeltoe.Extensions.Configuration.Placeholder.PlaceholderResolverExtensions
