### YamlMime:ManagedReference
items:
- uid: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer
  commentId: T:Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer
  id: CosmosDbProviderConfigurer
  parent: Steeltoe.Connector.CosmosDb
  children:
  - Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  - Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  langs:
  - csharp
  - vb
  name: CosmosDbProviderConfigurer
  nameWithType: CosmosDbProviderConfigurer
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer
  type: Class
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CosmosDbProviderConfigurer
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.CosmosDb
  syntax:
    content: public class CosmosDbProviderConfigurer
    content.vb: Public Class CosmosDbProviderConfigurer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  commentId: M:Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  id: Configure(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  parent: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer
  langs:
  - csharp
  - vb
  name: Configure(CosmosDbServiceInfo, CosmosDbConnectorOptions)
  nameWithType: CosmosDbProviderConfigurer.Configure(CosmosDbServiceInfo, CosmosDbConnectorOptions)
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure(Steeltoe.Connector.Services.CosmosDbServiceInfo, Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.CosmosDb
  syntax:
    content: public string Configure(CosmosDbServiceInfo si, CosmosDbConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.CosmosDbServiceInfo
    - id: configuration
      type: Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions
    return:
      type: System.String
    content.vb: Public Function Configure(si As CosmosDbServiceInfo, configuration As CosmosDbConnectorOptions) As String
  overload: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  commentId: M:Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  id: UpdateConfiguration(Steeltoe.Connector.Services.CosmosDbServiceInfo,Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  parent: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer
  langs:
  - csharp
  - vb
  name: UpdateConfiguration(CosmosDbServiceInfo, CosmosDbConnectorOptions)
  nameWithType: CosmosDbProviderConfigurer.UpdateConfiguration(CosmosDbServiceInfo, CosmosDbConnectorOptions)
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.CosmosDbServiceInfo, Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: UpdateConfiguration
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/CosmosDb/CosmosDbProviderConfigurer.cs
    startLine: 16
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.CosmosDb
  syntax:
    content: public void UpdateConfiguration(CosmosDbServiceInfo si, CosmosDbConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.CosmosDbServiceInfo
    - id: configuration
      type: Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions
    content.vb: Public Sub UpdateConfiguration(si As CosmosDbServiceInfo, configuration As CosmosDbConnectorOptions)
  overload: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Connector.CosmosDb
  commentId: N:Steeltoe.Connector.CosmosDb
  name: Steeltoe.Connector.CosmosDb
  nameWithType: Steeltoe.Connector.CosmosDb
  fullName: Steeltoe.Connector.CosmosDb
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure*
  commentId: Overload:Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure
  name: Configure
  nameWithType: CosmosDbProviderConfigurer.Configure
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.Configure
- uid: Steeltoe.Connector.Services.CosmosDbServiceInfo
  commentId: T:Steeltoe.Connector.Services.CosmosDbServiceInfo
  parent: Steeltoe.Connector.Services
  name: CosmosDbServiceInfo
  nameWithType: CosmosDbServiceInfo
  fullName: Steeltoe.Connector.Services.CosmosDbServiceInfo
- uid: Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions
  commentId: T:Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions
  parent: Steeltoe.Connector.CosmosDb
  name: CosmosDbConnectorOptions
  nameWithType: CosmosDbConnectorOptions
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbConnectorOptions
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Connector.Services
  commentId: N:Steeltoe.Connector.Services
  name: Steeltoe.Connector.Services
  nameWithType: Steeltoe.Connector.Services
  fullName: Steeltoe.Connector.Services
- uid: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration*
  commentId: Overload:Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration
  name: UpdateConfiguration
  nameWithType: CosmosDbProviderConfigurer.UpdateConfiguration
  fullName: Steeltoe.Connector.CosmosDb.CosmosDbProviderConfigurer.UpdateConfiguration
