### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor
  id: IRabbitListenerAttributeProcessor
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize
  langs:
  - csharp
  - vb
  name: IRabbitListenerAttributeProcessor
  nameWithType: IRabbitListenerAttributeProcessor
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IRabbitListenerAttributeProcessor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IRabbitListenerAttributeProcessor
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IRabbitListenerAttributeProcessor.cs
    startLine: 8
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: 'public interface IRabbitListenerAttributeProcessor : IServiceNameAware'
    content.vb: >-
      Public Interface IRabbitListenerAttributeProcessor

          Inherits IServiceNameAware
  inheritedMembers:
  - Steeltoe.Common.Services.IServiceNameAware.ServiceName
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize
  id: Initialize
  parent: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor
  langs:
  - csharp
  - vb
  name: Initialize()
  nameWithType: IRabbitListenerAttributeProcessor.Initialize()
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize()
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IRabbitListenerAttributeProcessor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Initialize
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IRabbitListenerAttributeProcessor.cs
    startLine: 10
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: void Initialize()
    content.vb: Sub Initialize
  overload: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize*
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Common.Services.IServiceNameAware.ServiceName
  commentId: P:Steeltoe.Common.Services.IServiceNameAware.ServiceName
  parent: Steeltoe.Common.Services.IServiceNameAware
  name: ServiceName
  nameWithType: IServiceNameAware.ServiceName
  fullName: Steeltoe.Common.Services.IServiceNameAware.ServiceName
- uid: Steeltoe.Common.Services.IServiceNameAware
  commentId: T:Steeltoe.Common.Services.IServiceNameAware
  parent: Steeltoe.Common.Services
  name: IServiceNameAware
  nameWithType: IServiceNameAware
  fullName: Steeltoe.Common.Services.IServiceNameAware
- uid: Steeltoe.Common.Services
  commentId: N:Steeltoe.Common.Services
  name: Steeltoe.Common.Services
  nameWithType: Steeltoe.Common.Services
  fullName: Steeltoe.Common.Services
- uid: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize
  name: Initialize
  nameWithType: IRabbitListenerAttributeProcessor.Initialize
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IRabbitListenerAttributeProcessor.Initialize
