### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  id: RabbitOptions.RetryOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
  langs:
  - csharp
  - vb
  name: RabbitOptions.RetryOptions
  nameWithType: RabbitOptions.RetryOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RetryOptions
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 251
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class RetryOptions
    content.vb: Public Class RetryOptions
  inheritance:
  - System.Object
  derivedClasses:
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerRetryOptions
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
  id: Enabled
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: RabbitOptions.RetryOptions.Enabled
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Enabled
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 253
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
  id: MaxAttempts
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  langs:
  - csharp
  - vb
  name: MaxAttempts
  nameWithType: RabbitOptions.RetryOptions.MaxAttempts
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MaxAttempts
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 255
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public int MaxAttempts { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxAttempts As Integer
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
  id: InitialInterval
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  langs:
  - csharp
  - vb
  name: InitialInterval
  nameWithType: RabbitOptions.RetryOptions.InitialInterval
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InitialInterval
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 257
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public TimeSpan InitialInterval { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property InitialInterval As TimeSpan
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
  id: Multiplier
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  langs:
  - csharp
  - vb
  name: Multiplier
  nameWithType: RabbitOptions.RetryOptions.Multiplier
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Multiplier
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 259
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public double Multiplier { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Multiplier As Double
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
  id: MaxInterval
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions
  langs:
  - csharp
  - vb
  name: MaxInterval
  nameWithType: RabbitOptions.RetryOptions.MaxInterval
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MaxInterval
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 261
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public TimeSpan MaxInterval { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property MaxInterval As TimeSpan
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
  name: Enabled
  nameWithType: RabbitOptions.RetryOptions.Enabled
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
  name: MaxAttempts
  nameWithType: RabbitOptions.RetryOptions.MaxAttempts
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxAttempts
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
  name: InitialInterval
  nameWithType: RabbitOptions.RetryOptions.InitialInterval
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.InitialInterval
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
  name: Multiplier
  nameWithType: RabbitOptions.RetryOptions.Multiplier
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.Multiplier
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
  name: MaxInterval
  nameWithType: RabbitOptions.RetryOptions.MaxInterval
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.RetryOptions.MaxInterval
