### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  id: ContainerType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.ContainerType.DIRECT
  langs:
  - csharp
  - vb
  name: ContainerType
  nameWithType: ContainerType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  type: Enum
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ContainerType
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 363
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public enum ContainerType
    content.vb: Public Enum ContainerType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: Steeltoe.Messaging.RabbitMQ.Config.ContainerType.DIRECT
  commentId: F:Steeltoe.Messaging.RabbitMQ.Config.ContainerType.DIRECT
  id: DIRECT
  parent: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  langs:
  - csharp
  - vb
  name: DIRECT
  nameWithType: ContainerType.DIRECT
  fullName: Steeltoe.Messaging.RabbitMQ.Config.ContainerType.DIRECT
  type: Field
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: DIRECT
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 365
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: DIRECT = 0
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: ContainerType
  nameWithType: ContainerType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
