### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IBinding
  id: IBinding
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  langs:
  - csharp
  - vb
  name: IBinding
  nameWithType: IBinding
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IBinding
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 9
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: 'public interface IBinding : IDeclarable, IServiceNameAware'
    content.vb: >-
      Public Interface IBinding

          Inherits IDeclarable, IServiceNameAware
  inheritedMembers:
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  - Steeltoe.Common.Services.IServiceNameAware.ServiceName
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  id: BindingName
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: BindingName
  nameWithType: IBinding.BindingName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: BindingName
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 11
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string BindingName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property BindingName As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  id: Destination
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: Destination
  nameWithType: IBinding.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Destination
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 13
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string Destination { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Destination As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  id: Exchange
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: Exchange
  nameWithType: IBinding.Exchange
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Exchange
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 15
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string Exchange { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Exchange As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  id: RoutingKey
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: RoutingKey
  nameWithType: IBinding.RoutingKey
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RoutingKey
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 17
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string RoutingKey { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property RoutingKey As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  id: Type
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: IBinding.Type
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Type
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 19
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: Binding.DestinationType Type { get; set; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
    content.vb: Property Type As Binding.DestinationType
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  id: IsDestinationQueue
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  langs:
  - csharp
  - vb
  name: IsDestinationQueue
  nameWithType: IBinding.IsDestinationQueue
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IsDestinationQueue
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IBinding.cs
    startLine: 21
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: bool IsDestinationQueue { get; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: ReadOnly Property IsDestinationQueue As Boolean
  overload: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: ShouldDeclare
  nameWithType: IDeclarable.ShouldDeclare
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: DeclaringAdmins
  nameWithType: IDeclarable.DeclaringAdmins
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: IgnoreDeclarationExceptions
  nameWithType: IDeclarable.IgnoreDeclarationExceptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: Arguments
  nameWithType: IDeclarable.Arguments
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: AddArgument(String, Object)
  nameWithType: IDeclarable.AddArgument(String, Object)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String, System.Object)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: RemoveArgument(String)
  nameWithType: IDeclarable.RemoveArgument(String)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Common.Services.IServiceNameAware.ServiceName
  commentId: P:Steeltoe.Common.Services.IServiceNameAware.ServiceName
  parent: Steeltoe.Common.Services.IServiceNameAware
  name: ServiceName
  nameWithType: IServiceNameAware.ServiceName
  fullName: Steeltoe.Common.Services.IServiceNameAware.ServiceName
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IDeclarable
  nameWithType: IDeclarable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
- uid: Steeltoe.Common.Services.IServiceNameAware
  commentId: T:Steeltoe.Common.Services.IServiceNameAware
  parent: Steeltoe.Common.Services
  name: IServiceNameAware
  nameWithType: IServiceNameAware
  fullName: Steeltoe.Common.Services.IServiceNameAware
- uid: Steeltoe.Common.Services
  commentId: N:Steeltoe.Common.Services
  name: Steeltoe.Common.Services
  nameWithType: Steeltoe.Common.Services
  fullName: Steeltoe.Common.Services
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  name: BindingName
  nameWithType: IBinding.BindingName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  name: Destination
  nameWithType: IBinding.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  name: Exchange
  nameWithType: IBinding.Exchange
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  name: RoutingKey
  nameWithType: IBinding.RoutingKey
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  name: Type
  nameWithType: IBinding.Type
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
- uid: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: Binding.DestinationType
  nameWithType: Binding.DestinationType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.Binding.DestinationType
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  name: IsDestinationQueue
  nameWithType: IBinding.IsDestinationQueue
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
