### YamlMime:ManagedReference
items:
- uid: Steeltoe.Connector.ConnectionStringConfigurationSource
  commentId: T:Steeltoe.Connector.ConnectionStringConfigurationSource
  id: ConnectionStringConfigurationSource
  parent: Steeltoe.Connector
  children:
  - Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor(System.Collections.Generic.IList{IConfigurationSource})
  - Steeltoe.Connector.ConnectionStringConfigurationSource.Build(IConfigurationBuilder)
  langs:
  - csharp
  - vb
  name: ConnectionStringConfigurationSource
  nameWithType: ConnectionStringConfigurationSource
  fullName: Steeltoe.Connector.ConnectionStringConfigurationSource
  type: Class
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConnectionStringConfigurationSource
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
    startLine: 11
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector
  syntax:
    content: 'public class ConnectionStringConfigurationSource : IConfigurationSource'
    content.vb: >-
      Public Class ConnectionStringConfigurationSource

          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor(System.Collections.Generic.IList{IConfigurationSource})
  commentId: M:Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor(System.Collections.Generic.IList{IConfigurationSource})
  id: '#ctor(System.Collections.Generic.IList{IConfigurationSource})'
  parent: Steeltoe.Connector.ConnectionStringConfigurationSource
  langs:
  - csharp
  - vb
  name: ConnectionStringConfigurationSource(IList<IConfigurationSource>)
  nameWithType: ConnectionStringConfigurationSource.ConnectionStringConfigurationSource(IList<IConfigurationSource>)
  fullName: Steeltoe.Connector.ConnectionStringConfigurationSource.ConnectionStringConfigurationSource(System.Collections.Generic.IList<IConfigurationSource>)
  type: Constructor
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
    startLine: 15
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector
  syntax:
    content: public ConnectionStringConfigurationSource(IList<IConfigurationSource> sources)
    parameters:
    - id: sources
      type: System.Collections.Generic.IList{IConfigurationSource}
    content.vb: Public Sub New(sources As IList(Of IConfigurationSource))
  overload: Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor*
  nameWithType.vb: ConnectionStringConfigurationSource.ConnectionStringConfigurationSource(IList(Of IConfigurationSource))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Steeltoe.Connector.ConnectionStringConfigurationSource.ConnectionStringConfigurationSource(System.Collections.Generic.IList(Of IConfigurationSource))
  name.vb: ConnectionStringConfigurationSource(IList(Of IConfigurationSource))
- uid: Steeltoe.Connector.ConnectionStringConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Steeltoe.Connector.ConnectionStringConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Steeltoe.Connector.ConnectionStringConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: ConnectionStringConfigurationSource.Build(IConfigurationBuilder)
  fullName: Steeltoe.Connector.ConnectionStringConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Build
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/ConnectionStringConfigurationSource.cs
    startLine: 26
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector
  example: []
  syntax:
    content: public IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
    return:
      type: IConfigurationProvider
    content.vb: Public Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Steeltoe.Connector.ConnectionStringConfigurationSource.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Connector
  commentId: N:Steeltoe.Connector
  name: Steeltoe.Connector
  nameWithType: Steeltoe.Connector
  fullName: Steeltoe.Connector
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor*
  commentId: Overload:Steeltoe.Connector.ConnectionStringConfigurationSource.#ctor
  name: ConnectionStringConfigurationSource
  nameWithType: ConnectionStringConfigurationSource.ConnectionStringConfigurationSource
  fullName: Steeltoe.Connector.ConnectionStringConfigurationSource.ConnectionStringConfigurationSource
- uid: System.Collections.Generic.IList{IConfigurationSource}
  commentId: T:System.Collections.Generic.IList{IConfigurationSource}
  parent: System.Collections.Generic
  definition: System.Collections.Generic.IList`1
  name: IList<IConfigurationSource>
  nameWithType: IList<IConfigurationSource>
  fullName: System.Collections.Generic.IList<IConfigurationSource>
  nameWithType.vb: IList(Of IConfigurationSource)
  fullName.vb: System.Collections.Generic.IList(Of IConfigurationSource)
  name.vb: IList(Of IConfigurationSource)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: IConfigurationSource
    name: IConfigurationSource
    nameWithType: IConfigurationSource
    fullName: IConfigurationSource
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: IConfigurationSource
    name: IConfigurationSource
    nameWithType: IConfigurationSource
    fullName: IConfigurationSource
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IList`1
  commentId: T:System.Collections.Generic.IList`1
  isExternal: true
  name: IList<T>
  nameWithType: IList<T>
  fullName: System.Collections.Generic.IList<T>
  nameWithType.vb: IList(Of T)
  fullName.vb: System.Collections.Generic.IList(Of T)
  name.vb: IList(Of T)
  spec.csharp:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IList`1
    name: IList
    nameWithType: IList
    fullName: System.Collections.Generic.IList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic
  commentId: N:System.Collections.Generic
  isExternal: true
  name: System.Collections.Generic
  nameWithType: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: Steeltoe.Connector.ConnectionStringConfigurationSource.Build*
  commentId: Overload:Steeltoe.Connector.ConnectionStringConfigurationSource.Build
  name: Build
  nameWithType: ConnectionStringConfigurationSource.Build
  fullName: Steeltoe.Connector.ConnectionStringConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
