### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IExchangeBinding
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IExchangeBinding
  id: IExchangeBinding
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children: []
  langs:
  - csharp
  - vb
  name: IExchangeBinding
  nameWithType: IExchangeBinding
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IExchangeBinding
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IExchangeBinding.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IExchangeBinding
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IExchangeBinding.cs
    startLine: 6
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: 'public interface IExchangeBinding : IBinding, IDeclarable, IServiceNameAware'
    content.vb: >-
      Public Interface IExchangeBinding

          Inherits IBinding
  inheritedMembers:
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  - Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  - Steeltoe.Common.Services.IServiceNameAware.ServiceName
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: BindingName
  nameWithType: IBinding.BindingName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.BindingName
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: Destination
  nameWithType: IBinding.Destination
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Destination
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: Exchange
  nameWithType: IBinding.Exchange
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Exchange
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: RoutingKey
  nameWithType: IBinding.RoutingKey
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.RoutingKey
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: Type
  nameWithType: IBinding.Type
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.Type
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
  parent: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  name: IsDestinationQueue
  nameWithType: IBinding.IsDestinationQueue
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding.IsDestinationQueue
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: ShouldDeclare
  nameWithType: IDeclarable.ShouldDeclare
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: DeclaringAdmins
  nameWithType: IDeclarable.DeclaringAdmins
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: IgnoreDeclarationExceptions
  nameWithType: IDeclarable.IgnoreDeclarationExceptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: Arguments
  nameWithType: IDeclarable.Arguments
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: AddArgument(String, Object)
  nameWithType: IDeclarable.AddArgument(String, Object)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String, System.Object)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: RemoveArgument(String)
  nameWithType: IDeclarable.RemoveArgument(String)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Common.Services.IServiceNameAware.ServiceName
  commentId: P:Steeltoe.Common.Services.IServiceNameAware.ServiceName
  parent: Steeltoe.Common.Services.IServiceNameAware
  name: ServiceName
  nameWithType: IServiceNameAware.ServiceName
  fullName: Steeltoe.Common.Services.IServiceNameAware.ServiceName
- uid: Steeltoe.Messaging.RabbitMQ.Config.IBinding
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IBinding
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IBinding
  nameWithType: IBinding
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IBinding
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IDeclarable
  nameWithType: IDeclarable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
- uid: Steeltoe.Common.Services.IServiceNameAware
  commentId: T:Steeltoe.Common.Services.IServiceNameAware
  parent: Steeltoe.Common.Services
  name: IServiceNameAware
  nameWithType: IServiceNameAware
  fullName: Steeltoe.Common.Services.IServiceNameAware
- uid: Steeltoe.Common.Services
  commentId: N:Steeltoe.Common.Services
  name: Steeltoe.Common.Services
  nameWithType: Steeltoe.Common.Services
  fullName: Steeltoe.Common.Services
