### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  commentId: T:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  id: StandardPodUtilities
  parent: Steeltoe.Extensions.Configuration.Kubernetes
  children:
  - Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor(Steeltoe.Common.Kubernetes.KubernetesApplicationOptions,ILogger,IKubernetes)
  - Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync
  langs:
  - csharp
  - vb
  name: StandardPodUtilities
  nameWithType: StandardPodUtilities
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  type: Class
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: StandardPodUtilities
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
    startLine: 14
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Extensions.Configuration.Kubernetes
  syntax:
    content: 'public class StandardPodUtilities : IPodUtilities'
    content.vb: >-
      Public Class StandardPodUtilities

          Implements IPodUtilities
  inheritance:
  - System.Object
  implements:
  - Steeltoe.Common.Kubernetes.IPodUtilities
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor(Steeltoe.Common.Kubernetes.KubernetesApplicationOptions,ILogger,IKubernetes)
  commentId: M:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor(Steeltoe.Common.Kubernetes.KubernetesApplicationOptions,ILogger,IKubernetes)
  id: '#ctor(Steeltoe.Common.Kubernetes.KubernetesApplicationOptions,ILogger,IKubernetes)'
  parent: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  langs:
  - csharp
  - vb
  name: StandardPodUtilities(KubernetesApplicationOptions, ILogger, IKubernetes)
  nameWithType: StandardPodUtilities.StandardPodUtilities(KubernetesApplicationOptions, ILogger, IKubernetes)
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.StandardPodUtilities(Steeltoe.Common.Kubernetes.KubernetesApplicationOptions, ILogger, IKubernetes)
  type: Constructor
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
    startLine: 20
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Extensions.Configuration.Kubernetes
  syntax:
    content: public StandardPodUtilities(KubernetesApplicationOptions kubernetesApplicationOptions, ILogger logger = null, IKubernetes kubernetes = null)
    parameters:
    - id: kubernetesApplicationOptions
      type: Steeltoe.Common.Kubernetes.KubernetesApplicationOptions
    - id: logger
      type: ILogger
    - id: kubernetes
      type: IKubernetes
    content.vb: Public Sub New(kubernetesApplicationOptions As KubernetesApplicationOptions, logger As ILogger = Nothing, kubernetes As IKubernetes = Nothing)
  overload: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync
  commentId: M:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync
  id: GetCurrentPodAsync
  parent: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities
  langs:
  - csharp
  - vb
  name: GetCurrentPodAsync()
  nameWithType: StandardPodUtilities.GetCurrentPodAsync()
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync()
  type: Method
  source:
    remote:
      path: src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GetCurrentPodAsync
    path: ../Steeltoe/src/Common/src/Common.Kubernetes/StandardPodUtilities.cs
    startLine: 32
  assemblies:
  - Steeltoe.Common.Kubernetes
  namespace: Steeltoe.Extensions.Configuration.Kubernetes
  syntax:
    content: public Task<V1Pod> GetCurrentPodAsync()
    return:
      type: System.Threading.Tasks.Task{V1Pod}
    content.vb: Public Function GetCurrentPodAsync As Task(Of V1Pod)
  overload: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync*
  implements:
  - Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.Kubernetes
  commentId: N:Steeltoe.Extensions.Configuration.Kubernetes
  name: Steeltoe.Extensions.Configuration.Kubernetes
  nameWithType: Steeltoe.Extensions.Configuration.Kubernetes
  fullName: Steeltoe.Extensions.Configuration.Kubernetes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: Steeltoe.Common.Kubernetes.IPodUtilities
  commentId: T:Steeltoe.Common.Kubernetes.IPodUtilities
  parent: Steeltoe.Common.Kubernetes
  name: IPodUtilities
  nameWithType: IPodUtilities
  fullName: Steeltoe.Common.Kubernetes.IPodUtilities
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Common.Kubernetes
  commentId: N:Steeltoe.Common.Kubernetes
  name: Steeltoe.Common.Kubernetes
  nameWithType: Steeltoe.Common.Kubernetes
  fullName: Steeltoe.Common.Kubernetes
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor*
  commentId: Overload:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.#ctor
  name: StandardPodUtilities
  nameWithType: StandardPodUtilities.StandardPodUtilities
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.StandardPodUtilities
- uid: Steeltoe.Common.Kubernetes.KubernetesApplicationOptions
  commentId: T:Steeltoe.Common.Kubernetes.KubernetesApplicationOptions
  parent: Steeltoe.Common.Kubernetes
  name: KubernetesApplicationOptions
  nameWithType: KubernetesApplicationOptions
  fullName: Steeltoe.Common.Kubernetes.KubernetesApplicationOptions
- uid: ILogger
  isExternal: true
  name: ILogger
  nameWithType: ILogger
  fullName: ILogger
- uid: IKubernetes
  isExternal: true
  name: IKubernetes
  nameWithType: IKubernetes
  fullName: IKubernetes
- uid: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync*
  commentId: Overload:Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync
  name: GetCurrentPodAsync
  nameWithType: StandardPodUtilities.GetCurrentPodAsync
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.StandardPodUtilities.GetCurrentPodAsync
- uid: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
  commentId: M:Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
  parent: Steeltoe.Common.Kubernetes.IPodUtilities
  name: GetCurrentPodAsync()
  nameWithType: IPodUtilities.GetCurrentPodAsync()
  fullName: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync()
  spec.csharp:
  - uid: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
    name: GetCurrentPodAsync
    nameWithType: IPodUtilities.GetCurrentPodAsync
    fullName: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
    name: GetCurrentPodAsync
    nameWithType: IPodUtilities.GetCurrentPodAsync
    fullName: Steeltoe.Common.Kubernetes.IPodUtilities.GetCurrentPodAsync
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks.Task{V1Pod}
  commentId: T:System.Threading.Tasks.Task{V1Pod}
  parent: System.Threading.Tasks
  definition: System.Threading.Tasks.Task`1
  name: Task<V1Pod>
  nameWithType: Task<V1Pod>
  fullName: System.Threading.Tasks.Task<V1Pod>
  nameWithType.vb: Task(Of V1Pod)
  fullName.vb: System.Threading.Tasks.Task(Of V1Pod)
  name.vb: Task(Of V1Pod)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: V1Pod
    name: V1Pod
    nameWithType: V1Pod
    fullName: V1Pod
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: V1Pod
    name: V1Pod
    nameWithType: V1Pod
    fullName: V1Pod
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks.Task`1
  commentId: T:System.Threading.Tasks.Task`1
  isExternal: true
  name: Task<TResult>
  nameWithType: Task<TResult>
  fullName: System.Threading.Tasks.Task<TResult>
  nameWithType.vb: Task(Of TResult)
  fullName.vb: System.Threading.Tasks.Task(Of TResult)
  name.vb: Task(Of TResult)
  spec.csharp:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Threading.Tasks.Task`1
    name: Task
    nameWithType: Task
    fullName: System.Threading.Tasks.Task
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: TResult
    nameWithType: TResult
    fullName: TResult
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Threading.Tasks
  commentId: N:System.Threading.Tasks
  isExternal: true
  name: System.Threading.Tasks
  nameWithType: System.Threading.Tasks
  fullName: System.Threading.Tasks
