### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Consul.ConsulPostConfigurer
  commentId: T:Steeltoe.Discovery.Consul.ConsulPostConfigurer
  id: ConsulPostConfigurer
  parent: Steeltoe.Discovery.Consul
  children:
  - Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions(IConfiguration,Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions,InetOptions)
  - Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions(Steeltoe.Discovery.Consul.ConsulOptions)
  langs:
  - csharp
  - vb
  name: ConsulPostConfigurer
  nameWithType: ConsulPostConfigurer
  fullName: Steeltoe.Discovery.Consul.ConsulPostConfigurer
  type: Class
  source:
    remote:
      path: src/Discovery/src/Consul/ConsulPostConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConsulPostConfigurer
    path: ../Steeltoe/src/Discovery/src/Consul/ConsulPostConfigurer.cs
    startLine: 13
  assemblies:
  - Steeltoe.Discovery.Consul
  namespace: Steeltoe.Discovery.Consul
  syntax:
    content: public static class ConsulPostConfigurer
    content.vb: Public Module ConsulPostConfigurer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions(Steeltoe.Discovery.Consul.ConsulOptions)
  commentId: M:Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions(Steeltoe.Discovery.Consul.ConsulOptions)
  id: ValidateConsulOptions(Steeltoe.Discovery.Consul.ConsulOptions)
  parent: Steeltoe.Discovery.Consul.ConsulPostConfigurer
  langs:
  - csharp
  - vb
  name: ValidateConsulOptions(ConsulOptions)
  nameWithType: ConsulPostConfigurer.ValidateConsulOptions(ConsulOptions)
  fullName: Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions(Steeltoe.Discovery.Consul.ConsulOptions)
  type: Method
  source:
    remote:
      path: src/Discovery/src/Consul/ConsulPostConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ValidateConsulOptions
    path: ../Steeltoe/src/Discovery/src/Consul/ConsulPostConfigurer.cs
    startLine: 19
  assemblies:
  - Steeltoe.Discovery.Consul
  namespace: Steeltoe.Discovery.Consul
  summary: "\nAt PostConfigure, confirm that settings are valid for the current environment\n"
  example: []
  syntax:
    content: public static void ValidateConsulOptions(ConsulOptions options)
    parameters:
    - id: options
      type: Steeltoe.Discovery.Consul.ConsulOptions
      description: ConsulOptions to evaluate
    content.vb: Public Shared Sub ValidateConsulOptions(options As ConsulOptions)
  overload: Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions(IConfiguration,Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions,InetOptions)
  commentId: M:Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions(IConfiguration,Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions,InetOptions)
  id: UpdateDiscoveryOptions(IConfiguration,Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions,InetOptions)
  parent: Steeltoe.Discovery.Consul.ConsulPostConfigurer
  langs:
  - csharp
  - vb
  name: UpdateDiscoveryOptions(IConfiguration, ConsulDiscoveryOptions, InetOptions)
  nameWithType: ConsulPostConfigurer.UpdateDiscoveryOptions(IConfiguration, ConsulDiscoveryOptions, InetOptions)
  fullName: Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions(IConfiguration, Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions, InetOptions)
  type: Method
  source:
    remote:
      path: src/Discovery/src/Consul/ConsulPostConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: UpdateDiscoveryOptions
    path: ../Steeltoe/src/Discovery/src/Consul/ConsulPostConfigurer.cs
    startLine: 33
  assemblies:
  - Steeltoe.Discovery.Consul
  namespace: Steeltoe.Discovery.Consul
  summary: "\nPerform post-configuration on ConsulDiscoveryOptions\n"
  example: []
  syntax:
    content: public static void UpdateDiscoveryOptions(IConfiguration config, ConsulDiscoveryOptions options, InetOptions netOptions)
    parameters:
    - id: config
      type: IConfiguration
      description: Application Configuration
    - id: options
      type: Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions
      description: ConsulDiscoveryOptions to configure
    - id: netOptions
      type: InetOptions
      description: Optional InetOptions
    content.vb: Public Shared Sub UpdateDiscoveryOptions(config As IConfiguration, options As ConsulDiscoveryOptions, netOptions As InetOptions)
  overload: Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.Discovery.Consul
  commentId: N:Steeltoe.Discovery.Consul
  name: Steeltoe.Discovery.Consul
  nameWithType: Steeltoe.Discovery.Consul
  fullName: Steeltoe.Discovery.Consul
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions*
  commentId: Overload:Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions
  name: ValidateConsulOptions
  nameWithType: ConsulPostConfigurer.ValidateConsulOptions
  fullName: Steeltoe.Discovery.Consul.ConsulPostConfigurer.ValidateConsulOptions
- uid: Steeltoe.Discovery.Consul.ConsulOptions
  commentId: T:Steeltoe.Discovery.Consul.ConsulOptions
  parent: Steeltoe.Discovery.Consul
  name: ConsulOptions
  nameWithType: ConsulOptions
  fullName: Steeltoe.Discovery.Consul.ConsulOptions
- uid: Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions*
  commentId: Overload:Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions
  name: UpdateDiscoveryOptions
  nameWithType: ConsulPostConfigurer.UpdateDiscoveryOptions
  fullName: Steeltoe.Discovery.Consul.ConsulPostConfigurer.UpdateDiscoveryOptions
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
- uid: Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions
  commentId: T:Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions
  parent: Steeltoe.Discovery.Consul.Discovery
  name: ConsulDiscoveryOptions
  nameWithType: ConsulDiscoveryOptions
  fullName: Steeltoe.Discovery.Consul.Discovery.ConsulDiscoveryOptions
- uid: InetOptions
  commentId: '!:InetOptions'
  isExternal: true
  name: InetOptions
  nameWithType: InetOptions
  fullName: InetOptions
- uid: Steeltoe.Discovery.Consul.Discovery
  commentId: N:Steeltoe.Discovery.Consul.Discovery
  name: Steeltoe.Discovery.Consul.Discovery
  nameWithType: Steeltoe.Discovery.Consul.Discovery
  fullName: Steeltoe.Discovery.Consul.Discovery
