### YamlMime:ManagedReference
items:
- uid: Steeltoe.Management.Endpoint.Security
  commentId: N:Steeltoe.Management.Endpoint.Security
  id: Steeltoe.Management.Endpoint.Security
  children:
  - Steeltoe.Management.Endpoint.Security.EndpointClaim
  - Steeltoe.Management.Endpoint.Security.ISecurityContext
  langs:
  - csharp
  - vb
  name: Steeltoe.Management.Endpoint.Security
  nameWithType: Steeltoe.Management.Endpoint.Security
  fullName: Steeltoe.Management.Endpoint.Security
  type: Namespace
  assemblies:
  - Steeltoe.Management.EndpointBase
references:
- uid: Steeltoe.Management.Endpoint.Security.EndpointClaim
  commentId: T:Steeltoe.Management.Endpoint.Security.EndpointClaim
  parent: Steeltoe.Management.Endpoint.Security
  name: EndpointClaim
  nameWithType: EndpointClaim
  fullName: Steeltoe.Management.Endpoint.Security.EndpointClaim
- uid: Steeltoe.Management.Endpoint.Security.ISecurityContext
  commentId: T:Steeltoe.Management.Endpoint.Security.ISecurityContext
  parent: Steeltoe.Management.Endpoint.Security
  name: ISecurityContext
  nameWithType: ISecurityContext
  fullName: Steeltoe.Management.Endpoint.Security.ISecurityContext
- uid: Steeltoe.Management.Endpoint.Security
  commentId: N:Steeltoe.Management.Endpoint.Security
  name: Steeltoe.Management.Endpoint.Security
  nameWithType: Steeltoe.Management.Endpoint.Security
  fullName: Steeltoe.Management.Endpoint.Security
