### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.IListenerContainerCustomizer
  commentId: T:Steeltoe.Stream.Config.IListenerContainerCustomizer
  id: IListenerContainerCustomizer
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure(System.Object,System.String,System.String)
  langs:
  - csharp
  - vb
  name: IListenerContainerCustomizer
  nameWithType: IListenerContainerCustomizer
  fullName: Steeltoe.Stream.Config.IListenerContainerCustomizer
  type: Interface
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IListenerContainerCustomizer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IListenerContainerCustomizer
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IListenerContainerCustomizer.cs
    startLine: 9
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nTODO: Look at making internal\n"
  example: []
  syntax:
    content: public interface IListenerContainerCustomizer
    content.vb: Public Interface IListenerContainerCustomizer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure(System.Object,System.String,System.String)
  commentId: M:Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure(System.Object,System.String,System.String)
  id: Configure(System.Object,System.String,System.String)
  parent: Steeltoe.Stream.Config.IListenerContainerCustomizer
  langs:
  - csharp
  - vb
  name: Configure(Object, String, String)
  nameWithType: IListenerContainerCustomizer.Configure(Object, String, String)
  fullName: Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure(System.Object, System.String, System.String)
  type: Method
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IListenerContainerCustomizer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IListenerContainerCustomizer.cs
    startLine: 11
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: void Configure(object container, string destinationName, string group)
    parameters:
    - id: container
      type: System.Object
    - id: destinationName
      type: System.String
    - id: group
      type: System.String
    content.vb: Sub Configure(container As Object, destinationName As String, group As String)
  overload: Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure*
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure*
  commentId: Overload:Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure
  name: Configure
  nameWithType: IListenerContainerCustomizer.Configure
  fullName: Steeltoe.Stream.Config.IListenerContainerCustomizer.Configure
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
