### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IQueue
  id: IQueue
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
  - Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
  langs:
  - csharp
  - vb
  name: IQueue
  nameWithType: IQueue
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  type: Interface
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IQueue
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 8
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: 'public interface IQueue : IDeclarable, IServiceNameAware'
    content.vb: >-
      Public Interface IQueue

          Inherits IDeclarable, IServiceNameAware
  inheritedMembers:
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  - Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  - Steeltoe.Common.Services.IServiceNameAware.ServiceName
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
  id: QueueName
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: QueueName
  nameWithType: IQueue.QueueName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: QueueName
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 10
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string QueueName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property QueueName As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
  id: ActualName
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: ActualName
  nameWithType: IQueue.ActualName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ActualName
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 12
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string ActualName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property ActualName As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
  id: IsDurable
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: IsDurable
  nameWithType: IQueue.IsDurable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IsDurable
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 14
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: bool IsDurable { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property IsDurable As Boolean
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
  id: IsExclusive
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: IsExclusive
  nameWithType: IQueue.IsExclusive
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IsExclusive
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 16
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: bool IsExclusive { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property IsExclusive As Boolean
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
  id: IsAutoDelete
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: IsAutoDelete
  nameWithType: IQueue.IsAutoDelete
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IsAutoDelete
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 18
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: bool IsAutoDelete { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Property IsAutoDelete As Boolean
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
  id: MasterLocator
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: MasterLocator
  nameWithType: IQueue.MasterLocator
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MasterLocator
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 20
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: string MasterLocator { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property MasterLocator As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone
  id: Clone
  parent: Steeltoe.Messaging.RabbitMQ.Config.IQueue
  langs:
  - csharp
  - vb
  name: Clone()
  nameWithType: IQueue.Clone()
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone()
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/IQueue.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Clone
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/IQueue.cs
    startLine: 22
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: object Clone()
    return:
      type: System.Object
    content.vb: Function Clone As Object
  overload: Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone*
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: ShouldDeclare
  nameWithType: IDeclarable.ShouldDeclare
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.ShouldDeclare
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: DeclaringAdmins
  nameWithType: IDeclarable.DeclaringAdmins
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.DeclaringAdmins
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: IgnoreDeclarationExceptions
  nameWithType: IDeclarable.IgnoreDeclarationExceptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.IgnoreDeclarationExceptions
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  name: Arguments
  nameWithType: IDeclarable.Arguments
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.Arguments
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: AddArgument(String, Object)
  nameWithType: IDeclarable.AddArgument(String, Object)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String, System.Object)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument(System.String,System.Object)
    name: AddArgument
    nameWithType: IDeclarable.AddArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.AddArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  parent: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  isExternal: true
  name: RemoveArgument(String)
  nameWithType: IDeclarable.RemoveArgument(String)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
  spec.csharp:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument(System.String)
    name: RemoveArgument
    nameWithType: IDeclarable.RemoveArgument
    fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable.RemoveArgument
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Common.Services.IServiceNameAware.ServiceName
  commentId: P:Steeltoe.Common.Services.IServiceNameAware.ServiceName
  parent: Steeltoe.Common.Services.IServiceNameAware
  name: ServiceName
  nameWithType: IServiceNameAware.ServiceName
  fullName: Steeltoe.Common.Services.IServiceNameAware.ServiceName
- uid: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: IDeclarable
  nameWithType: IDeclarable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IDeclarable
- uid: Steeltoe.Common.Services.IServiceNameAware
  commentId: T:Steeltoe.Common.Services.IServiceNameAware
  parent: Steeltoe.Common.Services
  name: IServiceNameAware
  nameWithType: IServiceNameAware
  fullName: Steeltoe.Common.Services.IServiceNameAware
- uid: Steeltoe.Common.Services
  commentId: N:Steeltoe.Common.Services
  name: Steeltoe.Common.Services
  nameWithType: Steeltoe.Common.Services
  fullName: Steeltoe.Common.Services
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
  name: QueueName
  nameWithType: IQueue.QueueName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.QueueName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
  name: ActualName
  nameWithType: IQueue.ActualName
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.ActualName
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
  name: IsDurable
  nameWithType: IQueue.IsDurable
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsDurable
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
  name: IsExclusive
  nameWithType: IQueue.IsExclusive
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsExclusive
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
  name: IsAutoDelete
  nameWithType: IQueue.IsAutoDelete
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.IsAutoDelete
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
  name: MasterLocator
  nameWithType: IQueue.MasterLocator
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.MasterLocator
- uid: Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone
  name: Clone
  nameWithType: IQueue.Clone
  fullName: Steeltoe.Messaging.RabbitMQ.Config.IQueue.Clone
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
