### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  id: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.BinderConfigurations
  - Steeltoe.Stream.Config.BinderOptions
  - Steeltoe.Stream.Config.BindingOptions
  - Steeltoe.Stream.Config.BindingServiceOptions
  - Steeltoe.Stream.Config.ConsumerOptions
  - Steeltoe.Stream.Config.HeaderMode
  - Steeltoe.Stream.Config.IBinderConfigurations
  - Steeltoe.Stream.Config.IBinderOptions
  - Steeltoe.Stream.Config.IBindingOptions
  - Steeltoe.Stream.Config.IConsumerOptions
  - Steeltoe.Stream.Config.IListenerContainerCustomizer
  - Steeltoe.Stream.Config.IMessageSourceCustomizer
  - Steeltoe.Stream.Config.IProducerOptions
  - Steeltoe.Stream.Config.IStreamListenerMethod
  - Steeltoe.Stream.Config.ProducerOptions
  - Steeltoe.Stream.Config.SmartMessageMethodArgumentResolver
  - Steeltoe.Stream.Config.SmartPayloadArgumentResolver
  - Steeltoe.Stream.Config.SpringIntegrationOptions
  - Steeltoe.Stream.Config.StreamListenerMethod
  - Steeltoe.Stream.Config.StreamMessageHandlerMethodFactory
  langs:
  - csharp
  - vb
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
  type: Namespace
  assemblies:
  - Steeltoe.Stream.Abstractions
references:
- uid: Steeltoe.Stream.Config.HeaderMode
  commentId: T:Steeltoe.Stream.Config.HeaderMode
  parent: Steeltoe.Stream.Config
  name: HeaderMode
  nameWithType: HeaderMode
  fullName: Steeltoe.Stream.Config.HeaderMode
- uid: Steeltoe.Stream.Config.IBinderOptions
  commentId: T:Steeltoe.Stream.Config.IBinderOptions
  parent: Steeltoe.Stream.Config
  name: IBinderOptions
  nameWithType: IBinderOptions
  fullName: Steeltoe.Stream.Config.IBinderOptions
- uid: Steeltoe.Stream.Config.IBindingOptions
  commentId: T:Steeltoe.Stream.Config.IBindingOptions
  parent: Steeltoe.Stream.Config
  name: IBindingOptions
  nameWithType: IBindingOptions
  fullName: Steeltoe.Stream.Config.IBindingOptions
- uid: Steeltoe.Stream.Config.IConsumerOptions
  commentId: T:Steeltoe.Stream.Config.IConsumerOptions
  parent: Steeltoe.Stream.Config
  name: IConsumerOptions
  nameWithType: IConsumerOptions
  fullName: Steeltoe.Stream.Config.IConsumerOptions
- uid: Steeltoe.Stream.Config.IListenerContainerCustomizer
  commentId: T:Steeltoe.Stream.Config.IListenerContainerCustomizer
  parent: Steeltoe.Stream.Config
  name: IListenerContainerCustomizer
  nameWithType: IListenerContainerCustomizer
  fullName: Steeltoe.Stream.Config.IListenerContainerCustomizer
- uid: Steeltoe.Stream.Config.IMessageSourceCustomizer
  commentId: T:Steeltoe.Stream.Config.IMessageSourceCustomizer
  parent: Steeltoe.Stream.Config
  name: IMessageSourceCustomizer
  nameWithType: IMessageSourceCustomizer
  fullName: Steeltoe.Stream.Config.IMessageSourceCustomizer
- uid: Steeltoe.Stream.Config.IProducerOptions
  commentId: T:Steeltoe.Stream.Config.IProducerOptions
  parent: Steeltoe.Stream.Config
  name: IProducerOptions
  nameWithType: IProducerOptions
  fullName: Steeltoe.Stream.Config.IProducerOptions
- uid: Steeltoe.Stream.Config.BinderConfigurations
  commentId: T:Steeltoe.Stream.Config.BinderConfigurations
  name: BinderConfigurations
  nameWithType: BinderConfigurations
  fullName: Steeltoe.Stream.Config.BinderConfigurations
- uid: Steeltoe.Stream.Config.BinderOptions
  commentId: T:Steeltoe.Stream.Config.BinderOptions
  name: BinderOptions
  nameWithType: BinderOptions
  fullName: Steeltoe.Stream.Config.BinderOptions
- uid: Steeltoe.Stream.Config.BindingOptions
  commentId: T:Steeltoe.Stream.Config.BindingOptions
  parent: Steeltoe.Stream.Config
  name: BindingOptions
  nameWithType: BindingOptions
  fullName: Steeltoe.Stream.Config.BindingOptions
- uid: Steeltoe.Stream.Config.BindingServiceOptions
  commentId: T:Steeltoe.Stream.Config.BindingServiceOptions
  parent: Steeltoe.Stream.Config
  name: BindingServiceOptions
  nameWithType: BindingServiceOptions
  fullName: Steeltoe.Stream.Config.BindingServiceOptions
- uid: Steeltoe.Stream.Config.ConsumerOptions
  commentId: T:Steeltoe.Stream.Config.ConsumerOptions
  parent: Steeltoe.Stream.Config
  name: ConsumerOptions
  nameWithType: ConsumerOptions
  fullName: Steeltoe.Stream.Config.ConsumerOptions
- uid: Steeltoe.Stream.Config.IBinderConfigurations
  commentId: T:Steeltoe.Stream.Config.IBinderConfigurations
  parent: Steeltoe.Stream.Config
  name: IBinderConfigurations
  nameWithType: IBinderConfigurations
  fullName: Steeltoe.Stream.Config.IBinderConfigurations
- uid: Steeltoe.Stream.Config.IStreamListenerMethod
  commentId: T:Steeltoe.Stream.Config.IStreamListenerMethod
  parent: Steeltoe.Stream.Config
  name: IStreamListenerMethod
  nameWithType: IStreamListenerMethod
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod
- uid: Steeltoe.Stream.Config.ProducerOptions
  commentId: T:Steeltoe.Stream.Config.ProducerOptions
  parent: Steeltoe.Stream.Config
  name: ProducerOptions
  nameWithType: ProducerOptions
  fullName: Steeltoe.Stream.Config.ProducerOptions
- uid: Steeltoe.Stream.Config.SmartMessageMethodArgumentResolver
  commentId: T:Steeltoe.Stream.Config.SmartMessageMethodArgumentResolver
  name: SmartMessageMethodArgumentResolver
  nameWithType: SmartMessageMethodArgumentResolver
  fullName: Steeltoe.Stream.Config.SmartMessageMethodArgumentResolver
- uid: Steeltoe.Stream.Config.SmartPayloadArgumentResolver
  commentId: T:Steeltoe.Stream.Config.SmartPayloadArgumentResolver
  name: SmartPayloadArgumentResolver
  nameWithType: SmartPayloadArgumentResolver
  fullName: Steeltoe.Stream.Config.SmartPayloadArgumentResolver
- uid: Steeltoe.Stream.Config.SpringIntegrationOptions
  commentId: T:Steeltoe.Stream.Config.SpringIntegrationOptions
  name: SpringIntegrationOptions
  nameWithType: SpringIntegrationOptions
  fullName: Steeltoe.Stream.Config.SpringIntegrationOptions
- uid: Steeltoe.Stream.Config.StreamListenerMethod
  commentId: T:Steeltoe.Stream.Config.StreamListenerMethod
  name: StreamListenerMethod
  nameWithType: StreamListenerMethod
  fullName: Steeltoe.Stream.Config.StreamListenerMethod
- uid: Steeltoe.Stream.Config.StreamMessageHandlerMethodFactory
  commentId: T:Steeltoe.Stream.Config.StreamMessageHandlerMethodFactory
  name: StreamMessageHandlerMethodFactory
  nameWithType: StreamMessageHandlerMethodFactory
  fullName: Steeltoe.Stream.Config.StreamMessageHandlerMethodFactory
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
