### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.IStreamListenerMethod
  commentId: T:Steeltoe.Stream.Config.IStreamListenerMethod
  id: IStreamListenerMethod
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  - Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  - Steeltoe.Stream.Config.IStreamListenerMethod.Method
  langs:
  - csharp
  - vb
  name: IStreamListenerMethod
  nameWithType: IStreamListenerMethod
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod
  type: Interface
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IStreamListenerMethod
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
    startLine: 10
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: public interface IStreamListenerMethod
    content.vb: Public Interface IStreamListenerMethod
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Method
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.Method
  id: Method
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  langs:
  - csharp
  - vb
  name: Method
  nameWithType: IStreamListenerMethod.Method
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Method
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Method
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
    startLine: 12
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: MethodInfo Method { get; }
    parameters: []
    return:
      type: System.Reflection.MethodInfo
    content.vb: ReadOnly Property Method As MethodInfo
  overload: Steeltoe.Stream.Config.IStreamListenerMethod.Method*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  id: Attribute
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  langs:
  - csharp
  - vb
  name: Attribute
  nameWithType: IStreamListenerMethod.Attribute
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Attribute
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
    startLine: 14
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: StreamListenerAttribute Attribute { get; }
    parameters: []
    return:
      type: Steeltoe.Stream.Attributes.StreamListenerAttribute
    content.vb: ReadOnly Property Attribute As StreamListenerAttribute
  overload: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  commentId: P:Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  id: ImplementationType
  parent: Steeltoe.Stream.Config.IStreamListenerMethod
  langs:
  - csharp
  - vb
  name: ImplementationType
  nameWithType: IStreamListenerMethod.ImplementationType
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  type: Property
  source:
    remote:
      path: src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ImplementationType
    path: ../Steeltoe/src/Stream/src/StreamBase/Config/IStreamListenerMethod.cs
    startLine: 16
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Config
  syntax:
    content: Type ImplementationType { get; }
    parameters: []
    return:
      type: System.Type
    content.vb: ReadOnly Property ImplementationType As Type
  overload: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Method*
  commentId: Overload:Steeltoe.Stream.Config.IStreamListenerMethod.Method
  name: Method
  nameWithType: IStreamListenerMethod.Method
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Method
- uid: System.Reflection.MethodInfo
  commentId: T:System.Reflection.MethodInfo
  parent: System.Reflection
  isExternal: true
  name: MethodInfo
  nameWithType: MethodInfo
  fullName: System.Reflection.MethodInfo
- uid: System.Reflection
  commentId: N:System.Reflection
  isExternal: true
  name: System.Reflection
  nameWithType: System.Reflection
  fullName: System.Reflection
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute*
  commentId: Overload:Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
  name: Attribute
  nameWithType: IStreamListenerMethod.Attribute
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.Attribute
- uid: Steeltoe.Stream.Attributes.StreamListenerAttribute
  commentId: T:Steeltoe.Stream.Attributes.StreamListenerAttribute
  parent: Steeltoe.Stream.Attributes
  name: StreamListenerAttribute
  nameWithType: StreamListenerAttribute
  fullName: Steeltoe.Stream.Attributes.StreamListenerAttribute
- uid: Steeltoe.Stream.Attributes
  commentId: N:Steeltoe.Stream.Attributes
  name: Steeltoe.Stream.Attributes
  nameWithType: Steeltoe.Stream.Attributes
  fullName: Steeltoe.Stream.Attributes
- uid: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType*
  commentId: Overload:Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
  name: ImplementationType
  nameWithType: IStreamListenerMethod.ImplementationType
  fullName: Steeltoe.Stream.Config.IStreamListenerMethod.ImplementationType
- uid: System.Type
  commentId: T:System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
