### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  commentId: T:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  id: EurekaClientOptions.EurekaHealthConfig
  parent: Steeltoe.Discovery.Eureka
  children:
  - Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor(Steeltoe.Discovery.Eureka.EurekaClientOptions)
  - Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  - Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
  - Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  langs:
  - csharp
  - vb
  name: EurekaClientOptions.EurekaHealthConfig
  nameWithType: EurekaClientOptions.EurekaHealthConfig
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  type: Class
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaClientOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: EurekaHealthConfig
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaClientOptions.cs
    startLine: 55
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public class EurekaHealthConfig
    content.vb: Public Class EurekaHealthConfig
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor(Steeltoe.Discovery.Eureka.EurekaClientOptions)
  commentId: M:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor(Steeltoe.Discovery.Eureka.EurekaClientOptions)
  id: '#ctor(Steeltoe.Discovery.Eureka.EurekaClientOptions)'
  parent: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  langs:
  - csharp
  - vb
  name: EurekaHealthConfig(EurekaClientOptions)
  nameWithType: EurekaClientOptions.EurekaHealthConfig.EurekaHealthConfig(EurekaClientOptions)
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.EurekaHealthConfig(Steeltoe.Discovery.Eureka.EurekaClientOptions)
  type: Constructor
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaClientOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaClientOptions.cs
    startLine: 59
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public EurekaHealthConfig(EurekaClientOptions options)
    parameters:
    - id: options
      type: Steeltoe.Discovery.Eureka.EurekaClientOptions
    content.vb: Public Sub New(options As EurekaClientOptions)
  overload: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
  commentId: P:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
  id: Enabled
  parent: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: EurekaClientOptions.EurekaHealthConfig.Enabled
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
  type: Property
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaClientOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Enabled
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaClientOptions.cs
    startLine: 65
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  commentId: P:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  id: MonitoredApps
  parent: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  langs:
  - csharp
  - vb
  name: MonitoredApps
  nameWithType: EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  type: Property
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaClientOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MonitoredApps
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaClientOptions.cs
    startLine: 73
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public string MonitoredApps { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property MonitoredApps As String
  overload: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  commentId: P:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  id: CheckEnabled
  parent: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig
  langs:
  - csharp
  - vb
  name: CheckEnabled
  nameWithType: EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  type: Property
  source:
    remote:
      path: src/Discovery/src/Eureka/EurekaClientOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CheckEnabled
    path: ../Steeltoe/src/Discovery/src/Eureka/EurekaClientOptions.cs
    startLine: 81
  assemblies:
  - Steeltoe.Discovery.Eureka
  namespace: Steeltoe.Discovery.Eureka
  syntax:
    content: public bool CheckEnabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property CheckEnabled As Boolean
  overload: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Discovery.Eureka
  commentId: N:Steeltoe.Discovery.Eureka
  name: Steeltoe.Discovery.Eureka
  nameWithType: Steeltoe.Discovery.Eureka
  fullName: Steeltoe.Discovery.Eureka
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.#ctor
  name: EurekaHealthConfig
  nameWithType: EurekaClientOptions.EurekaHealthConfig.EurekaHealthConfig
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.EurekaHealthConfig
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions
  commentId: T:Steeltoe.Discovery.Eureka.EurekaClientOptions
  parent: Steeltoe.Discovery.Eureka
  name: EurekaClientOptions
  nameWithType: EurekaClientOptions
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
  name: Enabled
  nameWithType: EurekaClientOptions.EurekaHealthConfig.Enabled
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  name: MonitoredApps
  nameWithType: EurekaClientOptions.EurekaHealthConfig.MonitoredApps
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.MonitoredApps
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled*
  commentId: Overload:Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  name: CheckEnabled
  nameWithType: EurekaClientOptions.EurekaHealthConfig.CheckEnabled
  fullName: Steeltoe.Discovery.Eureka.EurekaClientOptions.EurekaHealthConfig.CheckEnabled
