### YamlMime:ManagedReference
items:
- uid: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  commentId: T:Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  id: RedisCacheConfigurationExtensions
  parent: Steeltoe.Connector.Redis
  children:
  - Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,IConfiguration,System.String)
  - Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,Steeltoe.Connector.Redis.RedisCacheConnectorOptions,System.String)
  - Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,System.String)
  langs:
  - csharp
  - vb
  name: RedisCacheConfigurationExtensions
  nameWithType: RedisCacheConfigurationExtensions
  fullName: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  type: Class
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RedisCacheConfigurationExtensions
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
    startLine: 11
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Redis
  syntax:
    content: public static class RedisCacheConfigurationExtensions
    content.vb: Public Module RedisCacheConfigurationExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,System.String)
  commentId: M:Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,System.String)
  id: CreateRedisServiceConnectorFactory(IConfiguration,System.String)
  isExtensionMethod: true
  parent: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  langs:
  - csharp
  - vb
  name: CreateRedisServiceConnectorFactory(IConfiguration, String)
  nameWithType: RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, String)
  fullName: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, System.String)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CreateRedisServiceConnectorFactory
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
    startLine: 13
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Redis
  syntax:
    content: public static RedisServiceConnectorFactory CreateRedisServiceConnectorFactory(this IConfiguration config, string serviceName = null)
    parameters:
    - id: config
      type: IConfiguration
    - id: serviceName
      type: System.String
    return:
      type: Steeltoe.Connector.Redis.RedisServiceConnectorFactory
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function CreateRedisServiceConnectorFactory(config As IConfiguration, serviceName As String = Nothing) As RedisServiceConnectorFactory
  overload: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,IConfiguration,System.String)
  commentId: M:Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,IConfiguration,System.String)
  id: CreateRedisServiceConnectorFactory(IConfiguration,IConfiguration,System.String)
  isExtensionMethod: true
  parent: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  langs:
  - csharp
  - vb
  name: CreateRedisServiceConnectorFactory(IConfiguration, IConfiguration, String)
  nameWithType: RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, IConfiguration, String)
  fullName: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, IConfiguration, System.String)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CreateRedisServiceConnectorFactory
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
    startLine: 24
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Redis
  syntax:
    content: public static RedisServiceConnectorFactory CreateRedisServiceConnectorFactory(this IConfiguration config, IConfiguration connectorConfiguration, string serviceName = null)
    parameters:
    - id: config
      type: IConfiguration
    - id: connectorConfiguration
      type: IConfiguration
    - id: serviceName
      type: System.String
    return:
      type: Steeltoe.Connector.Redis.RedisServiceConnectorFactory
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function CreateRedisServiceConnectorFactory(config As IConfiguration, connectorConfiguration As IConfiguration, serviceName As String = Nothing) As RedisServiceConnectorFactory
  overload: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,Steeltoe.Connector.Redis.RedisCacheConnectorOptions,System.String)
  commentId: M:Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration,Steeltoe.Connector.Redis.RedisCacheConnectorOptions,System.String)
  id: CreateRedisServiceConnectorFactory(IConfiguration,Steeltoe.Connector.Redis.RedisCacheConnectorOptions,System.String)
  isExtensionMethod: true
  parent: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions
  langs:
  - csharp
  - vb
  name: CreateRedisServiceConnectorFactory(IConfiguration, RedisCacheConnectorOptions, String)
  nameWithType: RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, RedisCacheConnectorOptions, String)
  fullName: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory(IConfiguration, Steeltoe.Connector.Redis.RedisCacheConnectorOptions, System.String)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CreateRedisServiceConnectorFactory
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Redis/RedisCacheConfigurationExtensions.cs
    startLine: 40
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Redis
  syntax:
    content: public static RedisServiceConnectorFactory CreateRedisServiceConnectorFactory(this IConfiguration config, RedisCacheConnectorOptions connectorOptions, string serviceName = null)
    parameters:
    - id: config
      type: IConfiguration
    - id: connectorOptions
      type: Steeltoe.Connector.Redis.RedisCacheConnectorOptions
    - id: serviceName
      type: System.String
    return:
      type: Steeltoe.Connector.Redis.RedisServiceConnectorFactory
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function CreateRedisServiceConnectorFactory(config As IConfiguration, connectorOptions As RedisCacheConnectorOptions, serviceName As String = Nothing) As RedisServiceConnectorFactory
  overload: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.Connector.Redis
  commentId: N:Steeltoe.Connector.Redis
  name: Steeltoe.Connector.Redis
  nameWithType: Steeltoe.Connector.Redis
  fullName: Steeltoe.Connector.Redis
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory*
  commentId: Overload:Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory
  name: CreateRedisServiceConnectorFactory
  nameWithType: RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory
  fullName: Steeltoe.Connector.Redis.RedisCacheConfigurationExtensions.CreateRedisServiceConnectorFactory
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Connector.Redis.RedisServiceConnectorFactory
  commentId: T:Steeltoe.Connector.Redis.RedisServiceConnectorFactory
  parent: Steeltoe.Connector.Redis
  name: RedisServiceConnectorFactory
  nameWithType: RedisServiceConnectorFactory
  fullName: Steeltoe.Connector.Redis.RedisServiceConnectorFactory
- uid: Steeltoe.Connector.Redis.RedisCacheConnectorOptions
  commentId: T:Steeltoe.Connector.Redis.RedisCacheConnectorOptions
  parent: Steeltoe.Connector.Redis
  name: RedisCacheConnectorOptions
  nameWithType: RedisCacheConnectorOptions
  fullName: Steeltoe.Connector.Redis.RedisCacheConnectorOptions
