### YamlMime:ManagedReference
items:
- uid: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration
  id: SerialHystrixConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Serial
  children:
  - Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString(Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration)
  langs:
  - csharp
  - vb
  name: SerialHystrixConfiguration
  nameWithType: SerialHystrixConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration
  type: Class
  source:
    remote:
      path: src/CircuitBreaker/src/HystrixBase/Serial/SerialHystrixConfiguration.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: SerialHystrixConfiguration
    path: ../Steeltoe/src/CircuitBreaker/src/HystrixBase/Serial/SerialHystrixConfiguration.cs
    startLine: 10
  assemblies:
  - Steeltoe.CircuitBreaker.HystrixBase
  namespace: Steeltoe.CircuitBreaker.Hystrix.Serial
  syntax:
    content: public static class SerialHystrixConfiguration
    content.vb: Public Module SerialHystrixConfiguration
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString(Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration)
  commentId: M:Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString(Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration)
  id: ToJsonString(Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration)
  parent: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration
  langs:
  - csharp
  - vb
  name: ToJsonString(HystrixConfiguration)
  nameWithType: SerialHystrixConfiguration.ToJsonString(HystrixConfiguration)
  fullName: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString(Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration)
  type: Method
  source:
    remote:
      path: src/CircuitBreaker/src/HystrixBase/Serial/SerialHystrixConfiguration.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ToJsonString
    path: ../Steeltoe/src/CircuitBreaker/src/HystrixBase/Serial/SerialHystrixConfiguration.cs
    startLine: 12
  assemblies:
  - Steeltoe.CircuitBreaker.HystrixBase
  namespace: Steeltoe.CircuitBreaker.Hystrix.Serial
  syntax:
    content: public static string ToJsonString(HystrixConfiguration config)
    parameters:
    - id: config
      type: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
    return:
      type: System.String
    content.vb: Public Shared Function ToJsonString(config As HystrixConfiguration) As String
  overload: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.CircuitBreaker.Hystrix.Serial
  commentId: N:Steeltoe.CircuitBreaker.Hystrix.Serial
  name: Steeltoe.CircuitBreaker.Hystrix.Serial
  nameWithType: Steeltoe.CircuitBreaker.Hystrix.Serial
  fullName: Steeltoe.CircuitBreaker.Hystrix.Serial
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString*
  commentId: Overload:Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString
  name: ToJsonString
  nameWithType: SerialHystrixConfiguration.ToJsonString
  fullName: Steeltoe.CircuitBreaker.Hystrix.Serial.SerialHystrixConfiguration.ToJsonString
- uid: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
  commentId: T:Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
  parent: Steeltoe.CircuitBreaker.Hystrix.Config
  name: HystrixConfiguration
  nameWithType: HystrixConfiguration
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config.HystrixConfiguration
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.CircuitBreaker.Hystrix.Config
  commentId: N:Steeltoe.CircuitBreaker.Hystrix.Config
  name: Steeltoe.CircuitBreaker.Hystrix.Config
  nameWithType: Steeltoe.CircuitBreaker.Hystrix.Config
  fullName: Steeltoe.CircuitBreaker.Hystrix.Config
