### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration
  commentId: N:Steeltoe.Extensions.Configuration
  id: Steeltoe.Extensions.Configuration
  children:
  - Steeltoe.Extensions.Configuration.AbstractServiceOptions
  - Steeltoe.Extensions.Configuration.Credential
  - Steeltoe.Extensions.Configuration.CredentialConverter
  - Steeltoe.Extensions.Configuration.IPlaceholderResolverProvider
  - Steeltoe.Extensions.Configuration.IServiceCollectionExtensions
  - Steeltoe.Extensions.Configuration.IServicesInfo
  - Steeltoe.Extensions.Configuration.Service
  - Steeltoe.Extensions.Configuration.ServicesOptions
  langs:
  - csharp
  - vb
  name: Steeltoe.Extensions.Configuration
  nameWithType: Steeltoe.Extensions.Configuration
  fullName: Steeltoe.Extensions.Configuration
  type: Namespace
  assemblies:
  - Steeltoe.Extensions.Configuration.Abstractions
references:
- uid: Steeltoe.Extensions.Configuration.AbstractServiceOptions
  commentId: T:Steeltoe.Extensions.Configuration.AbstractServiceOptions
  parent: Steeltoe.Extensions.Configuration
  name: AbstractServiceOptions
  nameWithType: AbstractServiceOptions
  fullName: Steeltoe.Extensions.Configuration.AbstractServiceOptions
- uid: Steeltoe.Extensions.Configuration.Credential
  commentId: T:Steeltoe.Extensions.Configuration.Credential
  name: Credential
  nameWithType: Credential
  fullName: Steeltoe.Extensions.Configuration.Credential
- uid: Steeltoe.Extensions.Configuration.CredentialConverter
  commentId: T:Steeltoe.Extensions.Configuration.CredentialConverter
  parent: Steeltoe.Extensions.Configuration
  name: CredentialConverter
  nameWithType: CredentialConverter
  fullName: Steeltoe.Extensions.Configuration.CredentialConverter
- uid: Steeltoe.Extensions.Configuration.IPlaceholderResolverProvider
  commentId: T:Steeltoe.Extensions.Configuration.IPlaceholderResolverProvider
  parent: Steeltoe.Extensions.Configuration
  name: IPlaceholderResolverProvider
  nameWithType: IPlaceholderResolverProvider
  fullName: Steeltoe.Extensions.Configuration.IPlaceholderResolverProvider
- uid: Steeltoe.Extensions.Configuration.IServiceCollectionExtensions
  commentId: T:Steeltoe.Extensions.Configuration.IServiceCollectionExtensions
  name: IServiceCollectionExtensions
  nameWithType: IServiceCollectionExtensions
  fullName: Steeltoe.Extensions.Configuration.IServiceCollectionExtensions
- uid: Steeltoe.Extensions.Configuration.IServicesInfo
  commentId: T:Steeltoe.Extensions.Configuration.IServicesInfo
  parent: Steeltoe.Extensions.Configuration
  name: IServicesInfo
  nameWithType: IServicesInfo
  fullName: Steeltoe.Extensions.Configuration.IServicesInfo
- uid: Steeltoe.Extensions.Configuration.Service
  commentId: T:Steeltoe.Extensions.Configuration.Service
  parent: Steeltoe.Extensions.Configuration
  name: Service
  nameWithType: Service
  fullName: Steeltoe.Extensions.Configuration.Service
- uid: Steeltoe.Extensions.Configuration.ServicesOptions
  commentId: T:Steeltoe.Extensions.Configuration.ServicesOptions
  parent: Steeltoe.Extensions.Configuration
  name: ServicesOptions
  nameWithType: ServicesOptions
  fullName: Steeltoe.Extensions.Configuration.ServicesOptions
- uid: Steeltoe.Extensions.Configuration
  commentId: N:Steeltoe.Extensions.Configuration
  name: Steeltoe.Extensions.Configuration
  nameWithType: Steeltoe.Extensions.Configuration
  fullName: Steeltoe.Extensions.Configuration
