### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  commentId: T:Steeltoe.Stream.Binding.IMessageChannelConfigurer
  id: IMessageChannelConfigurer
  parent: Steeltoe.Stream.Binding
  children:
  - Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  - Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  langs:
  - csharp
  - vb
  name: IMessageChannelConfigurer
  nameWithType: IMessageChannelConfigurer
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  type: Interface
  source:
    remote:
      path: src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IMessageChannelConfigurer
    path: ../Steeltoe/src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Binding
  syntax:
    content: public interface IMessageChannelConfigurer
    content.vb: Public Interface IMessageChannelConfigurer
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  commentId: M:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  id: ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  parent: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  langs:
  - csharp
  - vb
  name: ConfigureInputChannel(IMessageChannel, String)
  nameWithType: IMessageChannelConfigurer.ConfigureInputChannel(IMessageChannel, String)
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel(Steeltoe.Messaging.IMessageChannel, System.String)
  type: Method
  source:
    remote:
      path: src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigureInputChannel
    path: ../Steeltoe/src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Binding
  syntax:
    content: void ConfigureInputChannel(IMessageChannel messageChannel, string channelName)
    parameters:
    - id: messageChannel
      type: Steeltoe.Messaging.IMessageChannel
    - id: channelName
      type: System.String
    content.vb: Sub ConfigureInputChannel(messageChannel As IMessageChannel, channelName As String)
  overload: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel*
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  commentId: M:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  id: ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel,System.String)
  parent: Steeltoe.Stream.Binding.IMessageChannelConfigurer
  langs:
  - csharp
  - vb
  name: ConfigureOutputChannel(IMessageChannel, String)
  nameWithType: IMessageChannelConfigurer.ConfigureOutputChannel(IMessageChannel, String)
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel(Steeltoe.Messaging.IMessageChannel, System.String)
  type: Method
  source:
    remote:
      path: src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigureOutputChannel
    path: ../Steeltoe/src/Stream/src/StreamBase/Binding/IMessageChannelConfigurer.cs
    startLine: 12
  assemblies:
  - Steeltoe.Stream.StreamBase
  namespace: Steeltoe.Stream.Binding
  syntax:
    content: void ConfigureOutputChannel(IMessageChannel messageChannel, string channelName)
    parameters:
    - id: messageChannel
      type: Steeltoe.Messaging.IMessageChannel
    - id: channelName
      type: System.String
    content.vb: Sub ConfigureOutputChannel(messageChannel As IMessageChannel, channelName As String)
  overload: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel*
references:
- uid: Steeltoe.Stream.Binding
  commentId: N:Steeltoe.Stream.Binding
  name: Steeltoe.Stream.Binding
  nameWithType: Steeltoe.Stream.Binding
  fullName: Steeltoe.Stream.Binding
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel*
  commentId: Overload:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel
  name: ConfigureInputChannel
  nameWithType: IMessageChannelConfigurer.ConfigureInputChannel
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureInputChannel
- uid: Steeltoe.Messaging.IMessageChannel
  commentId: T:Steeltoe.Messaging.IMessageChannel
  parent: Steeltoe.Messaging
  name: IMessageChannel
  nameWithType: IMessageChannel
  fullName: Steeltoe.Messaging.IMessageChannel
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Messaging
  commentId: N:Steeltoe.Messaging
  name: Steeltoe.Messaging
  nameWithType: Steeltoe.Messaging
  fullName: Steeltoe.Messaging
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel*
  commentId: Overload:Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel
  name: ConfigureOutputChannel
  nameWithType: IMessageChannelConfigurer.ConfigureOutputChannel
  fullName: Steeltoe.Stream.Binding.IMessageChannelConfigurer.ConfigureOutputChannel
