### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  commentId: T:Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  id: KubernetesConfigurationBuilderExtensions
  parent: Steeltoe.Extensions.Configuration.Kubernetes
  children:
  - Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder,System.Action{KubernetesClientConfiguration},ILoggerFactory)
  langs:
  - csharp
  - vb
  name: KubernetesConfigurationBuilderExtensions
  nameWithType: KubernetesConfigurationBuilderExtensions
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  type: Class
  source:
    remote:
      path: src/Configuration/src/KubernetesBase/KubernetesConfigurationBuilderExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: KubernetesConfigurationBuilderExtensions
    path: ../Steeltoe/src/Configuration/src/KubernetesBase/KubernetesConfigurationBuilderExtensions.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.KubernetesBase
  namespace: Steeltoe.Extensions.Configuration.Kubernetes
  syntax:
    content: public static class KubernetesConfigurationBuilderExtensions
    content.vb: Public Module KubernetesConfigurationBuilderExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder,System.Action{KubernetesClientConfiguration},ILoggerFactory)
  commentId: M:Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder,System.Action{KubernetesClientConfiguration},ILoggerFactory)
  id: AddKubernetes(IConfigurationBuilder,System.Action{KubernetesClientConfiguration},ILoggerFactory)
  isExtensionMethod: true
  parent: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions
  langs:
  - csharp
  - vb
  name: AddKubernetes(IConfigurationBuilder, Action<KubernetesClientConfiguration>, ILoggerFactory)
  nameWithType: KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder, Action<KubernetesClientConfiguration>, ILoggerFactory)
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder, System.Action<KubernetesClientConfiguration>, ILoggerFactory)
  type: Method
  source:
    remote:
      path: src/Configuration/src/KubernetesBase/KubernetesConfigurationBuilderExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: AddKubernetes
    path: ../Steeltoe/src/Configuration/src/KubernetesBase/KubernetesConfigurationBuilderExtensions.cs
    startLine: 20
  assemblies:
  - Steeltoe.Extensions.Configuration.KubernetesBase
  namespace: Steeltoe.Extensions.Configuration.Kubernetes
  summary: "\nAdd configuration providers for ConfigMaps and Secrets\n"
  example: []
  syntax:
    content: public static IConfigurationBuilder AddKubernetes(this IConfigurationBuilder configurationBuilder, Action<KubernetesClientConfiguration> kubernetesClientConfiguration = null, ILoggerFactory loggerFactory = null)
    parameters:
    - id: configurationBuilder
      type: IConfigurationBuilder
      description: <see cref="!:IConfigurationBuilder"></see>
    - id: kubernetesClientConfiguration
      type: System.Action{KubernetesClientConfiguration}
      description: Kubernetes client configuration customization
    - id: loggerFactory
      type: ILoggerFactory
      description: <see cref="!:ILoggerFactory"></see> for logging within config providers
    return:
      type: IConfigurationBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddKubernetes(configurationBuilder As IConfigurationBuilder, kubernetesClientConfiguration As Action(Of KubernetesClientConfiguration) = Nothing, loggerFactory As ILoggerFactory = Nothing) As IConfigurationBuilder
  overload: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes*
  nameWithType.vb: KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder, Action(Of KubernetesClientConfiguration), ILoggerFactory)
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes(IConfigurationBuilder, System.Action(Of KubernetesClientConfiguration), ILoggerFactory)
  name.vb: AddKubernetes(IConfigurationBuilder, Action(Of KubernetesClientConfiguration), ILoggerFactory)
references:
- uid: Steeltoe.Extensions.Configuration.Kubernetes
  commentId: N:Steeltoe.Extensions.Configuration.Kubernetes
  name: Steeltoe.Extensions.Configuration.Kubernetes
  nameWithType: Steeltoe.Extensions.Configuration.Kubernetes
  fullName: Steeltoe.Extensions.Configuration.Kubernetes
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes*
  commentId: Overload:Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes
  name: AddKubernetes
  nameWithType: KubernetesConfigurationBuilderExtensions.AddKubernetes
  fullName: Steeltoe.Extensions.Configuration.Kubernetes.KubernetesConfigurationBuilderExtensions.AddKubernetes
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: System.Action{KubernetesClientConfiguration}
  commentId: T:System.Action{KubernetesClientConfiguration}
  parent: System
  definition: System.Action`1
  name: Action<KubernetesClientConfiguration>
  nameWithType: Action<KubernetesClientConfiguration>
  fullName: System.Action<KubernetesClientConfiguration>
  nameWithType.vb: Action(Of KubernetesClientConfiguration)
  fullName.vb: System.Action(Of KubernetesClientConfiguration)
  name.vb: Action(Of KubernetesClientConfiguration)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: KubernetesClientConfiguration
    name: KubernetesClientConfiguration
    nameWithType: KubernetesClientConfiguration
    fullName: KubernetesClientConfiguration
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: KubernetesClientConfiguration
    name: KubernetesClientConfiguration
    nameWithType: KubernetesClientConfiguration
    fullName: KubernetesClientConfiguration
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: ILoggerFactory
  isExternal: true
  name: ILoggerFactory
  nameWithType: ILoggerFactory
  fullName: ILoggerFactory
- uid: System.Action`1
  commentId: T:System.Action`1
  isExternal: true
  name: Action<T>
  nameWithType: Action<T>
  fullName: System.Action<T>
  nameWithType.vb: Action(Of T)
  fullName.vb: System.Action(Of T)
  name.vb: Action(Of T)
  spec.csharp:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Action`1
    name: Action
    nameWithType: Action
    fullName: System.Action
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
