### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  id: QueueInformation
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor(System.String,System.UInt32,System.UInt32)
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals(System.Object)
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
  - Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
  langs:
  - csharp
  - vb
  name: QueueInformation
  nameWithType: QueueInformation
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: QueueInformation
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 6
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class QueueInformation
    content.vb: Public Class QueueInformation
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor(System.String,System.UInt32,System.UInt32)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor(System.String,System.UInt32,System.UInt32)
  id: '#ctor(System.String,System.UInt32,System.UInt32)'
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: QueueInformation(String, UInt32, UInt32)
  nameWithType: QueueInformation.QueueInformation(String, UInt32, UInt32)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.QueueInformation(System.String, System.UInt32, System.UInt32)
  type: Constructor
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 8
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public QueueInformation(string name, uint messageCount, uint consumerCount)
    parameters:
    - id: name
      type: System.String
    - id: messageCount
      type: System.UInt32
    - id: consumerCount
      type: System.UInt32
    content.vb: Public Sub New(name As String, messageCount As UInteger, consumerCount As UInteger)
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
  id: Name
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: QueueInformation.Name
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Name
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 15
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public string Name { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Name As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
  id: MessageCount
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: MessageCount
  nameWithType: QueueInformation.MessageCount
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MessageCount
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 17
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public uint MessageCount { get; }
    parameters: []
    return:
      type: System.UInt32
    content.vb: Public ReadOnly Property MessageCount As UInteger
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
  id: ConsumerCount
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: ConsumerCount
  nameWithType: QueueInformation.ConsumerCount
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConsumerCount
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 19
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public uint ConsumerCount { get; }
    parameters: []
    return:
      type: System.UInt32
    content.vb: Public ReadOnly Property ConsumerCount As UInteger
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode
  id: GetHashCode
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: GetHashCode()
  nameWithType: QueueInformation.GetHashCode()
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode()
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GetHashCode
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 21
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public override int GetHashCode()
    return:
      type: System.Int32
    content.vb: Public Overrides Function GetHashCode As Integer
  overridden: System.Object.GetHashCode
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals(System.Object)
  commentId: M:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals(System.Object)
  id: Equals(System.Object)
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation
  langs:
  - csharp
  - vb
  name: Equals(Object)
  nameWithType: QueueInformation.Equals(Object)
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals(System.Object)
  type: Method
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Equals
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueInformation.cs
    startLine: 29
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public override bool Equals(object obj)
    parameters:
    - id: obj
      type: System.Object
    return:
      type: System.Boolean
    content.vb: Public Overrides Function Equals(obj As Object) As Boolean
  overridden: System.Object.Equals(System.Object)
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.#ctor
  name: QueueInformation
  nameWithType: QueueInformation.QueueInformation
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.QueueInformation
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.UInt32
  commentId: T:System.UInt32
  parent: System
  isExternal: true
  name: UInt32
  nameWithType: UInt32
  fullName: System.UInt32
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
  name: Name
  nameWithType: QueueInformation.Name
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Name
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
  name: MessageCount
  nameWithType: QueueInformation.MessageCount
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.MessageCount
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
  name: ConsumerCount
  nameWithType: QueueInformation.ConsumerCount
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.ConsumerCount
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode
  name: GetHashCode
  nameWithType: QueueInformation.GetHashCode
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.GetHashCode
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals
  name: Equals
  nameWithType: QueueInformation.Equals
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueInformation.Equals
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
