### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  id: QueueBuilder.OverFlow
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
  - Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
  - Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
  langs:
  - csharp
  - vb
  name: QueueBuilder.OverFlow
  nameWithType: QueueBuilder.OverFlow
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: OverFlow
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
    startLine: 11
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class OverFlow
    content.vb: Public Class OverFlow
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
  id: DropHead
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  langs:
  - csharp
  - vb
  name: DropHead
  nameWithType: QueueBuilder.OverFlow.DropHead
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: DropHead
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
    startLine: 13
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public static QueueBuilder.OverFlow DropHead { get; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
    content.vb: Public Shared ReadOnly Property DropHead As QueueBuilder.OverFlow
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
  id: RejectPublish
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  langs:
  - csharp
  - vb
  name: RejectPublish
  nameWithType: QueueBuilder.OverFlow.RejectPublish
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RejectPublish
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
    startLine: 15
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public static QueueBuilder.OverFlow RejectPublish { get; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
    content.vb: Public Shared ReadOnly Property RejectPublish As QueueBuilder.OverFlow
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
  id: Value
  parent: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  langs:
  - csharp
  - vb
  name: Value
  nameWithType: QueueBuilder.OverFlow.Value
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Value
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/QueueBuilder.cs
    startLine: 17
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public string Value { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Value As String
  overload: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
  name: DropHead
  nameWithType: QueueBuilder.OverFlow.DropHead
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.DropHead
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: QueueBuilder.OverFlow
  nameWithType: QueueBuilder.OverFlow
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
  name: RejectPublish
  nameWithType: QueueBuilder.OverFlow.RejectPublish
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.RejectPublish
- uid: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
  name: Value
  nameWithType: QueueBuilder.OverFlow.Value
  fullName: Steeltoe.Messaging.RabbitMQ.Config.QueueBuilder.OverFlow.Value
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
