### YamlMime:ManagedReference
items:
- uid: Steeltoe.Stream.Config.IBindingOptions
  commentId: T:Steeltoe.Stream.Config.IBindingOptions
  id: IBindingOptions
  parent: Steeltoe.Stream.Config
  children:
  - Steeltoe.Stream.Config.IBindingOptions.Binder
  - Steeltoe.Stream.Config.IBindingOptions.Consumer
  - Steeltoe.Stream.Config.IBindingOptions.ContentType
  - Steeltoe.Stream.Config.IBindingOptions.Destination
  - Steeltoe.Stream.Config.IBindingOptions.Group
  - Steeltoe.Stream.Config.IBindingOptions.Producer
  langs:
  - csharp
  - vb
  name: IBindingOptions
  nameWithType: IBindingOptions
  fullName: Steeltoe.Stream.Config.IBindingOptions
  type: Interface
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: IBindingOptions
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 9
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  summary: "\nContains the configuration options for a binding\n"
  example: []
  syntax:
    content: public interface IBindingOptions
    content.vb: Public Interface IBindingOptions
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Stream.Config.IBindingOptions.Destination
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.Destination
  id: Destination
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: Destination
  nameWithType: IBindingOptions.Destination
  fullName: Steeltoe.Stream.Config.IBindingOptions.Destination
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Destination
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 11
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: string Destination { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Destination As String
  overload: Steeltoe.Stream.Config.IBindingOptions.Destination*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Stream.Config.IBindingOptions.Group
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.Group
  id: Group
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: Group
  nameWithType: IBindingOptions.Group
  fullName: Steeltoe.Stream.Config.IBindingOptions.Group
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Group
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 13
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: string Group { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Group As String
  overload: Steeltoe.Stream.Config.IBindingOptions.Group*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Stream.Config.IBindingOptions.ContentType
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.ContentType
  id: ContentType
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: ContentType
  nameWithType: IBindingOptions.ContentType
  fullName: Steeltoe.Stream.Config.IBindingOptions.ContentType
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ContentType
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 15
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: string ContentType { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property ContentType As String
  overload: Steeltoe.Stream.Config.IBindingOptions.ContentType*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Stream.Config.IBindingOptions.Binder
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.Binder
  id: Binder
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: Binder
  nameWithType: IBindingOptions.Binder
  fullName: Steeltoe.Stream.Config.IBindingOptions.Binder
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Binder
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 17
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: string Binder { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Property Binder As String
  overload: Steeltoe.Stream.Config.IBindingOptions.Binder*
  modifiers.csharp:
  - get
  - set
- uid: Steeltoe.Stream.Config.IBindingOptions.Consumer
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.Consumer
  id: Consumer
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: Consumer
  nameWithType: IBindingOptions.Consumer
  fullName: Steeltoe.Stream.Config.IBindingOptions.Consumer
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Consumer
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 19
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: IConsumerOptions Consumer { get; }
    parameters: []
    return:
      type: Steeltoe.Stream.Config.IConsumerOptions
    content.vb: ReadOnly Property Consumer As IConsumerOptions
  overload: Steeltoe.Stream.Config.IBindingOptions.Consumer*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Stream.Config.IBindingOptions.Producer
  commentId: P:Steeltoe.Stream.Config.IBindingOptions.Producer
  id: Producer
  parent: Steeltoe.Stream.Config.IBindingOptions
  langs:
  - csharp
  - vb
  name: Producer
  nameWithType: IBindingOptions.Producer
  fullName: Steeltoe.Stream.Config.IBindingOptions.Producer
  type: Property
  source:
    remote:
      path: src/Stream/src/Abstractions/Config/IBindingOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Producer
    path: ../Steeltoe/src/Stream/src/Abstractions/Config/IBindingOptions.cs
    startLine: 21
  assemblies:
  - Steeltoe.Stream.Abstractions
  namespace: Steeltoe.Stream.Config
  syntax:
    content: IProducerOptions Producer { get; }
    parameters: []
    return:
      type: Steeltoe.Stream.Config.IProducerOptions
    content.vb: ReadOnly Property Producer As IProducerOptions
  overload: Steeltoe.Stream.Config.IBindingOptions.Producer*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Steeltoe.Stream.Config
  commentId: N:Steeltoe.Stream.Config
  name: Steeltoe.Stream.Config
  nameWithType: Steeltoe.Stream.Config
  fullName: Steeltoe.Stream.Config
- uid: Steeltoe.Stream.Config.IBindingOptions.Destination*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.Destination
  name: Destination
  nameWithType: IBindingOptions.Destination
  fullName: Steeltoe.Stream.Config.IBindingOptions.Destination
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Stream.Config.IBindingOptions.Group*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.Group
  name: Group
  nameWithType: IBindingOptions.Group
  fullName: Steeltoe.Stream.Config.IBindingOptions.Group
- uid: Steeltoe.Stream.Config.IBindingOptions.ContentType*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.ContentType
  name: ContentType
  nameWithType: IBindingOptions.ContentType
  fullName: Steeltoe.Stream.Config.IBindingOptions.ContentType
- uid: Steeltoe.Stream.Config.IBindingOptions.Binder*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.Binder
  name: Binder
  nameWithType: IBindingOptions.Binder
  fullName: Steeltoe.Stream.Config.IBindingOptions.Binder
- uid: Steeltoe.Stream.Config.IBindingOptions.Consumer*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.Consumer
  name: Consumer
  nameWithType: IBindingOptions.Consumer
  fullName: Steeltoe.Stream.Config.IBindingOptions.Consumer
- uid: Steeltoe.Stream.Config.IConsumerOptions
  commentId: T:Steeltoe.Stream.Config.IConsumerOptions
  parent: Steeltoe.Stream.Config
  name: IConsumerOptions
  nameWithType: IConsumerOptions
  fullName: Steeltoe.Stream.Config.IConsumerOptions
- uid: Steeltoe.Stream.Config.IBindingOptions.Producer*
  commentId: Overload:Steeltoe.Stream.Config.IBindingOptions.Producer
  name: Producer
  nameWithType: IBindingOptions.Producer
  fullName: Steeltoe.Stream.Config.IBindingOptions.Producer
- uid: Steeltoe.Stream.Config.IProducerOptions
  commentId: T:Steeltoe.Stream.Config.IProducerOptions
  parent: Steeltoe.Stream.Config
  name: IProducerOptions
  nameWithType: IProducerOptions
  fullName: Steeltoe.Stream.Config.IProducerOptions
