### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  id: ConfigServerHealthContributor
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  children:
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health
  - Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
  langs:
  - csharp
  - vb
  name: ConfigServerHealthContributor
  nameWithType: ConfigServerHealthContributor
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  type: Class
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigServerHealthContributor
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
    startLine: 13
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: 'public class ConfigServerHealthContributor : IHealthContributor'
    content.vb: >-
      Public Class ConfigServerHealthContributor

          Inherits IHealthContributor
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  commentId: M:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  id: GetHealthContributor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  parent: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  langs:
  - csharp
  - vb
  name: GetHealthContributor(IConfiguration, ILogger<ConfigServerHealthContributor>)
  nameWithType: ConfigServerHealthContributor.GetHealthContributor(IConfiguration, ILogger<ConfigServerHealthContributor>)
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor(IConfiguration, ILogger<Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor>)
  type: Method
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GetHealthContributor
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
    startLine: 15
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public static IHealthContributor GetHealthContributor(IConfiguration configuration, ILogger<ConfigServerHealthContributor> logger = null)
    parameters:
    - id: configuration
      type: IConfiguration
    - id: logger
      type: ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor}
    return:
      type: IHealthContributor
    content.vb: Public Shared Function GetHealthContributor(configuration As IConfiguration, logger As ILogger(Of ConfigServerHealthContributor) = Nothing) As IHealthContributor
  overload: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor*
  nameWithType.vb: ConfigServerHealthContributor.GetHealthContributor(IConfiguration, ILogger(Of ConfigServerHealthContributor))
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
  fullName.vb: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor(IConfiguration, ILogger(Of Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor))
  name.vb: GetHealthContributor(IConfiguration, ILogger(Of ConfigServerHealthContributor))
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
  id: Id
  parent: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: ConfigServerHealthContributor.Id
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Id
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
    startLine: 25
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public string Id { get; }
    parameters: []
    return:
      type: System.String
    content.vb: Public ReadOnly Property Id As String
  overload: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  commentId: M:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})
  id: '#ctor(IConfiguration,ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor})'
  parent: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  langs:
  - csharp
  - vb
  name: ConfigServerHealthContributor(IConfiguration, ILogger<ConfigServerHealthContributor>)
  nameWithType: ConfigServerHealthContributor.ConfigServerHealthContributor(IConfiguration, ILogger<ConfigServerHealthContributor>)
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.ConfigServerHealthContributor(IConfiguration, ILogger<Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor>)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
    startLine: 37
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public ConfigServerHealthContributor(IConfiguration configuration, ILogger<ConfigServerHealthContributor> logger = null)
    parameters:
    - id: configuration
      type: IConfiguration
    - id: logger
      type: ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor}
    content.vb: Public Sub New(configuration As IConfiguration, logger As ILogger(Of ConfigServerHealthContributor) = Nothing)
  overload: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor*
  nameWithType.vb: ConfigServerHealthContributor.ConfigServerHealthContributor(IConfiguration, ILogger(Of ConfigServerHealthContributor))
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.ConfigServerHealthContributor(IConfiguration, ILogger(Of Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor))
  name.vb: ConfigServerHealthContributor(IConfiguration, ILogger(Of ConfigServerHealthContributor))
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health
  commentId: M:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health
  id: Health
  parent: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  langs:
  - csharp
  - vb
  name: Health()
  nameWithType: ConfigServerHealthContributor.Health()
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health()
  type: Method
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Health
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/ConfigServerHealthContributor.cs
    startLine: 44
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public HealthCheckResult Health()
    return:
      type: HealthCheckResult
    content.vb: Public Function Health As HealthCheckResult
  overload: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.ConfigServer
  commentId: N:Steeltoe.Extensions.Configuration.ConfigServer
  name: Steeltoe.Extensions.Configuration.ConfigServer
  nameWithType: Steeltoe.Extensions.Configuration.ConfigServer
  fullName: Steeltoe.Extensions.Configuration.ConfigServer
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor
  name: GetHealthContributor
  nameWithType: ConfigServerHealthContributor.GetHealthContributor
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.GetHealthContributor
- uid: IConfiguration
  isExternal: true
  name: IConfiguration
  nameWithType: IConfiguration
  fullName: IConfiguration
- uid: ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor}
  commentId: '!:ILogger{Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor}'
  definition: ILogger`1
  name: ILogger<ConfigServerHealthContributor>
  nameWithType: ILogger<ConfigServerHealthContributor>
  fullName: ILogger<Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor>
  nameWithType.vb: ILogger(Of ConfigServerHealthContributor)
  fullName.vb: ILogger(Of Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor)
  name.vb: ILogger(Of ConfigServerHealthContributor)
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
    name: ConfigServerHealthContributor
    nameWithType: ConfigServerHealthContributor
    fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
    name: ConfigServerHealthContributor
    nameWithType: ConfigServerHealthContributor
    fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor
  - name: )
    nameWithType: )
    fullName: )
- uid: IHealthContributor
  isExternal: true
  name: IHealthContributor
  nameWithType: IHealthContributor
  fullName: IHealthContributor
- uid: ILogger`1
  isExternal: true
  name: ILogger<>
  nameWithType: ILogger<>
  fullName: ILogger<>
  nameWithType.vb: ILogger(Of )
  fullName.vb: ILogger(Of )
  name.vb: ILogger(Of )
  spec.csharp:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: ILogger`1
    name: ILogger
    nameWithType: ILogger
    fullName: ILogger
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: ''
    nameWithType: ''
    fullName: ''
  - name: )
    nameWithType: )
    fullName: )
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
  name: Id
  nameWithType: ConfigServerHealthContributor.Id
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Id
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.#ctor
  name: ConfigServerHealthContributor
  nameWithType: ConfigServerHealthContributor.ConfigServerHealthContributor
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.ConfigServerHealthContributor
- uid: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health
  name: Health
  nameWithType: ConfigServerHealthContributor.Health
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.ConfigServerHealthContributor.Health
- uid: HealthCheckResult
  isExternal: true
  name: HealthCheckResult
  nameWithType: HealthCheckResult
  fullName: HealthCheckResult
