### YamlMime:ManagedReference
items:
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  commentId: T:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  id: GenericHostingEnvironment
  parent: Steeltoe.Management.Endpoint.Env
  children:
  - Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
  - Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
  - Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
  - Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
  langs:
  - csharp
  - vb
  name: GenericHostingEnvironment
  nameWithType: GenericHostingEnvironment
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  type: Class
  source:
    remote:
      path: src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GenericHostingEnvironment
    path: ../Steeltoe/src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
    startLine: 9
  assemblies:
  - Steeltoe.Management.EndpointBase
  namespace: Steeltoe.Management.Endpoint.Env
  syntax:
    content: 'public class GenericHostingEnvironment : IHostEnvironment'
    content.vb: >-
      Public Class GenericHostingEnvironment

          Inherits IHostEnvironment
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
  commentId: P:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
  id: EnvironmentName
  parent: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  langs:
  - csharp
  - vb
  name: EnvironmentName
  nameWithType: GenericHostingEnvironment.EnvironmentName
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
  type: Property
  source:
    remote:
      path: src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: EnvironmentName
    path: ../Steeltoe/src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
    startLine: 11
  assemblies:
  - Steeltoe.Management.EndpointBase
  namespace: Steeltoe.Management.Endpoint.Env
  syntax:
    content: public string EnvironmentName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property EnvironmentName As String
  overload: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
  commentId: P:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
  id: ApplicationName
  parent: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  langs:
  - csharp
  - vb
  name: ApplicationName
  nameWithType: GenericHostingEnvironment.ApplicationName
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
  type: Property
  source:
    remote:
      path: src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ApplicationName
    path: ../Steeltoe/src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
    startLine: 13
  assemblies:
  - Steeltoe.Management.EndpointBase
  namespace: Steeltoe.Management.Endpoint.Env
  syntax:
    content: public string ApplicationName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ApplicationName As String
  overload: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
  commentId: P:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
  id: ContentRootPath
  parent: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  langs:
  - csharp
  - vb
  name: ContentRootPath
  nameWithType: GenericHostingEnvironment.ContentRootPath
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
  type: Property
  source:
    remote:
      path: src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ContentRootPath
    path: ../Steeltoe/src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
    startLine: 15
  assemblies:
  - Steeltoe.Management.EndpointBase
  namespace: Steeltoe.Management.Endpoint.Env
  syntax:
    content: public string ContentRootPath { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ContentRootPath As String
  overload: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
  commentId: P:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
  id: ContentRootFileProvider
  parent: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment
  langs:
  - csharp
  - vb
  name: ContentRootFileProvider
  nameWithType: GenericHostingEnvironment.ContentRootFileProvider
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
  type: Property
  source:
    remote:
      path: src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ContentRootFileProvider
    path: ../Steeltoe/src/Management/src/EndpointBase/Env/GenericHostingEnvironment.cs
    startLine: 17
  assemblies:
  - Steeltoe.Management.EndpointBase
  namespace: Steeltoe.Management.Endpoint.Env
  syntax:
    content: public IFileProvider ContentRootFileProvider { get; set; }
    parameters: []
    return:
      type: IFileProvider
    content.vb: Public Property ContentRootFileProvider As IFileProvider
  overload: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Management.Endpoint.Env
  commentId: N:Steeltoe.Management.Endpoint.Env
  name: Steeltoe.Management.Endpoint.Env
  nameWithType: Steeltoe.Management.Endpoint.Env
  fullName: Steeltoe.Management.Endpoint.Env
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName*
  commentId: Overload:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
  name: EnvironmentName
  nameWithType: GenericHostingEnvironment.EnvironmentName
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.EnvironmentName
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName*
  commentId: Overload:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
  name: ApplicationName
  nameWithType: GenericHostingEnvironment.ApplicationName
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ApplicationName
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath*
  commentId: Overload:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
  name: ContentRootPath
  nameWithType: GenericHostingEnvironment.ContentRootPath
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootPath
- uid: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider*
  commentId: Overload:Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
  name: ContentRootFileProvider
  nameWithType: GenericHostingEnvironment.ContentRootFileProvider
  fullName: Steeltoe.Management.Endpoint.Env.GenericHostingEnvironment.ContentRootFileProvider
- uid: IFileProvider
  commentId: '!:IFileProvider'
  isExternal: true
  name: IFileProvider
  nameWithType: IFileProvider
  fullName: IFileProvider
