### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions
  id: RabbitOptions.CacheOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
  langs:
  - csharp
  - vb
  name: RabbitOptions.CacheOptions
  nameWithType: RabbitOptions.CacheOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CacheOptions
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 185
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class CacheOptions
    content.vb: Public Class CacheOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
  id: Channel
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions
  langs:
  - csharp
  - vb
  name: Channel
  nameWithType: RabbitOptions.CacheOptions.Channel
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Channel
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 187
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public RabbitOptions.ChannelOptions Channel { get; set; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ChannelOptions
    content.vb: Public Property Channel As RabbitOptions.ChannelOptions
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
  id: Connection
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions
  langs:
  - csharp
  - vb
  name: Connection
  nameWithType: RabbitOptions.CacheOptions.Connection
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Connection
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 189
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public RabbitOptions.ConnectionOptions Connection { get; set; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ConnectionOptions
    content.vb: Public Property Connection As RabbitOptions.ConnectionOptions
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
  name: Channel
  nameWithType: RabbitOptions.CacheOptions.Channel
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Channel
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ChannelOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ChannelOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: RabbitOptions.ChannelOptions
  nameWithType: RabbitOptions.ChannelOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ChannelOptions
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
  name: Connection
  nameWithType: RabbitOptions.CacheOptions.Connection
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.CacheOptions.Connection
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ConnectionOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ConnectionOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: RabbitOptions.ConnectionOptions
  nameWithType: RabbitOptions.ConnectionOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ConnectionOptions
