### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  commentId: T:Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  id: RandomValueExtensions
  parent: Steeltoe.Extensions.Configuration.RandomValue
  children:
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,ILoggerFactory)
  - Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,System.String,ILoggerFactory)
  langs:
  - csharp
  - vb
  name: RandomValueExtensions
  nameWithType: RandomValueExtensions
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  type: Class
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: RandomValueExtensions
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
    startLine: 10
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  syntax:
    content: public static class RandomValueExtensions
    content.vb: Public Module RandomValueExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,ILoggerFactory)
  commentId: M:Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,ILoggerFactory)
  id: AddRandomValueSource(IConfigurationBuilder,ILoggerFactory)
  isExtensionMethod: true
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  langs:
  - csharp
  - vb
  name: AddRandomValueSource(IConfigurationBuilder, ILoggerFactory)
  nameWithType: RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder, ILoggerFactory)
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder, ILoggerFactory)
  type: Method
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: AddRandomValueSource
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
    startLine: 18
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nAdd a random value configuration source to the <see cref=\"!:ConfigurationBuilder\"></see>.\n"
  example: []
  syntax:
    content: public static IConfigurationBuilder AddRandomValueSource(this IConfigurationBuilder builder, ILoggerFactory loggerFactory = null)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: the configuration builder
    - id: loggerFactory
      type: ILoggerFactory
      description: the logger factory to use
    return:
      type: IConfigurationBuilder
      description: builder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddRandomValueSource(builder As IConfigurationBuilder, loggerFactory As ILoggerFactory = Nothing) As IConfigurationBuilder
  overload: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,System.String,ILoggerFactory)
  commentId: M:Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder,System.String,ILoggerFactory)
  id: AddRandomValueSource(IConfigurationBuilder,System.String,ILoggerFactory)
  isExtensionMethod: true
  parent: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions
  langs:
  - csharp
  - vb
  name: AddRandomValueSource(IConfigurationBuilder, String, ILoggerFactory)
  nameWithType: RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder, String, ILoggerFactory)
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource(IConfigurationBuilder, System.String, ILoggerFactory)
  type: Method
  source:
    remote:
      path: src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: AddRandomValueSource
    path: ../Steeltoe/src/Configuration/src/RandomValueBase/RandomValueExtensions.cs
    startLine: 38
  assemblies:
  - Steeltoe.Extensions.Configuration.RandomValueBase
  namespace: Steeltoe.Extensions.Configuration.RandomValue
  summary: "\nAdd a random value configuration source to the <see cref=\"!:ConfigurationBuilder\"></see>.\n"
  example: []
  syntax:
    content: public static IConfigurationBuilder AddRandomValueSource(this IConfigurationBuilder builder, string prefix, ILoggerFactory loggerFactory = null)
    parameters:
    - id: builder
      type: IConfigurationBuilder
      description: the configuration builder
    - id: prefix
      type: System.String
      description: the prefix used for random key values, default &apos;random:&apos;
    - id: loggerFactory
      type: ILoggerFactory
      description: the logger factory to use
    return:
      type: IConfigurationBuilder
      description: builder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function AddRandomValueSource(builder As IConfigurationBuilder, prefix As String, loggerFactory As ILoggerFactory = Nothing) As IConfigurationBuilder
  overload: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.Extensions.Configuration.RandomValue
  commentId: N:Steeltoe.Extensions.Configuration.RandomValue
  name: Steeltoe.Extensions.Configuration.RandomValue
  nameWithType: Steeltoe.Extensions.Configuration.RandomValue
  fullName: Steeltoe.Extensions.Configuration.RandomValue
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource*
  commentId: Overload:Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource
  name: AddRandomValueSource
  nameWithType: RandomValueExtensions.AddRandomValueSource
  fullName: Steeltoe.Extensions.Configuration.RandomValue.RandomValueExtensions.AddRandomValueSource
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: ILoggerFactory
  isExternal: true
  name: ILoggerFactory
  nameWithType: ILoggerFactory
  fullName: ILoggerFactory
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
