### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  id: CloudFoundryConfigurationSource
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  children:
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build(IConfigurationBuilder)
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
  langs:
  - csharp
  - vb
  name: CloudFoundryConfigurationSource
  nameWithType: CloudFoundryConfigurationSource
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  type: Class
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CloudFoundryConfigurationSource
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
    startLine: 8
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: 'public class CloudFoundryConfigurationSource : IConfigurationSource'
    content.vb: >-
      Public Class CloudFoundryConfigurationSource

          Inherits IConfigurationSource
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
  id: SettingsReader
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  langs:
  - csharp
  - vb
  name: SettingsReader
  nameWithType: CloudFoundryConfigurationSource.SettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: SettingsReader
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
    startLine: 10
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public ICloudFoundrySettingsReader SettingsReader { get; set; }
    parameters: []
    return:
      type: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
    content.vb: Public Property SettingsReader As ICloudFoundrySettingsReader
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build(IConfigurationBuilder)
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build(IConfigurationBuilder)
  id: Build(IConfigurationBuilder)
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource
  langs:
  - csharp
  - vb
  name: Build(IConfigurationBuilder)
  nameWithType: CloudFoundryConfigurationSource.Build(IConfigurationBuilder)
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build(IConfigurationBuilder)
  type: Method
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Build
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationSource.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public IConfigurationProvider Build(IConfigurationBuilder builder)
    parameters:
    - id: builder
      type: IConfigurationBuilder
    return:
      type: IConfigurationProvider
    content.vb: Public Function Build(builder As IConfigurationBuilder) As IConfigurationProvider
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
  name: SettingsReader
  nameWithType: CloudFoundryConfigurationSource.SettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.SettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  name: ICloudFoundrySettingsReader
  nameWithType: ICloudFoundrySettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build
  name: Build
  nameWithType: CloudFoundryConfigurationSource.Build
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationSource.Build
- uid: IConfigurationBuilder
  isExternal: true
  name: IConfigurationBuilder
  nameWithType: IConfigurationBuilder
  fullName: IConfigurationBuilder
- uid: IConfigurationProvider
  isExternal: true
  name: IConfigurationProvider
  nameWithType: IConfigurationProvider
  fullName: IConfigurationProvider
