### YamlMime:ManagedReference
items:
- uid: Steeltoe.Connector.Oracle.OracleProviderConfigurer
  commentId: T:Steeltoe.Connector.Oracle.OracleProviderConfigurer
  id: OracleProviderConfigurer
  parent: Steeltoe.Connector.Oracle
  children:
  - Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  - Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  langs:
  - csharp
  - vb
  name: OracleProviderConfigurer
  nameWithType: OracleProviderConfigurer
  fullName: Steeltoe.Connector.Oracle.OracleProviderConfigurer
  type: Class
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: OracleProviderConfigurer
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
    startLine: 8
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Oracle
  syntax:
    content: public class OracleProviderConfigurer
    content.vb: Public Class OracleProviderConfigurer
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  commentId: M:Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  id: Configure(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  parent: Steeltoe.Connector.Oracle.OracleProviderConfigurer
  langs:
  - csharp
  - vb
  name: Configure(OracleServiceInfo, OracleProviderConnectorOptions)
  nameWithType: OracleProviderConfigurer.Configure(OracleServiceInfo, OracleProviderConnectorOptions)
  fullName: Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure(Steeltoe.Connector.Services.OracleServiceInfo, Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Configure
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
    startLine: 10
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Oracle
  syntax:
    content: public string Configure(OracleServiceInfo si, OracleProviderConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.OracleServiceInfo
    - id: configuration
      type: Steeltoe.Connector.Oracle.OracleProviderConnectorOptions
    return:
      type: System.String
    content.vb: Public Function Configure(si As OracleServiceInfo, configuration As OracleProviderConnectorOptions) As String
  overload: Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  commentId: M:Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  id: UpdateConfiguration(Steeltoe.Connector.Services.OracleServiceInfo,Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  parent: Steeltoe.Connector.Oracle.OracleProviderConfigurer
  langs:
  - csharp
  - vb
  name: UpdateConfiguration(OracleServiceInfo, OracleProviderConnectorOptions)
  nameWithType: OracleProviderConfigurer.UpdateConfiguration(OracleServiceInfo, OracleProviderConnectorOptions)
  fullName: Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration(Steeltoe.Connector.Services.OracleServiceInfo, Steeltoe.Connector.Oracle.OracleProviderConnectorOptions)
  type: Method
  source:
    remote:
      path: src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: UpdateConfiguration
    path: ../Steeltoe/src/Connectors/src/ConnectorBase/Oracle/OracleProviderConfigurer.cs
    startLine: 16
  assemblies:
  - Steeltoe.Connector.ConnectorBase
  namespace: Steeltoe.Connector.Oracle
  syntax:
    content: public void UpdateConfiguration(OracleServiceInfo si, OracleProviderConnectorOptions configuration)
    parameters:
    - id: si
      type: Steeltoe.Connector.Services.OracleServiceInfo
    - id: configuration
      type: Steeltoe.Connector.Oracle.OracleProviderConnectorOptions
    content.vb: Public Sub UpdateConfiguration(si As OracleServiceInfo, configuration As OracleProviderConnectorOptions)
  overload: Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Connector.Oracle
  commentId: N:Steeltoe.Connector.Oracle
  name: Steeltoe.Connector.Oracle
  nameWithType: Steeltoe.Connector.Oracle
  fullName: Steeltoe.Connector.Oracle
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure*
  commentId: Overload:Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure
  name: Configure
  nameWithType: OracleProviderConfigurer.Configure
  fullName: Steeltoe.Connector.Oracle.OracleProviderConfigurer.Configure
- uid: Steeltoe.Connector.Services.OracleServiceInfo
  commentId: T:Steeltoe.Connector.Services.OracleServiceInfo
  parent: Steeltoe.Connector.Services
  name: OracleServiceInfo
  nameWithType: OracleServiceInfo
  fullName: Steeltoe.Connector.Services.OracleServiceInfo
- uid: Steeltoe.Connector.Oracle.OracleProviderConnectorOptions
  commentId: T:Steeltoe.Connector.Oracle.OracleProviderConnectorOptions
  parent: Steeltoe.Connector.Oracle
  name: OracleProviderConnectorOptions
  nameWithType: OracleProviderConnectorOptions
  fullName: Steeltoe.Connector.Oracle.OracleProviderConnectorOptions
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Steeltoe.Connector.Services
  commentId: N:Steeltoe.Connector.Services
  name: Steeltoe.Connector.Services
  nameWithType: Steeltoe.Connector.Services
  fullName: Steeltoe.Connector.Services
- uid: Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration*
  commentId: Overload:Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration
  name: UpdateConfiguration
  nameWithType: OracleProviderConfigurer.UpdateConfiguration
  fullName: Steeltoe.Connector.Oracle.OracleProviderConfigurer.UpdateConfiguration
