### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  commentId: T:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  id: SpringCloudConfigRetry
  parent: Steeltoe.Extensions.Configuration.ConfigServer
  children:
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
  - Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
  langs:
  - csharp
  - vb
  name: SpringCloudConfigRetry
  nameWithType: SpringCloudConfigRetry
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  type: Class
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: SpringCloudConfigRetry
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 6
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public class SpringCloudConfigRetry
    content.vb: Public Class SpringCloudConfigRetry
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
  id: Enabled
  parent: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: Enabled
  nameWithType: SpringCloudConfigRetry.Enabled
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Enabled
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 8
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public bool Enabled { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Enabled As Boolean
  overload: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
  id: InitialInterval
  parent: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: InitialInterval
  nameWithType: SpringCloudConfigRetry.InitialInterval
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InitialInterval
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 10
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public int InitialInterval { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property InitialInterval As Integer
  overload: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
  id: MaxInterval
  parent: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: MaxInterval
  nameWithType: SpringCloudConfigRetry.MaxInterval
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MaxInterval
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public int MaxInterval { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxInterval As Integer
  overload: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
  id: Multiplier
  parent: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: Multiplier
  nameWithType: SpringCloudConfigRetry.Multiplier
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Multiplier
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 14
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public double Multiplier { get; set; }
    parameters: []
    return:
      type: System.Double
    content.vb: Public Property Multiplier As Double
  overload: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
  commentId: P:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
  id: MaxAttempts
  parent: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry
  langs:
  - csharp
  - vb
  name: MaxAttempts
  nameWithType: SpringCloudConfigRetry.MaxAttempts
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
  type: Property
  source:
    remote:
      path: src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: MaxAttempts
    path: ../Steeltoe/src/Configuration/src/ConfigServerBase/SpringCloudConfigRetry.cs
    startLine: 16
  assemblies:
  - Steeltoe.Extensions.Configuration.ConfigServerBase
  namespace: Steeltoe.Extensions.Configuration.ConfigServer
  syntax:
    content: public int MaxAttempts { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property MaxAttempts As Integer
  overload: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Extensions.Configuration.ConfigServer
  commentId: N:Steeltoe.Extensions.Configuration.ConfigServer
  name: Steeltoe.Extensions.Configuration.ConfigServer
  nameWithType: Steeltoe.Extensions.Configuration.ConfigServer
  fullName: Steeltoe.Extensions.Configuration.ConfigServer
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
  name: Enabled
  nameWithType: SpringCloudConfigRetry.Enabled
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Enabled
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
  name: InitialInterval
  nameWithType: SpringCloudConfigRetry.InitialInterval
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.InitialInterval
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
  name: MaxInterval
  nameWithType: SpringCloudConfigRetry.MaxInterval
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxInterval
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
  name: Multiplier
  nameWithType: SpringCloudConfigRetry.Multiplier
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.Multiplier
- uid: System.Double
  commentId: T:System.Double
  parent: System
  isExternal: true
  name: Double
  nameWithType: Double
  fullName: System.Double
- uid: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts*
  commentId: Overload:Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
  name: MaxAttempts
  nameWithType: SpringCloudConfigRetry.MaxAttempts
  fullName: Steeltoe.Extensions.Configuration.ConfigServer.SpringCloudConfigRetry.MaxAttempts
