### YamlMime:ManagedReference
items:
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions
  commentId: T:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions
  id: PrometheusExporterExtensions
  parent: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  children:
  - Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter)
  - Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter,System.IO.StreamWriter)
  langs:
  - csharp
  - vb
  name: PrometheusExporterExtensions
  nameWithType: PrometheusExporterExtensions
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions
  type: Class
  source:
    remote:
      path: src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: PrometheusExporterExtensions
    path: ../Steeltoe/src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
    startLine: 15
  assemblies:
  - Steeltoe.Management.OpenTelemetryBase
  namespace: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  summary: "\nHelper to write metrics collection from exporter in Prometheus format.\n"
  example: []
  syntax:
    content: public static class PrometheusExporterExtensions
    content.vb: Public Module PrometheusExporterExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter,System.IO.StreamWriter)
  commentId: M:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter,System.IO.StreamWriter)
  id: WriteMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter,System.IO.StreamWriter)
  isExtensionMethod: true
  parent: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions
  langs:
  - csharp
  - vb
  name: WriteMetricsCollection(PrometheusExporter, StreamWriter)
  nameWithType: PrometheusExporterExtensions.WriteMetricsCollection(PrometheusExporter, StreamWriter)
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter, System.IO.StreamWriter)
  type: Method
  source:
    remote:
      path: src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: WriteMetricsCollection
    path: ../Steeltoe/src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
    startLine: 22
  assemblies:
  - Steeltoe.Management.OpenTelemetryBase
  namespace: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  summary: "\nSerialize to Prometheus Format.\n"
  example: []
  syntax:
    content: public static void WriteMetricsCollection(this PrometheusExporter exporter, StreamWriter writer)
    parameters:
    - id: exporter
      type: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter
      description: Prometheus Exporter.
    - id: writer
      type: System.IO.StreamWriter
      description: StreamWriter to write to.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Sub WriteMetricsCollection(exporter As PrometheusExporter, writer As StreamWriter)
  overload: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter)
  commentId: M:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter)
  id: GetMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter)
  isExtensionMethod: true
  parent: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions
  langs:
  - csharp
  - vb
  name: GetMetricsCollection(PrometheusExporter)
  nameWithType: PrometheusExporterExtensions.GetMetricsCollection(PrometheusExporter)
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection(Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter)
  type: Method
  source:
    remote:
      path: src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: GetMetricsCollection
    path: ../Steeltoe/src/Management/src/OpenTelemetryBase/Metrics/Exporter/PrometheusExporterExtensions.cs
    startLine: 176
  assemblies:
  - Steeltoe.Management.OpenTelemetryBase
  namespace: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  summary: "\nGet Metrics Collection as a string.\n"
  example: []
  syntax:
    content: public static string GetMetricsCollection(this PrometheusExporter exporter)
    parameters:
    - id: exporter
      type: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter
      description: 'Prometheus Exporter. '
    return:
      type: System.String
      description: Metrics serialized to string in Prometheus format.
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function GetMetricsCollection(exporter As PrometheusExporter) As String
  overload: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  commentId: N:Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  name: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  nameWithType: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection*
  commentId: Overload:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection
  name: WriteMetricsCollection
  nameWithType: PrometheusExporterExtensions.WriteMetricsCollection
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.WriteMetricsCollection
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter
  commentId: T:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter
  parent: Steeltoe.Management.OpenTelemetry.Metrics.Exporter
  name: PrometheusExporter
  nameWithType: PrometheusExporter
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporter
- uid: System.IO.StreamWriter
  commentId: T:System.IO.StreamWriter
  parent: System.IO
  isExternal: true
  name: StreamWriter
  nameWithType: StreamWriter
  fullName: System.IO.StreamWriter
- uid: System.IO
  commentId: N:System.IO
  isExternal: true
  name: System.IO
  nameWithType: System.IO
  fullName: System.IO
- uid: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection*
  commentId: Overload:Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection
  name: GetMetricsCollection
  nameWithType: PrometheusExporterExtensions.GetMetricsCollection
  fullName: Steeltoe.Management.OpenTelemetry.Metrics.Exporter.PrometheusExporterExtensions.GetMetricsCollection
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
