### YamlMime:ManagedReference
items:
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions
  commentId: T:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions
  id: ConfigurationDiscoveryClientBuilderExtensions
  parent: Steeltoe.Discovery.Client.SimpleClients
  children:
  - Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances(Steeltoe.Discovery.Client.DiscoveryClientBuilder)
  langs:
  - csharp
  - vb
  name: ConfigurationDiscoveryClientBuilderExtensions
  nameWithType: ConfigurationDiscoveryClientBuilderExtensions
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions
  type: Class
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientBuilderExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ConfigurationDiscoveryClientBuilderExtensions
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientBuilderExtensions.cs
    startLine: 6
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  syntax:
    content: public static class ConfigurationDiscoveryClientBuilderExtensions
    content.vb: Public Module ConfigurationDiscoveryClientBuilderExtensions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances(Steeltoe.Discovery.Client.DiscoveryClientBuilder)
  commentId: M:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances(Steeltoe.Discovery.Client.DiscoveryClientBuilder)
  id: UseConfiguredInstances(Steeltoe.Discovery.Client.DiscoveryClientBuilder)
  isExtensionMethod: true
  parent: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions
  langs:
  - csharp
  - vb
  name: UseConfiguredInstances(DiscoveryClientBuilder)
  nameWithType: ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances(DiscoveryClientBuilder)
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances(Steeltoe.Discovery.Client.DiscoveryClientBuilder)
  type: Method
  source:
    remote:
      path: src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientBuilderExtensions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: UseConfiguredInstances
    path: ../Steeltoe/src/Discovery/src/ClientBase/SimpleClients/ConfigurationDiscoveryClientBuilderExtensions.cs
    startLine: 22
  assemblies:
  - Steeltoe.Discovery.ClientBase
  namespace: Steeltoe.Discovery.Client.SimpleClients
  summary: "\nAllows the use of IDiscoveryClient model built from IConfiguration instead of a hosted service registry\n"
  remarks: "\nBuild your list of service instances under the configuration prefix discovery:services<p></p>\nFor example:\n&quot;discovery&quot;: {\n&quot;services&quot;: [\n  { &quot;serviceId&quot;: &quot;CartService&quot;, &quot;host&quot;: &quot;knownhost1&quot;, &quot;port&quot;: 443, &quot;isSecure&quot;: true },\n  { &quot;serviceId&quot;: &quot;CartService&quot;, &quot;host&quot;: &quot;knownhost2&quot;, &quot;port&quot;: 443, &quot;isSecure&quot;: true },\n]\n}\n"
  example: []
  syntax:
    content: public static DiscoveryClientBuilder UseConfiguredInstances(this DiscoveryClientBuilder clientBuilder)
    parameters:
    - id: clientBuilder
      type: Steeltoe.Discovery.Client.DiscoveryClientBuilder
      description: this
    return:
      type: Steeltoe.Discovery.Client.DiscoveryClientBuilder
    content.vb: >-
      <ExtensionAttribute>

      Public Shared Function UseConfiguredInstances(clientBuilder As DiscoveryClientBuilder) As DiscoveryClientBuilder
  overload: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances*
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: Steeltoe.Discovery.Client.SimpleClients
  commentId: N:Steeltoe.Discovery.Client.SimpleClients
  name: Steeltoe.Discovery.Client.SimpleClients
  nameWithType: Steeltoe.Discovery.Client.SimpleClients
  fullName: Steeltoe.Discovery.Client.SimpleClients
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances*
  commentId: Overload:Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances
  name: UseConfiguredInstances
  nameWithType: ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances
  fullName: Steeltoe.Discovery.Client.SimpleClients.ConfigurationDiscoveryClientBuilderExtensions.UseConfiguredInstances
- uid: Steeltoe.Discovery.Client.DiscoveryClientBuilder
  commentId: T:Steeltoe.Discovery.Client.DiscoveryClientBuilder
  parent: Steeltoe.Discovery.Client
  name: DiscoveryClientBuilder
  nameWithType: DiscoveryClientBuilder
  fullName: Steeltoe.Discovery.Client.DiscoveryClientBuilder
- uid: Steeltoe.Discovery.Client
  commentId: N:Steeltoe.Discovery.Client
  name: Steeltoe.Discovery.Client
  nameWithType: Steeltoe.Discovery.Client
  fullName: Steeltoe.Discovery.Client
