### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  id: ICloudFoundrySettingsReader
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  children:
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
  - Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
  langs:
  - csharp
  - vb
  name: ICloudFoundrySettingsReader
  nameWithType: ICloudFoundrySettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  type: Interface
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ICloudFoundrySettingsReader
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 6
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public interface ICloudFoundrySettingsReader
    content.vb: Public Interface ICloudFoundrySettingsReader
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
  id: ApplicationJson
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: ApplicationJson
  nameWithType: ICloudFoundrySettingsReader.ApplicationJson
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ApplicationJson
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 8
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string ApplicationJson { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ApplicationJson As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
  id: InstanceId
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: InstanceId
  nameWithType: ICloudFoundrySettingsReader.InstanceId
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InstanceId
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 10
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string InstanceId { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property InstanceId As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
  id: InstanceIndex
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: InstanceIndex
  nameWithType: ICloudFoundrySettingsReader.InstanceIndex
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InstanceIndex
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string InstanceIndex { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property InstanceIndex As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
  id: InstanceInternalIp
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: InstanceInternalIp
  nameWithType: ICloudFoundrySettingsReader.InstanceInternalIp
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InstanceInternalIp
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 14
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string InstanceInternalIp { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property InstanceInternalIp As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
  id: InstanceIp
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: InstanceIp
  nameWithType: ICloudFoundrySettingsReader.InstanceIp
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InstanceIp
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 16
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string InstanceIp { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property InstanceIp As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
  id: InstancePort
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: InstancePort
  nameWithType: ICloudFoundrySettingsReader.InstancePort
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: InstancePort
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 18
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string InstancePort { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property InstancePort As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
  commentId: P:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
  id: ServicesJson
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  langs:
  - csharp
  - vb
  name: ServicesJson
  nameWithType: ICloudFoundrySettingsReader.ServicesJson
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
  type: Property
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ServicesJson
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/ICloudFoundrySettingsReader.cs
    startLine: 20
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: string ServicesJson { get; }
    parameters: []
    return:
      type: System.String
    content.vb: ReadOnly Property ServicesJson As String
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson*
  modifiers.csharp:
  - get
  modifiers.vb:
  - ReadOnly
references:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
  name: ApplicationJson
  nameWithType: ICloudFoundrySettingsReader.ApplicationJson
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ApplicationJson
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
  name: InstanceId
  nameWithType: ICloudFoundrySettingsReader.InstanceId
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceId
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
  name: InstanceIndex
  nameWithType: ICloudFoundrySettingsReader.InstanceIndex
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIndex
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
  name: InstanceInternalIp
  nameWithType: ICloudFoundrySettingsReader.InstanceInternalIp
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceInternalIp
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
  name: InstanceIp
  nameWithType: ICloudFoundrySettingsReader.InstanceIp
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstanceIp
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
  name: InstancePort
  nameWithType: ICloudFoundrySettingsReader.InstancePort
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.InstancePort
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
  name: ServicesJson
  nameWithType: ICloudFoundrySettingsReader.ServicesJson
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader.ServicesJson
