### YamlMime:ManagedReference
items:
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions
  id: RabbitOptions.ListenerOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  children:
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
  - Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
  langs:
  - csharp
  - vb
  name: RabbitOptions.ListenerOptions
  nameWithType: RabbitOptions.ListenerOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions
  type: Class
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: ListenerOptions
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 192
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public class ListenerOptions
    content.vb: Public Class ListenerOptions
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
  id: Type
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions
  langs:
  - csharp
  - vb
  name: Type
  nameWithType: RabbitOptions.ListenerOptions.Type
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Type
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 194
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public ContainerType Type { get; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
    content.vb: Public ReadOnly Property Type As ContainerType
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type*
  modifiers.csharp:
  - public
  - get
  modifiers.vb:
  - Public
  - ReadOnly
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
  commentId: P:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
  id: Direct
  parent: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions
  langs:
  - csharp
  - vb
  name: Direct
  nameWithType: RabbitOptions.ListenerOptions.Direct
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
  type: Property
  source:
    remote:
      path: src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Direct
    path: ../Steeltoe/src/Messaging/src/RabbitMQ/Config/RabbitOptions.cs
    startLine: 196
  assemblies:
  - Steeltoe.Messaging.RabbitMQ
  namespace: Steeltoe.Messaging.RabbitMQ.Config
  syntax:
    content: public RabbitOptions.DirectContainerOptions Direct { get; set; }
    parameters: []
    return:
      type: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.DirectContainerOptions
    content.vb: Public Property Direct As RabbitOptions.DirectContainerOptions
  overload: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: Steeltoe.Messaging.RabbitMQ.Config
  commentId: N:Steeltoe.Messaging.RabbitMQ.Config
  name: Steeltoe.Messaging.RabbitMQ.Config
  nameWithType: Steeltoe.Messaging.RabbitMQ.Config
  fullName: Steeltoe.Messaging.RabbitMQ.Config
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
  name: Type
  nameWithType: RabbitOptions.ListenerOptions.Type
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Type
- uid: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.ContainerType
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: ContainerType
  nameWithType: ContainerType
  fullName: Steeltoe.Messaging.RabbitMQ.Config.ContainerType
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct*
  commentId: Overload:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
  name: Direct
  nameWithType: RabbitOptions.ListenerOptions.Direct
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.ListenerOptions.Direct
- uid: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.DirectContainerOptions
  commentId: T:Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.DirectContainerOptions
  parent: Steeltoe.Messaging.RabbitMQ.Config
  name: RabbitOptions.DirectContainerOptions
  nameWithType: RabbitOptions.DirectContainerOptions
  fullName: Steeltoe.Messaging.RabbitMQ.Config.RabbitOptions.DirectContainerOptions
