### YamlMime:ManagedReference
items:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  id: CloudFoundryConfigurationProvider
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  children:
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor(Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader)
  - Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load
  langs:
  - csharp
  - vb
  name: CloudFoundryConfigurationProvider
  nameWithType: CloudFoundryConfigurationProvider
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  type: Class
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: CloudFoundryConfigurationProvider
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
    startLine: 12
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: 'public class CloudFoundryConfigurationProvider : ConfigurationProvider'
    content.vb: >-
      Public Class CloudFoundryConfigurationProvider

          Inherits ConfigurationProvider
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor(Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader)
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor(Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader)
  id: '#ctor(Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader)'
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  langs:
  - csharp
  - vb
  name: CloudFoundryConfigurationProvider(ICloudFoundrySettingsReader)
  nameWithType: CloudFoundryConfigurationProvider.CloudFoundryConfigurationProvider(ICloudFoundrySettingsReader)
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.CloudFoundryConfigurationProvider(Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader)
  type: Constructor
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: .ctor
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
    startLine: 16
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public CloudFoundryConfigurationProvider(ICloudFoundrySettingsReader settingsReader)
    parameters:
    - id: settingsReader
      type: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
    content.vb: Public Sub New(settingsReader As ICloudFoundrySettingsReader)
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load
  commentId: M:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load
  id: Load
  parent: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider
  langs:
  - csharp
  - vb
  name: Load()
  nameWithType: CloudFoundryConfigurationProvider.Load()
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load()
  type: Method
  source:
    remote:
      path: src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
      branch: master
      repo: https://github.com/SteeltoeOSS/steeltoe
    id: Load
    path: ../Steeltoe/src/Configuration/src/CloudFoundryBase/CloudFoundryConfigurationProvider.cs
    startLine: 28
  assemblies:
  - Steeltoe.Extensions.Configuration.CloudFoundryBase
  namespace: Steeltoe.Extensions.Configuration.CloudFoundry
  syntax:
    content: public override void Load()
    content.vb: Public Overrides Sub Load
  overload: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load*
  modifiers.csharp:
  - public
  - override
  modifiers.vb:
  - Public
  - Overrides
references:
- uid: Steeltoe.Extensions.Configuration.CloudFoundry
  commentId: N:Steeltoe.Extensions.Configuration.CloudFoundry
  name: Steeltoe.Extensions.Configuration.CloudFoundry
  nameWithType: Steeltoe.Extensions.Configuration.CloudFoundry
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.#ctor
  name: CloudFoundryConfigurationProvider
  nameWithType: CloudFoundryConfigurationProvider.CloudFoundryConfigurationProvider
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.CloudFoundryConfigurationProvider
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  commentId: T:Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
  parent: Steeltoe.Extensions.Configuration.CloudFoundry
  name: ICloudFoundrySettingsReader
  nameWithType: ICloudFoundrySettingsReader
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.ICloudFoundrySettingsReader
- uid: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load*
  commentId: Overload:Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load
  name: Load
  nameWithType: CloudFoundryConfigurationProvider.Load
  fullName: Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfigurationProvider.Load
